/*
 * ABAnyadirCliente.java
 *
 * Created on 03-oct-2009, 0:25:10
 */

package neg;

import data.Cliente;
import java.io.UnsupportedEncodingException;
import java.net.UnknownHostException;
import java.security.NoSuchAlgorithmException;
import java.util.Date;
import utils.Utilidades;
import utils.LimitadorDeDocumento;
import data.DbConnection;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author lito
 */
public class CSAnyadirCliente extends javax.swing.JPanel
{
    /** Creates new form ABAnyadirCliente */
    public CSAnyadirCliente() throws SQLException
    {
        CSDesktop.menuNuevoCliente.setEnabled(false);
        Date hoy = new Date();

        initComponents();

        jDateChooserAlta.setDate(hoy);
        getFPagoClientes();
        getDepartamentoContacto();
        getComercial();
        limitacionesCampos();


        KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonGuardar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };

        for (int k = 0; k < this.getComponents().length; k ++)
        {
            if (this.getComponents()[k] != jComboBoxDepartamento &&
                this.getComponents()[k] != jComboBoxEstado &&
                this.getComponents()[k] != jComboBoxFPago &&
                this.getComponents()[k] != jComboBoxPlazo &&
                this.getComponents()[k] != jComboBoxComercial &&
                this.getComponents()[k] != jComboBoxTarifa &&
                this.getComponents()[k] != jComboBoxProvincia &&
                this.getComponents()[k] != jComboBoxTipo)
            {
                this.getComponents()[k].addKeyListener(l);                
            }
        }

        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        lDNI = new javax.swing.JLabel();
        jTextDNI = new javax.swing.JTextField();
        lDireccion = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        lCodPostal = new javax.swing.JLabel();
        jTextCodPostal = new javax.swing.JTextField();
        lPoblacion = new javax.swing.JLabel();
        jTextPoblacion = new javax.swing.JTextField();
        lProvincia = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        lFax = new javax.swing.JLabel();
        jTextFax = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        lNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        lPContacto = new javax.swing.JLabel();
        lNombreCon = new javax.swing.JLabel();
        lDepartamento = new javax.swing.JLabel();
        jComboBoxDepartamento = new javax.swing.JComboBox();
        lTelefonoCon = new javax.swing.JLabel();
        jTextTelefonoCon = new javax.swing.JTextField();
        lEmailCon = new javax.swing.JLabel();
        lTelefono2 = new javax.swing.JLabel();
        jTextTelefono2 = new javax.swing.JTextField();
        lTelefonoCon1 = new javax.swing.JLabel();
        jTextTelefonoCon2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProvincia = new javax.swing.JComboBox();
        jTextEmail = new javax.swing.JTextField();
        jTextEmailCon = new javax.swing.JTextField();
        lWeb = new javax.swing.JLabel();
        jTextWeb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextNombreCon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lComercial = new javax.swing.JLabel();
        jComboBoxComercial = new javax.swing.JComboBox();
        lPContacto1 = new javax.swing.JLabel();
        lDireccion1 = new javax.swing.JLabel();
        lCodPostalFiscal = new javax.swing.JLabel();
        jTextDireccionFiscal = new javax.swing.JTextField();
        jTextCodPostalFiscal = new javax.swing.JTextField();
        lPoblacionFiscal = new javax.swing.JLabel();
        jTextPoblacionFiscal = new javax.swing.JTextField();
        lProvinciaFiscal = new javax.swing.JLabel();
        jComboBoxProvinciaFiscal = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        jTextEntidad = new javax.swing.JTextField();
        jTextSucursal = new javax.swing.JTextField();
        jComboBoxPlazo = new javax.swing.JComboBox();
        lPlazo = new javax.swing.JLabel();
        jTextDigito = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox();
        lEstado = new javax.swing.JLabel();
        lNumCuenta = new javax.swing.JLabel();
        jTextNumCuenta = new javax.swing.JTextField();
        lFPago = new javax.swing.JLabel();
        jComboBoxFPago = new javax.swing.JComboBox();
        lFactura = new javax.swing.JLabel();
        lDiasPlazo = new javax.swing.JLabel();
        jTextDiasPlazo = new javax.swing.JTextField();
        jDateChooserAlta = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lTarifa = new javax.swing.JLabel();
        jComboBoxTarifa = new javax.swing.JComboBox();
        lTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox();

        lNombre.setForeground(new java.awt.Color(0, 0, 100));
        lNombre.setText("Nombre");
        lNombre.setName("lNombre"); // NOI18N

        jTextNombre.setName("jTextNombre"); // NOI18N
        jTextNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreFocusLost(evt);
            }
        });

        lDNI.setForeground(new java.awt.Color(0, 0, 100));
        lDNI.setText("DNI/CIF");
        lDNI.setName("lDNI"); // NOI18N

        jTextDNI.setName("jTextDNI"); // NOI18N
        jTextDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDNIFocusLost(evt);
            }
        });

        lDireccion.setForeground(new java.awt.Color(0, 0, 100));
        lDireccion.setText("Dirección");
        lDireccion.setName("lDireccion"); // NOI18N

        jTextDireccion.setName("jTextDireccion"); // NOI18N
        jTextDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionFocusLost(evt);
            }
        });

        lCodPostal.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostal.setLabelFor(jTextCodPostal);
        lCodPostal.setText("Código Postal");
        lCodPostal.setName("lCodPostal"); // NOI18N

        jTextCodPostal.setName("jTextCodPostal"); // NOI18N

        lPoblacion.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacion.setText("Población");
        lPoblacion.setName("lPoblacion"); // NOI18N

        jTextPoblacion.setName("jTextPoblacion"); // NOI18N
        jTextPoblacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionFocusLost(evt);
            }
        });

        lProvincia.setForeground(new java.awt.Color(0, 0, 100));
        lProvincia.setText("Provincia");
        lProvincia.setName("lProvincia"); // NOI18N

        lTelefono.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono.setText("Teléfono");
        lTelefono.setName("lTelefono"); // NOI18N

        jTextTelefono.setMinimumSize(new java.awt.Dimension(9, 9));
        jTextTelefono.setName("jTextTelefono"); // NOI18N

        lFax.setForeground(new java.awt.Color(0, 0, 100));
        lFax.setText("Fax");
        lFax.setName("lFax"); // NOI18N

        jTextFax.setName("jTextFax"); // NOI18N

        lEmail.setForeground(new java.awt.Color(0, 0, 100));
        lEmail.setText("Email");
        lEmail.setName("lEmail"); // NOI18N

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setName("jButtonGuardar"); // NOI18N
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        lNumero.setForeground(new java.awt.Color(0, 0, 100));
        lNumero.setText("    Nº. Cliente  CL/");
        lNumero.setName("lNumero"); // NOI18N

        jTextNumero.setEditable(false);
        jTextNumero.setEnabled(false);
        jTextNumero.setName("jTextNumero"); // NOI18N

        lPContacto.setFont(new java.awt.Font("Tahoma", 1, 11));
        lPContacto.setForeground(new java.awt.Color(170, 16, 4));
        lPContacto.setText("PERSONA DE CONTACTO");
        lPContacto.setName("lPContacto"); // NOI18N

        lNombreCon.setForeground(new java.awt.Color(0, 0, 100));
        lNombreCon.setText("Nombre");
        lNombreCon.setName("lNombreCon"); // NOI18N

        lDepartamento.setForeground(new java.awt.Color(0, 0, 100));
        lDepartamento.setText("Departamento");
        lDepartamento.setName("lDepartamento"); // NOI18N

        jComboBoxDepartamento.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxDepartamento.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxDepartamento.setName("jComboBoxDepartamento"); // NOI18N

        lTelefonoCon.setForeground(new java.awt.Color(0, 0, 100));
        lTelefonoCon.setText("Teléfono");
        lTelefonoCon.setName("lTelefonoCon"); // NOI18N

        jTextTelefonoCon.setName("jTextTelefonoCon"); // NOI18N

        lEmailCon.setForeground(new java.awt.Color(0, 0, 100));
        lEmailCon.setText("Email");
        lEmailCon.setName("lEmailCon"); // NOI18N

        lTelefono2.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono2.setText("   Teléfono2");
        lTelefono2.setName("lTelefono2"); // NOI18N

        jTextTelefono2.setMinimumSize(new java.awt.Dimension(9, 9));
        jTextTelefono2.setName("jTextTelefono2"); // NOI18N

        lTelefonoCon1.setForeground(new java.awt.Color(0, 0, 100));
        lTelefonoCon1.setText("Teléfono 2");
        lTelefonoCon1.setName("lTelefonoCon1"); // NOI18N

        jTextTelefonoCon2.setName("jTextTelefonoCon2"); // NOI18N

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("* Campos obligatorios");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabelO.setForeground(new java.awt.Color(204, 0, 0));
        jLabelO.setText("*");
        jLabelO.setName("jLabelO"); // NOI18N

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("*");
        jLabel2.setName("jLabel2"); // NOI18N

        jComboBoxProvincia.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvincia.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvincia.setName("jComboBoxProvincia"); // NOI18N

        jTextEmail.setName("jTextEmail"); // NOI18N
        jTextEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailFocusLost(evt);
            }
        });

        jTextEmailCon.setName("jTextEmailCon"); // NOI18N
        jTextEmailCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailConFocusLost(evt);
            }
        });

        lWeb.setForeground(new java.awt.Color(0, 0, 100));
        lWeb.setText("Web");
        lWeb.setName("lWeb"); // NOI18N

        jTextWeb.setName("jTextWeb"); // NOI18N
        jTextWeb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextWebFocusLost(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("*");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("*");
        jLabel8.setName("jLabel8"); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator1.setName("jSeparator1"); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator2.setName("jSeparator2"); // NOI18N

        jTextNombreCon.setName("jTextNombreCon"); // NOI18N
        jTextNombreCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreConFocusLost(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("*");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("*");
        jLabel10.setName("jLabel10"); // NOI18N

        lComercial.setForeground(new java.awt.Color(0, 0, 100));
        lComercial.setText("Comercial");
        lComercial.setName("lComercial"); // NOI18N

        jComboBoxComercial.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxComercial.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxComercial.setName("jComboBoxComercial"); // NOI18N

        lPContacto1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lPContacto1.setForeground(new java.awt.Color(170, 16, 4));
        lPContacto1.setText("DOMICILIO FISCAL");
        lPContacto1.setName("lPContacto1"); // NOI18N

        lDireccion1.setForeground(new java.awt.Color(0, 0, 100));
        lDireccion1.setText("Dirección");
        lDireccion1.setName("lDireccion1"); // NOI18N

        lCodPostalFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostalFiscal.setLabelFor(jTextCodPostal);
        lCodPostalFiscal.setText("Código Postal");
        lCodPostalFiscal.setName("lCodPostalFiscal"); // NOI18N

        jTextDireccionFiscal.setName("jTextDireccionFiscal"); // NOI18N
        jTextDireccionFiscal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionFiscalFocusLost(evt);
            }
        });

        jTextCodPostalFiscal.setName("jTextCodPostalFiscal"); // NOI18N

        lPoblacionFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionFiscal.setText("Población");
        lPoblacionFiscal.setName("lPoblacionFiscal"); // NOI18N

        jTextPoblacionFiscal.setName("jTextPoblacionFiscal"); // NOI18N
        jTextPoblacionFiscal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionFiscalFocusLost(evt);
            }
        });

        lProvinciaFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaFiscal.setText("Provincia");
        lProvinciaFiscal.setName("lProvinciaFiscal"); // NOI18N

        jComboBoxProvinciaFiscal.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaFiscal.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaFiscal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaFiscal.setName("jComboBoxProvinciaFiscal"); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator3.setName("jSeparator3"); // NOI18N

        jTextEntidad.setEnabled(false);
        jTextEntidad.setName("jTextEntidad"); // NOI18N

        jTextSucursal.setEnabled(false);
        jTextSucursal.setName("jTextSucursal"); // NOI18N

        jComboBoxPlazo.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxPlazo.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxPlazo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30 días FF", "15 días FF", "45 días FF", "60 días FF", "Especial" }));
        jComboBoxPlazo.setName("jComboBoxPlazo"); // NOI18N
        jComboBoxPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlazoActionPerformed(evt);
            }
        });

        lPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lPlazo.setText("   Plazo");
        lPlazo.setName("lPlazo"); // NOI18N

        jTextDigito.setEnabled(false);
        jTextDigito.setName("jTextDigito"); // NOI18N

        jComboBoxEstado.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxEstado.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        jComboBoxEstado.setName("jComboBoxEstado"); // NOI18N

        lEstado.setForeground(new java.awt.Color(0, 0, 100));
        lEstado.setText("    Estado");
        lEstado.setName("lEstado"); // NOI18N

        lNumCuenta.setForeground(new java.awt.Color(0, 0, 100));
        lNumCuenta.setText("Núm. cuenta");
        lNumCuenta.setName("lNumCuenta"); // NOI18N

        jTextNumCuenta.setEnabled(false);
        jTextNumCuenta.setName("jTextNumCuenta"); // NOI18N

        lFPago.setForeground(new java.awt.Color(0, 0, 100));
        lFPago.setText("Forma de Pago");
        lFPago.setName("lFPago"); // NOI18N

        jComboBoxFPago.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxFPago.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxFPago.setName("jComboBoxFPago"); // NOI18N
        jComboBoxFPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFPagoActionPerformed(evt);
            }
        });

        lFactura.setForeground(new java.awt.Color(0, 0, 100));
        lFactura.setText("Fecha Alta Cliente");
        lFactura.setName("lFactura"); // NOI18N

        lDiasPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lDiasPlazo.setText("Días");
        lDiasPlazo.setName("lDiasPlazo"); // NOI18N

        jTextDiasPlazo.setEnabled(false);
        jTextDiasPlazo.setName("jTextDiasPlazo"); // NOI18N

        jDateChooserAlta.setDateFormatString("dd-MM-yyyy");
        jDateChooserAlta.setName("jDateChooserAlta"); // NOI18N

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("*");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");
        jLabel11.setName("jLabel11"); // NOI18N

        lTarifa.setForeground(new java.awt.Color(0, 0, 100));
        lTarifa.setText("Tipo de Tarifa");
        lTarifa.setName("lTarifa"); // NOI18N

        jComboBoxTarifa.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxTarifa.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxTarifa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  1", "  2", "  3", "  4", "  5", "  6", "  7", "  8", "  9", " 10" }));
        jComboBoxTarifa.setName("jComboBoxTarifa"); // NOI18N

        lTipo.setForeground(new java.awt.Color(0, 0, 100));
        lTipo.setText("    Tipo");
        lTipo.setName("lTipo"); // NOI18N

        jComboBoxTipo.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxTipo.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empresa", "Concesionario", "Renting", "Compraventa", "Particular", "Proveedor", "Fabricante", "Otros" }));
        jComboBoxTipo.setName("jComboBoxTipo"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(211, 211, 211)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lPoblacionFiscal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPoblacionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lProvinciaFiscal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxProvinciaFiscal, 0, 158, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lDireccion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDireccionFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(lCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lPContacto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(lFax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(lWeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lComercial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxComercial, 0, 124, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lPlazo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lEstado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxPlazo, 0, 101, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDiasPlazo)
                        .addGap(24, 24, 24)
                        .addComponent(lFPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFPago, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipo, 0, 137, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lTarifa)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lNumCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserAlta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lPContacto)
                        .addGap(569, 569, 569))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNombreCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNombreCon, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTelefonoCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextTelefonoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lTelefonoCon1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTelefonoCon2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addComponent(lEmailCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEmailCon, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lCodPostal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPoblacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lProvincia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxProvincia, 0, 164, Short.MAX_VALUE))
                            .addComponent(jTextTelefono2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFax, jTextTelefono, jTextTelefono2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDNI)
                    .addComponent(jLabel2)
                    .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre)
                    .addComponent(jLabelO)
                    .addComponent(lNumero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion)
                    .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodPostal)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lPoblacion)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProvincia)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lTelefono)
                        .addComponent(jLabel5)
                        .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lEmail)
                        .addComponent(lFax)
                        .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lTelefono2)
                        .addComponent(jTextWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lWeb)
                        .addComponent(jTextTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lComercial)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPlazo)
                    .addComponent(jTextNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumCuenta)
                    .addComponent(lDiasPlazo)
                    .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFPago))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lEstado)
                        .addComponent(lFactura)
                        .addComponent(jLabel11)
                        .addComponent(jComboBoxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lTarifa)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lTipo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jDateChooserAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPContacto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion1)
                    .addComponent(lCodPostalFiscal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPoblacionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPoblacionFiscal)
                    .addComponent(jComboBoxProvinciaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProvinciaFiscal))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lPContacto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombreCon)
                    .addComponent(jLabel6)
                    .addComponent(jTextNombreCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDepartamento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelefonoCon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefonoCon1)
                    .addComponent(jTextTelefonoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefonoCon)
                    .addComponent(jLabel7)
                    .addComponent(jTextEmailCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEmailCon)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
 
            System.out.println("\nBoton Guardar de Añadir Clientes.");

            Cliente client = new Cliente();
            String fecha2="";
            String numCuenta="";
            String nombre = new String(jTextNombre.getText());
            String dni = new String(jTextDNI.getText());
            String direccion = new String(jTextDireccion.getText());
            String codPostal = new String(jTextCodPostal.getText());
            String poblacion = new String(jTextPoblacion.getText());
            String provincia = new String(jComboBoxProvincia.getSelectedItem().toString());
            String telefono = new String(jTextTelefono.getText());
            String telefono2 = new String(jTextTelefono2.getText());
            String fax = new String(jTextFax.getText());
            String email = new String(jTextEmail.getText());
            String web = new String(jTextWeb.getText());
            String plazo = new String(jComboBoxPlazo.getSelectedItem().toString());
            String diasPlazo = new String(jTextDiasPlazo.getText().toString());
            int dPlazo = 0;
            if (!diasPlazo.equals(""))
            {
                dPlazo = Integer.valueOf(diasPlazo);
            }
            String fPago = new String(Integer.valueOf(jComboBoxFPago.getSelectedIndex()+1).toString());
            String estado = new String(jComboBoxEstado.getSelectedItem().toString());
            String direccionFiscal = new String(jTextDireccionFiscal.getText());
            String poblacionFiscal = new String(jTextPoblacionFiscal.getText());
            String provinciaFiscal = new String(jComboBoxProvinciaFiscal.getSelectedItem().toString());
            String codPostalFiscal = new String(jTextCodPostalFiscal.getText());
            String tipoTarifa = new String(jComboBoxTarifa.getSelectedItem().toString());
            String tipoCliente = new String(jComboBoxTipo.getSelectedItem().toString());
            Calendar fechaCalendar = jDateChooserAlta.getCalendar();

            if (fechaCalendar!=null)
            {
                Date fecha = fechaCalendar.getTime();
                SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
                fecha2=formatoDeFecha.format(fecha);
            }
             String entidad = new String(jTextEntidad.getText());
            String sucursal = new String(jTextSucursal.getText());
            String digito = new String(jTextDigito.getText());
            if (!entidad.equals(""))
            {
                numCuenta = new String(entidad+"/"+sucursal+"/"+digito+"/"+jTextNumCuenta.getText());
            }
            //Esto hay que quitarlo o no dependiendo de la persona de contacto
            String nombreContacto = new String(jTextNombreCon.getText());
            String telefContacto = new String(jTextTelefonoCon.getText());
            String telefContacto2 = new String(jTextTelefonoCon2.getText());
            String emailContacto = new String(jTextEmailCon.getText());
            String fDepartamento = new String(Integer.valueOf(jComboBoxDepartamento.getSelectedIndex()+1).toString());
            String departamento = new String(jComboBoxDepartamento.getSelectedItem().toString());
            String  co_id = new String(Integer.valueOf(jComboBoxComercial.getSelectedIndex()+1).toString());
            String password = "";
            try {
                password = Utilidades.MD5(dni);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(CSAnyadirCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(CSAnyadirCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("password: "+password);

            //CAMPOS OBLIGATORIOS
            if (!Utilidades.campoObligatorio(nombre,"Nombre").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(nombre,"Nombre"));
            }
            else if (!Utilidades.campoObligatorio(dni,"DNI").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(dni,"DNI"));
            }
            else if (!Utilidades.campoObligatorio(direccion,"Dirección").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(direccion,"direccion"));
            }
            else if (!Utilidades.campoObligatorio(codPostal,"Código Postal").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(codPostal,"Código Postal"));
            }
            else if (!Utilidades.campoObligatorio(poblacion,"Población").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(poblacion,"Población"));
            }
            else if (!Utilidades.campoObligatorioCombo(provincia,"Provincia").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorioCombo(provincia,"Provincia"));
            }
            else if (!Utilidades.campoObligatorio(telefono,"telefono").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(telefono,"telefono"));
            }
            else if (!Utilidades.campoObligatorio(nombreContacto,"Nombre Contacto").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(nombreContacto,"Nombre Contacto"));
            }
            else if (!Utilidades.campoObligatorioCombo(departamento,"Departamento").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorioCombo(departamento,"Departamento"));
            }
            else if (!Utilidades.campoObligatorio(telefContacto,"Telefono Contacto").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(telefContacto,"Telefono Contacto"));
            }
            else if (!Utilidades.campoObligatorio(emailContacto,"Email Contacto").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(emailContacto,"Email Contacto"));
            }

            //VALIDACION DE FORMATOS
            else if(!Utilidades.formatoCodPostal(codPostal).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCodPostal(codPostal));
            }
            else if(!Utilidades.formatoTelefono9(telefono).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoTelefono9(telefono));
            }
            else if(!Utilidades.formatoTelefono9(telefono2).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoTelefono9(telefono2));
            }
             else if(!Utilidades.formatoFax(fax).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoFax(fax));
            }
             else if(!Utilidades.formatoCorreo(email).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCorreo(email));
            }
            else if(!Utilidades.formatoCodPostal(codPostalFiscal).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCodPostal(codPostalFiscal));
            }
             else if(!Utilidades.formatoTelefono9(telefContacto).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoTelefono9(telefContacto));
            }
             else if(!Utilidades.formatoTelefono9(telefContacto2).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoTelefono9(telefContacto2));
            }
             else if(!Utilidades.formatoCorreo(emailContacto).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCorreo(emailContacto));
            }
            else if(!Utilidades.formatoNumerico(diasPlazo).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoNumerico(diasPlazo));
            }
            else if(client.isCliente(nombre, dni))
            {
                    jButtonGuardar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Ya existe un Cliente con ese nombre y NIF</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonGuardar.setEnabled(true);
            }
            else
            {
                String query = "INSERT INTO cl_clientes (cl_nombre, cl_DNI_CIF, cl_direccion, " +
                                                         "cl_cod_postal, cl_poblacion, cl_provincia, " +
                                                         "cl_telefono, cl_telefono2, cl_fax, cl_email, " +
                                                         "cl_web, cl_plazo, cl_dias_plazo, fp_id, cl_estado, co_id,cl_direccion_fiscal,cl_cod_postal_fiscal, " +
                                                         "cl_poblacion_fiscal,cl_provincia_fiscal,cl_fecha,cl_num_cuenta, cl_tipo_tarifa, cl_password, cl_tipo) VALUES (";
                query = query + "'"+nombre+"','"+dni+"','"+direccion+"','"+codPostal+"','"+poblacion+"','"+provincia+"','"+telefono+"'";
                query = query + " ,'"+telefono2+"','"+fax+"','"+email+"','"+web+"','"+plazo+"','"+dPlazo+"','"+fPago+"','"+estado+"'";
                query = query + " ,'"+co_id+"','"+direccionFiscal+"','"+codPostalFiscal+"','"+poblacionFiscal+"','"+provinciaFiscal+"','"+fecha2+"'";
                query = query + " ,'"+numCuenta+"','"+tipoTarifa+"','"+password+"','"+tipoCliente+"')";
                      
                System.out.println(query);
                //datos = new DbConnection();
                boolean rs = CSDesktop.datos.manipuladorDatos(query);
                System.out.println(rs);
                if(rs)
                {
                    jButtonGuardar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonGuardar.setEnabled(true);
                }
                else
                {
                    query = "select distinct last_insert_id() from cl_clientes";
                    String cl_id="";
                    ResultSet rs2 = CSDesktop.datos.select(query);
                    try {
                           if (rs2.first())
                            {
                                cl_id=Integer.valueOf(rs2.getInt("last_insert_id()")).toString();
                                //System.out.println(rs2.getInt("last_insert_id()"));
                                String queryCon = "INSERT INTO cc_contactos_cliente (cc_nombre, cc_telefono, cc_telefono2, cc_email, cl_id, dp_id) "+
                                                  "VALUES ('"+nombreContacto+"','"+telefContacto+"','"+telefContacto2+"','"+emailContacto+"', "+
                                                  "'"+cl_id+"', '"+fDepartamento+"')";
                                System.out.println(queryCon);
                                boolean rsCon = CSDesktop.datos.manipuladorDatos(queryCon);
                                System.out.println(queryCon);
                                if(rsCon)
                                {
                                    jButtonGuardar.setEnabled(false);
                                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                                    JOptionPane.showMessageDialog(null,errorFields);
                                    jButtonGuardar.setEnabled(true);
                                }
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(CSAnyadirCliente.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    //Controlar posible error
                    //Creamos las tarifas de la plantilla
                    boolean tarifas = false;
                try {
                    tarifas = crearTarifasCliente(cl_id);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(CSAnyadirCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                    //Creamos los servicios de la plantilla
                    boolean servicios = false;
                try {
                    servicios = crearServiciosCliente(cl_id);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(CSAnyadirCliente.class.getName()).log(Level.SEVERE, null, ex);
                }

                    if(tarifas && servicios)
                    {
                        jButtonGuardar.setEnabled(false);
                        JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>Los datos se han guardado correctamente.</FONT></HTML>");
                        JOptionPane.showMessageDialog(null,mensaje);
                        jButtonGuardar.setEnabled(true);
                        CSDesktop.NuevoCliente.dispose();
                        CSDesktop.menuNuevoCliente.setEnabled(true);
                    }
                }
            }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       CSDesktop.NuevoCliente.dispose();
       CSDesktop.menuNuevoCliente.setEnabled(true);                          
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreFocusLost
       String nombreM = jTextNombre.getText().toUpperCase();
       jTextNombre.setText(nombreM);

    }//GEN-LAST:event_jTextNombreFocusLost

    private void jTextDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDNIFocusLost
       String DNIM = jTextDNI.getText().toUpperCase();
       jTextDNI.setText(DNIM);
    }//GEN-LAST:event_jTextDNIFocusLost

    private void jTextDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionFocusLost
       String DireccionM = jTextDireccion.getText().toUpperCase();
       jTextDireccion.setText(DireccionM);
    }//GEN-LAST:event_jTextDireccionFocusLost

    private void jTextPoblacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionFocusLost
        String PoblacionM = jTextPoblacion.getText().toUpperCase();
       jTextPoblacion.setText(PoblacionM);
    }//GEN-LAST:event_jTextPoblacionFocusLost

    private void jTextEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailFocusLost
       String MailM = jTextEmail.getText().toUpperCase();
       jTextEmail.setText(MailM);
    }//GEN-LAST:event_jTextEmailFocusLost

    private void jTextWebFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextWebFocusLost
       String WebM = jTextWeb.getText().toUpperCase();
       jTextWeb.setText(WebM);
    }//GEN-LAST:event_jTextWebFocusLost

    private void jTextNombreConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreConFocusLost
       String NombreConM = jTextNombreCon.getText().toUpperCase();
       jTextNombreCon.setText(NombreConM);
    }//GEN-LAST:event_jTextNombreConFocusLost

    private void jTextEmailConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailConFocusLost
       String MailConM = jTextEmailCon.getText().toUpperCase();
       jTextEmailCon.setText(MailConM);
    }//GEN-LAST:event_jTextEmailConFocusLost

    private void jTextDireccionFiscalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionFiscalFocusLost
        String DireccionFiscalConM = jTextDireccionFiscal.getText().toUpperCase();
        jTextDireccionFiscal.setText(DireccionFiscalConM);
    }//GEN-LAST:event_jTextDireccionFiscalFocusLost

    private void jTextPoblacionFiscalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionFiscalFocusLost
        String PoblacionFiscalConM = jTextPoblacionFiscal.getText().toUpperCase();
        jTextPoblacionFiscal.setText(PoblacionFiscalConM);
    }//GEN-LAST:event_jTextPoblacionFiscalFocusLost

    private void jComboBoxPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlazoActionPerformed
        if (jComboBoxPlazo.getSelectedItem().equals("Especial")) {
            jTextDiasPlazo.setEnabled(true);
        } else {
            jTextDiasPlazo.setEnabled(false);
        }
}//GEN-LAST:event_jComboBoxPlazoActionPerformed

    private void jComboBoxFPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFPagoActionPerformed
        if (jComboBoxFPago.getSelectedItem().equals("Recibo Domiciliado")) {
            jTextDigito.setEnabled(true);
            jTextEntidad.setEnabled(true);
            jTextSucursal.setEnabled(true);
            jTextNumCuenta.setEnabled(true);
        } else {
            jTextDigito.setEnabled(false);
            jTextEntidad.setEnabled(false);
            jTextSucursal.setEnabled(false);
            jTextNumCuenta.setEnabled(false);
        }
}//GEN-LAST:event_jComboBoxFPagoActionPerformed

    public Dimension getPreferredSize()
    {
      return new Dimension( 826,620 );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox jComboBoxComercial;
    private javax.swing.JComboBox jComboBoxDepartamento;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxFPago;
    private javax.swing.JComboBox jComboBoxPlazo;
    private javax.swing.JComboBox jComboBoxProvincia;
    private javax.swing.JComboBox jComboBoxProvinciaFiscal;
    private javax.swing.JComboBox jComboBoxTarifa;
    private javax.swing.JComboBox jComboBoxTipo;
    private com.toedter.calendar.JDateChooser jDateChooserAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelO;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextCodPostal;
    private javax.swing.JTextField jTextCodPostalFiscal;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextDiasPlazo;
    private javax.swing.JTextField jTextDigito;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextDireccionFiscal;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEmailCon;
    private javax.swing.JTextField jTextEntidad;
    private javax.swing.JTextField jTextFax;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNombreCon;
    private javax.swing.JTextField jTextNumCuenta;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPoblacion;
    private javax.swing.JTextField jTextPoblacionFiscal;
    private javax.swing.JTextField jTextSucursal;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jTextTelefono2;
    private javax.swing.JTextField jTextTelefonoCon;
    private javax.swing.JTextField jTextTelefonoCon2;
    private javax.swing.JTextField jTextWeb;
    private javax.swing.JLabel lCodPostal;
    private javax.swing.JLabel lCodPostalFiscal;
    private javax.swing.JLabel lComercial;
    private javax.swing.JLabel lDNI;
    private javax.swing.JLabel lDepartamento;
    private javax.swing.JLabel lDiasPlazo;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lDireccion1;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEmailCon;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lFPago;
    private javax.swing.JLabel lFactura;
    private javax.swing.JLabel lFax;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNombreCon;
    private javax.swing.JLabel lNumCuenta;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lPContacto;
    private javax.swing.JLabel lPContacto1;
    private javax.swing.JLabel lPlazo;
    private javax.swing.JLabel lPoblacion;
    private javax.swing.JLabel lPoblacionFiscal;
    private javax.swing.JLabel lProvincia;
    private javax.swing.JLabel lProvinciaFiscal;
    private javax.swing.JLabel lTarifa;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel lTelefono2;
    private javax.swing.JLabel lTelefonoCon;
    private javax.swing.JLabel lTelefonoCon1;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lWeb;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param accion
     */
    public void ValidarFormatos(String accion)
    {
         jButtonGuardar.setEnabled(false);
         JLabel errorFields = new JLabel(accion);
         JOptionPane.showMessageDialog(null,errorFields);
         jButtonGuardar.setEnabled(true);
    }

    /**
     *
     * @throws SQLException
     */
     private void getFPagoClientes() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT fp_id, fp_tipo FROM fp_forma_pago");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("fp_tipo");      
                jComboBoxFPago.addItem(valor);               
                jComboBoxFPago.setSelectedIndex(0);

                //jCombPago.addItem(rs.getString("fp_tipo"))
                j++;
        }
        
     }

/**
 * Función para sacar los departamentos de la bd
 * @throws SQLException
 */
    private void getDepartamentoContacto() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT dp_id, dp_nombre FROM dp_departamentos");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("dp_nombre");

                jComboBoxDepartamento.addItem(valor);
                jComboBoxDepartamento.setSelectedIndex(0);

                //jCombPago.addItem(rs.getString("fp_tipo"))
                j++;
        }
     }

    /**
     * Función para sacar todos los comerciales de la base da datos
     * @throws SQLException
     */
    private void getComercial() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT co_id, co_nombre FROM co_comerciales");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("co_nombre");

            jComboBoxComercial.addItem(valor);
            jComboBoxComercial.setSelectedIndex(0);

            j++;
        }
     }

    /**
     * Insertar las tarifas del cliente desde el cliente de plantilla
     * @param cliente
     */
    public boolean crearTarifasCliente(String idCliente) throws UnknownHostException
    {
        boolean tarifaOK=true;
        String query = "SELECT * FROM tc_tarifas_clientes WHERE cl_id = 1";

        ResultSet rs = CSDesktop.datos.select(query);
        try {
            DbConnection da = new DbConnection();

            while (rs.next())
            {       
                   boolean rsTc = true;
                   int tc_id = 1;

                    String servicio = rs.getString("tc_servicio");
                    String servicioOrigen = rs.getString("tc_servicio_origen");
                    String servicioDestino = rs.getString("tc_servicio_destino");
                    String soporte = rs.getString("tc_soporte");
                    Date fechaDesde = rs.getDate("tc_fecha_desde");
                    Date fechaHasta = rs.getDate("tc_fecha_hasta");
                    String incremento = rs.getString("tc_incremento");
                    String tarifa = rs.getString("tc_tarifa");

                   String queryTc = "INSERT INTO tc_tarifas_clientes (tc_servicio, tc_servicio_origen, tc_servicio_destino, " +
                   "tc_soporte, tc_fecha_desde, tc_fecha_hasta, tc_incremento, tc_tarifa, cl_id) " +
                   "VALUES ('" + servicio + "', '" + servicioOrigen + "', '" + servicioDestino + "', " +
                   "'" + soporte + "', '" + fechaDesde + "','" + fechaHasta + "', " +
                   ""+ incremento + ", "+ tarifa + ", "+ idCliente+")";
                                                   

                   System.out.println(queryTc);
                   rsTc = da.manipuladorDatos(queryTc);
                   if(rsTc)
                   {
                        borrarTarifasYCliente(idCliente);
                        jButtonGuardar.setEnabled(false);
                        JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar las tarifas en la base de datos</FONT></HTML>");
                        JOptionPane.showMessageDialog(null,errorFields);
                        jButtonGuardar.setEnabled(true);
                        tarifaOK=false;
                   }

            }
            da.cerrarConexion();
            rs.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CSEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
           
        }
        return tarifaOK;
    }

    /**
     * Insertar los servicios especiales del cliente desde el cliente de plantilla
     * @param cliente
     */
    public boolean crearServiciosCliente(String idCliente) throws UnknownHostException
    {
        boolean servicioOK=true;
        String query = "SELECT * FROM sc_servicios_clientes WHERE cl_id = 1";

        ResultSet rs = CSDesktop.datos.select(query);
        try
        {
            DbConnection se = new DbConnection();
            while (rs.next())
            {
                boolean rsSe = true;

                String todoterreno = rs.getString("sc_todoterreno");
                String industrial = rs.getString("sc_industrial");
                String furgonetas = rs.getString("sc_furgonetas");
                String furgones = rs.getString("sc_furgones");
                String lavadoEx = rs.getString("sc_lavado_exterior");
                String lavadoExIn = rs.getString("sc_lavado_exin");
                String lavadoInt = rs.getString("sc_lavado_integral");
                String lavadoIE4 = rs.getString("sc_int_ext_cuatro");
                String lavadoIntegral4 = rs.getString("sc_integral_cuatro");
                String lavadoIEIndustrial = rs.getString("sc_int_ext_industrial");
                String lavadoIntInd = rs.getString("sc_integral_industrial");
                String desrotularPegaFacil = rs.getString("sc_desrotular_peg_facil");
                String desrotularPegaNormal = rs.getString("sc_desrotular_peg_normal");
                String desrotularPegaDificil = rs.getString("sc_desrotular_peg_dificil");
                String rotularPegaFacil = rs.getString("sc_rotular_peg_facil");
                String rotularPegaNormal = rs.getString("sc_rotular_peg_normal");
                String rotularPegaDificil = rs.getString("sc_rotular_peg_dificil");
                String lavadoDomEx = rs.getString("sc_ldom_exterior");
                String lavadoDomExIn = rs.getString("sc_ldom_exin");
                String lavadoDomInt = rs.getString("sc_ldom_integral");
                String lavadoDomIE4 = rs.getString("sc_ldom_int_ext_cuatro");
                String lavadoDomIntegral4 = rs.getString("sc_ldom_integral_cuatro");
                String lavadoDomIEIndustrial = rs.getString("sc_ldom_int_ext_industrial");
                String lavadoDomIntInd = rs.getString("sc_ldom_integral_industrial");
                String itv = rs.getString("sc_itv");
                String preItv = rs.getString("sc_pre_itv");
                String itvPreItv = rs.getString("sc_itv_pre_itv");
                String idaVuelta = rs.getString("sc_ida_vuelta");
                String entradaCampa = rs.getString("sc_entrada_campa");
                String campa = rs.getString("sc_campa");
                String peritacion = rs.getString("sc_peritacion");
                String mOMecanicaChapa = rs.getString("sc_mo_mecanica_chapa");
                String chequeo = rs.getString("sc_chequeo");
                String repostaje = rs.getString("sc_repostaje");
                String suplemento = rs.getString("sc_suplemento");
                String urgente = rs.getString("sc_urgente");
                String fecha_desde = rs.getString("sc_fecha_desde");
                String fecha_hasta = rs.getString("sc_fecha_hasta");


                String querySe  = "INSERT INTO sc_servicios_clientes (sc_todoterreno, sc_industrial, sc_furgonetas, sc_furgones, " +
                "sc_lavado_exterior, sc_lavado_exin, sc_lavado_integral, sc_int_ext_cuatro, sc_integral_cuatro, " +
                "sc_int_ext_industrial, sc_integral_industrial, sc_desrotular_peg_facil, sc_desrotular_peg_normal, " +
                "sc_desrotular_peg_dificil, sc_rotular_peg_facil, sc_rotular_peg_normal, sc_rotular_peg_dificil, " +
                "sc_ldom_exterior, sc_ldom_exin, sc_ldom_integral, sc_ldom_int_ext_cuatro, sc_ldom_integral_cuatro, " +
                "sc_ldom_int_ext_industrial, sc_ldom_integral_industrial, sc_itv, sc_pre_itv, sc_itv_pre_itv, " +
                "sc_ida_vuelta, sc_entrada_campa, sc_campa, sc_peritacion, sc_mo_mecanica_chapa, sc_chequeo, " +
                "sc_repostaje, sc_suplemento, sc_urgente, cl_id, sc_fecha_desde, sc_fecha_hasta) " +
                "VALUES ('"+todoterreno+"', '"+industrial+"', '"+furgonetas+"', '"+furgones+"', '"+lavadoEx+"', " +
                "'"+lavadoExIn+"', '"+lavadoInt+"', '"+lavadoIE4+"', '"+lavadoIntegral4+"', '"+lavadoIEIndustrial+"', " +
                "'"+lavadoIntInd+"', '"+desrotularPegaFacil+"', '"+desrotularPegaNormal+"', '"+desrotularPegaDificil+"', " +
                "'"+rotularPegaFacil+"', '"+rotularPegaNormal+"', '"+rotularPegaDificil+"', '"+lavadoDomEx+"', " +
                "'"+lavadoDomExIn+"', '"+lavadoDomInt+"', '"+lavadoDomIE4+"', '"+lavadoDomIntegral4+"', '"+lavadoDomIEIndustrial+"', " +
                "'"+lavadoDomIntInd+"', '"+itv+"', '"+preItv+"', '"+itvPreItv+"', '"+idaVuelta+"', '"+entradaCampa+"', " +
                "'"+campa+"', '"+peritacion+"', '"+mOMecanicaChapa+"', '"+chequeo+"', '"+repostaje+"', '"+suplemento+"', " +
                "'"+urgente+"', '"+ idCliente+"', '"+ fecha_desde+"', '"+ fecha_hasta+"') ";

               System.out.println(querySe);
               rsSe = se.manipuladorDatos(querySe);
               if(rsSe)
               {
                     borrarTarifasYCliente(idCliente);
                    jButtonGuardar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar los servicios especiales en la base de datos</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonGuardar.setEnabled(true);
                    servicioOK=false;
               }

            }
            se.cerrarConexion();
            rs.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CSEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        return servicioOK;
    }

    /**
     * Función para la limitación de los campos
     */
    private void limitacionesCampos()
    {
        LimitadorDeDocumento limitadorNombre= new LimitadorDeDocumento(50);
        jTextNombre.setDocument(limitadorNombre);
        LimitadorDeDocumento limitadorDNI= new LimitadorDeDocumento(10);
        jTextDNI.setDocument(limitadorDNI);
        LimitadorDeDocumento limitadorDireccion = new LimitadorDeDocumento(255);
        jTextDireccion.setDocument(limitadorDireccion);
        LimitadorDeDocumento limitador5= new LimitadorDeDocumento(5);
        jTextCodPostal.setDocument(limitador5);
        LimitadorDeDocumento limitadorPoblacion= new LimitadorDeDocumento(80);
        jTextPoblacion.setDocument(limitadorPoblacion);
        LimitadorDeDocumento limitadorTelefono= new LimitadorDeDocumento(13);
        jTextTelefono.setDocument(limitadorTelefono);
        LimitadorDeDocumento limitadorTelefono2= new LimitadorDeDocumento(13);
        jTextTelefono2.setDocument(limitadorTelefono2);
        LimitadorDeDocumento limitadorFax= new LimitadorDeDocumento(13);
        jTextFax.setDocument(limitadorFax);
        LimitadorDeDocumento limitadorEmail= new LimitadorDeDocumento(50);
        jTextEmail.setDocument(limitadorEmail);
        LimitadorDeDocumento limitadorWeb= new LimitadorDeDocumento(50);
        jTextWeb.setDocument(limitadorWeb);

        //Parte Domicilio Fiscal
        LimitadorDeDocumento limitadorDireccionFiscal= new LimitadorDeDocumento(255);
        jTextDireccionFiscal.setDocument(limitadorDireccionFiscal);
        LimitadorDeDocumento limitadorCodPostalFiscal= new LimitadorDeDocumento(5);
        jTextCodPostalFiscal.setDocument(limitadorCodPostalFiscal);
        LimitadorDeDocumento limitadorPoblacionFiscal= new LimitadorDeDocumento(80);
        jTextPoblacionFiscal.setDocument(limitadorPoblacionFiscal);
        LimitadorDeDocumento limitadorEntidad= new LimitadorDeDocumento(4);
        jTextEntidad.setDocument(limitadorEntidad);
        LimitadorDeDocumento limitadorSucursal= new LimitadorDeDocumento(4);
        jTextSucursal.setDocument(limitadorSucursal);
        LimitadorDeDocumento limitadorDigito= new LimitadorDeDocumento(2);
        jTextDigito.setDocument(limitadorDigito);
        LimitadorDeDocumento limitadorNumC= new LimitadorDeDocumento(10);
        jTextNumCuenta.setDocument(limitadorNumC);

        //Parte de Persona de Contacto
        LimitadorDeDocumento limitadorNombreContacto= new LimitadorDeDocumento(50);
        jTextNombreCon.setDocument(limitadorNombreContacto);
        LimitadorDeDocumento limitadorTelefonoContacto= new LimitadorDeDocumento(13);
        jTextTelefonoCon.setDocument(limitadorTelefonoContacto);
        LimitadorDeDocumento limitadorTelefonoContacto2= new LimitadorDeDocumento(13);
        jTextTelefonoCon2.setDocument(limitadorTelefonoContacto2);
        LimitadorDeDocumento limitadorEmailContacto= new LimitadorDeDocumento(50);
        jTextEmailCon.setDocument(limitadorEmailContacto);
    }

public void borrarTarifasYCliente(String idCliente)
    {
        String query = "DELETE FROM tc_tarifas_clientes WHERE cl_id = " + idCliente;
        boolean resDel = CSDesktop.datos.manipuladorDatos(query);

        query="DELETE FROM cl_clientes WHERE cl_id = " + idCliente;
        resDel = CSDesktop.datos.manipuladorDatos(query);

        query="DELETE FROM sc_servicios_clientes WHERE cl_id = " + idCliente;
        resDel = CSDesktop.datos.manipuladorDatos(query);

    }
}