/*
 * ABAnyadirCliente.java
 *
 * Created on 03-oct-2009, 0:25:10
 */

package neg;

import java.sql.Date;
import utils.Utilidades;
import utils.LimitadorDeDocumento;
import data.DbConnection;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author lito
 */
public class CSAnyadirCliente extends javax.swing.JPanel
{
    DbConnection datos;
    /** Creates new form ABAnyadirCliente */
    public CSAnyadirCliente() throws SQLException
    {
        
        datos = new DbConnection();
        initComponents();
        getFPagoClientes();
        getDepartamentoContacto();
        getComercial();
        limitacionesCampos();


        KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonGuardar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };

        for (int k = 0; k < this.getComponents().length; k ++)
        {
            if (this.getComponents()[k] != jComboBoxDepartamento &&
                this.getComponents()[k] != jComboBoxEstado &&
                this.getComponents()[k] != jComboBoxFPago &&
                this.getComponents()[k] != jComboBoxPlazo &&
                this.getComponents()[k] != jComboBoxComercial &&
                this.getComponents()[k] != jComboBoxProvincia)
            {
                this.getComponents()[k].addKeyListener(l);                
            }
        }

        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        lDNI = new javax.swing.JLabel();
        jTextDNI = new javax.swing.JTextField();
        lDireccion = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        lCodPostal = new javax.swing.JLabel();
        jTextCodPostal = new javax.swing.JTextField();
        lPoblacion = new javax.swing.JLabel();
        jTextPoblacion = new javax.swing.JTextField();
        lProvincia = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        lFax = new javax.swing.JLabel();
        jTextFax = new javax.swing.JTextField();
        jComboBoxFPago = new javax.swing.JComboBox();
        lFPago = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        lNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        lPContacto = new javax.swing.JLabel();
        lNombreCon = new javax.swing.JLabel();
        lDepartamento = new javax.swing.JLabel();
        jComboBoxDepartamento = new javax.swing.JComboBox();
        lTelefonoCon = new javax.swing.JLabel();
        jTextTelefonoCon = new javax.swing.JTextField();
        lEmailCon = new javax.swing.JLabel();
        lTelefono2 = new javax.swing.JLabel();
        jTextTelefono2 = new javax.swing.JTextField();
        lPlazo = new javax.swing.JLabel();
        jComboBoxPlazo = new javax.swing.JComboBox();
        lTelefonoCon1 = new javax.swing.JLabel();
        jTextTelefonoCon2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxProvincia = new javax.swing.JComboBox();
        jTextEmail = new javax.swing.JTextField();
        jTextEmailCon = new javax.swing.JTextField();
        lWeb = new javax.swing.JLabel();
        jTextWeb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextNombreCon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lComercial = new javax.swing.JLabel();
        jComboBoxComercial = new javax.swing.JComboBox();
        jTextDiasPlazo = new javax.swing.JTextField();
        lDiasPlazo = new javax.swing.JLabel();

        lNombre.setForeground(new java.awt.Color(0, 0, 100));
        lNombre.setText("Nombre");
        lNombre.setName("lNombre"); // NOI18N

        jTextNombre.setName("jTextNombre"); // NOI18N
        jTextNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreFocusLost(evt);
            }
        });

        lDNI.setForeground(new java.awt.Color(0, 0, 100));
        lDNI.setText("DNI/CIF");
        lDNI.setName("lDNI"); // NOI18N

        jTextDNI.setName("jTextDNI"); // NOI18N
        jTextDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDNIFocusLost(evt);
            }
        });

        lDireccion.setForeground(new java.awt.Color(0, 0, 100));
        lDireccion.setText("    Dirección");
        lDireccion.setName("lDireccion"); // NOI18N

        jTextDireccion.setName("jTextDireccion"); // NOI18N
        jTextDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionFocusLost(evt);
            }
        });

        lCodPostal.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostal.setLabelFor(jTextCodPostal);
        lCodPostal.setText("Código Postal");
        lCodPostal.setName("lCodPostal"); // NOI18N

        jTextCodPostal.setName("jTextCodPostal"); // NOI18N

        lPoblacion.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacion.setText("Población");
        lPoblacion.setName("lPoblacion"); // NOI18N

        jTextPoblacion.setName("jTextPoblacion"); // NOI18N
        jTextPoblacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionFocusLost(evt);
            }
        });

        lProvincia.setForeground(new java.awt.Color(0, 0, 100));
        lProvincia.setText("Provincia");
        lProvincia.setName("lProvincia"); // NOI18N

        lTelefono.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono.setText("Teléfono");
        lTelefono.setName("lTelefono"); // NOI18N

        jTextTelefono.setMinimumSize(new java.awt.Dimension(9, 9));
        jTextTelefono.setName("jTextTelefono"); // NOI18N

        lFax.setForeground(new java.awt.Color(0, 0, 100));
        lFax.setText("Fax");
        lFax.setName("lFax"); // NOI18N

        jTextFax.setName("jTextFax"); // NOI18N

        jComboBoxFPago.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxFPago.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxFPago.setName("jComboBoxFPago"); // NOI18N

        lFPago.setForeground(new java.awt.Color(0, 0, 100));
        lFPago.setText("Forma de Pago");
        lFPago.setName("lFPago"); // NOI18N

        lEmail.setForeground(new java.awt.Color(0, 0, 100));
        lEmail.setText("Email");
        lEmail.setName("lEmail"); // NOI18N

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setName("jButtonGuardar"); // NOI18N
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        lNumero.setForeground(new java.awt.Color(0, 0, 100));
        lNumero.setText("    Nº. Cliente  CL/");
        lNumero.setName("lNumero"); // NOI18N

        jTextNumero.setEditable(false);
        jTextNumero.setEnabled(false);
        jTextNumero.setName("jTextNumero"); // NOI18N

        lPContacto.setFont(new java.awt.Font("Tahoma", 1, 11));
        lPContacto.setForeground(new java.awt.Color(170, 16, 4));
        lPContacto.setText("PERSONA DE CONTACTO");
        lPContacto.setName("lPContacto"); // NOI18N

        lNombreCon.setForeground(new java.awt.Color(0, 0, 100));
        lNombreCon.setText("Nombre");
        lNombreCon.setName("lNombreCon"); // NOI18N

        lDepartamento.setForeground(new java.awt.Color(0, 0, 100));
        lDepartamento.setText("Departamento");
        lDepartamento.setName("lDepartamento"); // NOI18N

        jComboBoxDepartamento.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxDepartamento.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxDepartamento.setName("jComboBoxDepartamento"); // NOI18N

        lTelefonoCon.setForeground(new java.awt.Color(0, 0, 100));
        lTelefonoCon.setText("Teléfono");
        lTelefonoCon.setName("lTelefonoCon"); // NOI18N

        jTextTelefonoCon.setName("jTextTelefonoCon"); // NOI18N

        lEmailCon.setForeground(new java.awt.Color(0, 0, 100));
        lEmailCon.setText("Email");
        lEmailCon.setName("lEmailCon"); // NOI18N

        lTelefono2.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono2.setText("    Teléfono 2");
        lTelefono2.setName("lTelefono2"); // NOI18N

        jTextTelefono2.setMinimumSize(new java.awt.Dimension(9, 9));
        jTextTelefono2.setName("jTextTelefono2"); // NOI18N

        lPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lPlazo.setText("Plazo");
        lPlazo.setName("lPlazo"); // NOI18N

        jComboBoxPlazo.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxPlazo.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxPlazo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30 días FF", "15 días FF", "45 días FF", "60 días FF", "Especial" }));
        jComboBoxPlazo.setName("jComboBoxPlazo"); // NOI18N
        jComboBoxPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlazoActionPerformed(evt);
            }
        });

        lTelefonoCon1.setForeground(new java.awt.Color(0, 0, 100));
        lTelefonoCon1.setText("Teléfono 2");
        lTelefonoCon1.setName("lTelefonoCon1"); // NOI18N

        jTextTelefonoCon2.setName("jTextTelefonoCon2"); // NOI18N

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("* Campos obligatorios");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabelO.setForeground(new java.awt.Color(204, 0, 0));
        jLabelO.setText("*");
        jLabelO.setName("jLabelO"); // NOI18N

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("*");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("*");
        jLabel3.setName("jLabel3"); // NOI18N

        jComboBoxProvincia.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvincia.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERíA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CORDOBA", "CORUÑA, A", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPUZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MALAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PALMAS, LAS", "PONTEVEDRA", "RIOJA, LA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvincia.setName("jComboBoxProvincia"); // NOI18N

        jTextEmail.setName("jTextEmail"); // NOI18N
        jTextEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailFocusLost(evt);
            }
        });

        jTextEmailCon.setName("jTextEmailCon"); // NOI18N
        jTextEmailCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailConFocusLost(evt);
            }
        });

        lWeb.setForeground(new java.awt.Color(0, 0, 100));
        lWeb.setText("Web");
        lWeb.setName("lWeb"); // NOI18N

        jTextWeb.setName("jTextWeb"); // NOI18N
        jTextWeb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextWebFocusLost(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("*");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("*");
        jLabel8.setName("jLabel8"); // NOI18N

        lEstado.setForeground(new java.awt.Color(0, 0, 100));
        lEstado.setText("    Estado");
        lEstado.setName("lEstado"); // NOI18N

        jComboBoxEstado.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxEstado.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        jComboBoxEstado.setName("jComboBoxEstado"); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator1.setName("jSeparator1"); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator2.setName("jSeparator2"); // NOI18N

        jTextNombreCon.setName("jTextNombreCon"); // NOI18N
        jTextNombreCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreConFocusLost(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("*");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("*");
        jLabel10.setName("jLabel10"); // NOI18N

        lComercial.setForeground(new java.awt.Color(0, 0, 100));
        lComercial.setText("Comercial");
        lComercial.setName("lComercial"); // NOI18N

        jComboBoxComercial.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxComercial.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxComercial.setName("jComboBoxComercial"); // NOI18N

        jTextDiasPlazo.setEnabled(false);
        jTextDiasPlazo.setName("jTextDiasPlazo"); // NOI18N

        lDiasPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lDiasPlazo.setText("Días");
        lDiasPlazo.setName("lDiasPlazo"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTelefonoCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextTelefonoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lTelefonoCon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextTelefonoCon2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(lEmailCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextEmailCon, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTelefono2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextTelefono2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lFax)
                                    .addComponent(lWeb)))))
                    .addComponent(lEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lEmail)
                        .addGap(18, 18, 18)
                        .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lPlazo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDiasPlazo)
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lComercial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lFPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxFPago, 0, 138, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lPoblacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextPoblacion, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lProvincia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addComponent(jComboBoxProvincia, 0, 135, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lCodPostal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lPContacto)
                .addContainerGap(579, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNombreCon)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNombreCon, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDepartamento, 0, 155, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumero)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDNI)
                    .addComponent(jLabel2)
                    .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre)
                    .addComponent(jLabelO))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion)
                    .addComponent(jLabel3)
                    .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lCodPostal))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lPoblacion)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProvincia)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTelefono)
                            .addComponent(jLabel5)
                            .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lFax))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTelefono2)
                            .addComponent(jTextTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lEmail))
                            .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lWeb)
                            .addComponent(jComboBoxComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lComercial))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEstado)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFPago)
                    .addComponent(lPlazo)
                    .addComponent(jComboBoxPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDiasPlazo)
                    .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPContacto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombreCon)
                    .addComponent(jLabel6)
                    .addComponent(jTextNombreCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDepartamento))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelefonoCon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefonoCon1)
                    .addComponent(jTextTelefonoCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefonoCon)
                    .addComponent(jLabel7)
                    .addComponent(jTextEmailCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEmailCon)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardar)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonCancelar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxPlazo, jTextDiasPlazo});

    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
 
            System.out.println("\nBoton Guardar de Añadir Clientes.");
            
            String nombre = new String(jTextNombre.getText());
            String dni = new String(jTextDNI.getText());
            String direccion = new String(jTextDireccion.getText());
            String codPostal = new String(jTextCodPostal.getText());
            String poblacion = new String(jTextPoblacion.getText());
            String provincia = new String(jComboBoxProvincia.getSelectedItem().toString());
            String telefono = new String(jTextTelefono.getText());
            String telefono2 = new String(jTextTelefono2.getText());
            String fax = new String(jTextFax.getText());
            String email = new String(jTextEmail.getText());
            String web = new String(jTextWeb.getText());
            String plazo = new String(jComboBoxPlazo.getSelectedItem().toString());
            String diasPlazo = new String(jTextDiasPlazo.getText().toString());
            String fPago = new String(Integer.valueOf(jComboBoxFPago.getSelectedIndex()+1).toString());
            String estado = new String(jComboBoxEstado.getSelectedItem().toString());
            //Esto hay que quitarlo o no dependiendo de la persona de contacto
            String nombreContacto = new String(jTextNombreCon.getText());
            String telefContacto = new String(jTextTelefonoCon.getText());
            String telefContacto2 = new String(jTextTelefonoCon2.getText());
            String emailContacto = new String(jTextEmailCon.getText());
            String fDepartamento = new String(Integer.valueOf(jComboBoxDepartamento.getSelectedIndex()+1).toString());
            String departamento = new String(jComboBoxDepartamento.getSelectedItem().toString());
            String  co_id = new String(Integer.valueOf(jComboBoxComercial.getSelectedIndex()+1).toString());
            String comercial = new String(jComboBoxComercial.getSelectedItem().toString());

            //CAMPOS OBLIGATORIOS
            if (!Utilidades.campoObligatorio(nombre,"Nombre").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(nombre,"Nombre"));
            }
            else if (!Utilidades.campoObligatorio(dni,"DNI").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(dni,"DNI"));
            }
            else if (!Utilidades.campoObligatorio(direccion,"Dirección").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(direccion,"direccion"));
            }
            else if (!Utilidades.campoObligatorio(codPostal,"Código Postal").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(codPostal,"Código Postal"));
            }
            else if (!Utilidades.campoObligatorio(poblacion,"Población").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(poblacion,"Población"));
            }
            else if (!Utilidades.campoObligatorioCombo(provincia,"Provincia").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorioCombo(provincia,"Provincia"));
            }
            else if (!Utilidades.campoObligatorio(telefono,"telefono").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(telefono,"telefono"));
            }
            else if (!Utilidades.campoObligatorio(nombreContacto,"Nombre Contacto").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(nombreContacto,"Nombre Contacto"));
            }
            else if (!Utilidades.campoObligatorioCombo(departamento,"Departamento").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorioCombo(departamento,"Departamento"));
            }
            else if (!Utilidades.campoObligatorio(telefContacto,"Telefono Contacto").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(telefContacto,"Telefono Contacto"));
            }
            else if (!Utilidades.campoObligatorio(emailContacto,"Email Contacto").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(emailContacto,"Email Contacto"));
            }

            //VALIDACION DE FORMATOS
            else if(!Utilidades.formatoCodPostal(codPostal).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCodPostal(codPostal));
            }
            else if(!Utilidades.formatoTelefono9(telefono).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoTelefono9(telefono));
            }
            else if(!Utilidades.formatoTelefono9(telefono2).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoTelefono9(telefono2));
            }
             else if(!Utilidades.formatoFax(fax).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoFax(fax));
            }
             else if(!Utilidades.formatoCorreo(email).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCorreo(email));
            }
             else if(!Utilidades.formatoTelefono9(telefContacto).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoTelefono9(telefContacto));
            }
             else if(!Utilidades.formatoTelefono9(telefContacto2).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoTelefono9(telefContacto2));
            }
             else if(!Utilidades.formatoCorreo(emailContacto).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCorreo(emailContacto));
            }
            else if(!Utilidades.formatoNumerico(diasPlazo).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoNumerico(diasPlazo));
            }
            else
            {
                String query = "INSERT INTO cl_clientes (cl_nombre, cl_DNI_CIF, cl_direccion, " +
                                                         "cl_cod_postal, cl_poblacion, cl_provincia, " +
                                                         "cl_telefono, cl_telefono2, cl_fax, cl_email, " +
                                                         "cl_web, cl_plazo, cl_dias_plazo, fp_id, cl_estado, co_id) VALUES (";
                query = query + "'"+nombre+"','"+dni+"','"+direccion+"','"+codPostal+"','"+poblacion+"','"+provincia+"','"+telefono+"'";
                query = query + " ,'"+telefono2+"','"+fax+"','"+email+"','"+web+"','"+plazo+"','"+diasPlazo+"','"+fPago+"','"+estado+"','"+co_id+"')";
                      
                System.out.println(query);
                //datos = new DbConnection();
                boolean rs = datos.manipuladorDatos(query);
                System.out.println(rs);
                if(rs)
                {
                    jButtonGuardar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonGuardar.setEnabled(true);
                }
                else
                {
                    query = "select distinct last_insert_id() from cl_clientes";
                    String cl_id="";
                    ResultSet rs2 = datos.select(query);
                    try {
                           if (rs2.first())
                            {
                                cl_id=Integer.valueOf(rs2.getInt("last_insert_id()")).toString();
                                //System.out.println(rs2.getInt("last_insert_id()"));
                                String queryCon = "INSERT INTO cc_contactos_cliente (cc_nombre, cc_telefono, cc_telefono2, cc_email, cl_id, dp_id) "+
                                                  "VALUES ('"+nombreContacto+"','"+telefContacto+"','"+telefContacto2+"','"+emailContacto+"', "+
                                                  "'"+cl_id+"', '"+fDepartamento+"')";
                                System.out.println(queryCon);
                                boolean rsCon = datos.manipuladorDatos(queryCon);
                                System.out.println(queryCon);
                                if(rsCon)
                                {
                                    jButtonGuardar.setEnabled(false);
                                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                                    JOptionPane.showMessageDialog(null,errorFields);
                                    jButtonGuardar.setEnabled(true);
                                }
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(CSAnyadirCliente.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    //Controlar posible error
                    //Creamos las tarifas de la plantilla
                    crearTarifasCliente(cl_id);
                    //Creamos los servicios de la plantilla
                    crearServiciosCliente(cl_id);

                    jButtonGuardar.setEnabled(false);
                    JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>Los datos se han guardado correctamente.</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,mensaje);
                    jButtonGuardar.setEnabled(true);
                    CSDesktop.NuevoCliente.dispose();
                    
                    
                    /**int confirmado = JOptionPane.showConfirmDialog(this,"Los datos se han guardado correctamente.¿Quiere crear una tarifa para este cliente?");

                    if (JOptionPane.OK_OPTION == confirmado)
                    {
                        CSDesktop.TarifaCliente = new JInternalFrame("Tarifa Cliente", true, true, true, true );
                        // adjuntar panel al panel de contenido del marco interno
                        CSAnyadirTarifaCliente panel = new CSAnyadirTarifaCliente();
                        CSDesktop.TarifaCliente.getContentPane().add( panel,BorderLayout.CENTER);
                        // establecer tama�o de marco interno en el tama�o de su contenido
                        CSDesktop.TarifaCliente.pack();
                        // adjuntar marco interno al escritorio y mostrarlo
                        CSDesktop.elEscritorio.add( CSDesktop.TarifaCliente );

                        Dimension pantalla = CSDesktop.elEscritorio.getSize();
                        Dimension ventana = CSDesktop.TarifaCliente.getSize();
                        CSDesktop.TarifaCliente.setLocation(
                        (pantalla.width - ventana.width) / 2,
                        (pantalla.height - ventana.height) / 2);
                        CSDesktop.TarifaCliente.setVisible(true);
                    }

                        CSDesktop.NuevoCliente.dispose();
                     */
                }
            }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
            {
               CSDesktop.NuevoCliente.dispose();
              
            }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreFocusLost
       String nombreM = jTextNombre.getText().toUpperCase();
       jTextNombre.setText(nombreM);

    }//GEN-LAST:event_jTextNombreFocusLost

    private void jTextDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDNIFocusLost
       String DNIM = jTextDNI.getText().toUpperCase();
       jTextDNI.setText(DNIM);
    }//GEN-LAST:event_jTextDNIFocusLost

    private void jTextDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionFocusLost
       String DireccionM = jTextDireccion.getText().toUpperCase();
       jTextDireccion.setText(DireccionM);
    }//GEN-LAST:event_jTextDireccionFocusLost

    private void jTextPoblacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionFocusLost
        String PoblacionM = jTextPoblacion.getText().toUpperCase();
       jTextPoblacion.setText(PoblacionM);
    }//GEN-LAST:event_jTextPoblacionFocusLost

    private void jTextEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailFocusLost
       String MailM = jTextEmail.getText().toUpperCase();
       jTextEmail.setText(MailM);
    }//GEN-LAST:event_jTextEmailFocusLost

    private void jTextWebFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextWebFocusLost
       String WebM = jTextWeb.getText().toUpperCase();
       jTextWeb.setText(WebM);
    }//GEN-LAST:event_jTextWebFocusLost

    private void jTextNombreConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreConFocusLost
       String NombreConM = jTextNombreCon.getText().toUpperCase();
       jTextNombreCon.setText(NombreConM);
    }//GEN-LAST:event_jTextNombreConFocusLost

    private void jTextEmailConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailConFocusLost
       String MailConM = jTextEmailCon.getText().toUpperCase();
       jTextEmailCon.setText(MailConM);
    }//GEN-LAST:event_jTextEmailConFocusLost

    private void jComboBoxPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlazoActionPerformed
        if (jComboBoxPlazo.getSelectedItem().equals("Especial"))
        {
            jTextDiasPlazo.setEnabled(true);
        }
        else
        {
            jTextDiasPlazo.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxPlazoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox jComboBoxComercial;
    private javax.swing.JComboBox jComboBoxDepartamento;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxFPago;
    private javax.swing.JComboBox jComboBoxPlazo;
    private javax.swing.JComboBox jComboBoxProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelO;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextCodPostal;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextDiasPlazo;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEmailCon;
    private javax.swing.JTextField jTextFax;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNombreCon;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPoblacion;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jTextTelefono2;
    private javax.swing.JTextField jTextTelefonoCon;
    private javax.swing.JTextField jTextTelefonoCon2;
    private javax.swing.JTextField jTextWeb;
    private javax.swing.JLabel lCodPostal;
    private javax.swing.JLabel lComercial;
    private javax.swing.JLabel lDNI;
    private javax.swing.JLabel lDepartamento;
    private javax.swing.JLabel lDiasPlazo;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEmailCon;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lFPago;
    private javax.swing.JLabel lFax;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNombreCon;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lPContacto;
    private javax.swing.JLabel lPlazo;
    private javax.swing.JLabel lPoblacion;
    private javax.swing.JLabel lProvincia;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel lTelefono2;
    private javax.swing.JLabel lTelefonoCon;
    private javax.swing.JLabel lTelefonoCon1;
    private javax.swing.JLabel lWeb;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param accion
     */
    public void ValidarFormatos(String accion)
    {
         jButtonGuardar.setEnabled(false);
         JLabel errorFields = new JLabel(accion);
         JOptionPane.showMessageDialog(null,errorFields);
         jButtonGuardar.setEnabled(true);
    }

    /**
     *
     * @throws SQLException
     */
     private void getFPagoClientes() throws SQLException
    {
        ResultSet rs = datos.select("SELECT fp_id, fp_tipo FROM fp_forma_pago");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("fp_tipo");
           
                jComboBoxFPago.addItem(valor);               
                jComboBoxFPago.setSelectedIndex(0);

                //jCombPago.addItem(rs.getString("fp_tipo"))
                j++;
        }
        
     }

/**
 * Función para sacar los departamentos de la bd
 * @throws SQLException
 */
    private void getDepartamentoContacto() throws SQLException
    {
        ResultSet rs = datos.select("SELECT dp_id, dp_nombre FROM dp_departamentos");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("dp_nombre");

                jComboBoxDepartamento.addItem(valor);
                jComboBoxDepartamento.setSelectedIndex(0);

                //jCombPago.addItem(rs.getString("fp_tipo"))
                j++;
        }
     }

    /**
     * Función para sacar todos los comerciales de la base da datos
     * @throws SQLException
     */
    private void getComercial() throws SQLException
    {
        ResultSet rs = datos.select("SELECT co_id, co_nombre FROM co_comerciales");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("co_nombre");

            jComboBoxComercial.addItem(valor);
            jComboBoxComercial.setSelectedIndex(0);

            j++;
        }
     }

    /**
     * Insertar las tarifas del cliente desde el cliente de plantilla
     * @param cliente
     */
    public void crearTarifasCliente(String idCliente)
    {
        String query = "SELECT * FROM tc_tarifas_clientes WHERE cl_id = 1";

        ResultSet rs = datos.select(query);
        try {

            while (rs.next())
            {
                   DbConnection da = new DbConnection();
                   boolean rsTc = true;
                   int tc_id = 1;

                    String fueraMad = rs.getString("tc_fuera_mad");
                    String servicio = rs.getString("tc_servicio");
                    String servicioDestino = rs.getString("tp_servicio_destino");
                    String soporte = rs.getString("tc_soporte");
                    Date fechaDesde = rs.getDate("tc_fecha_desde");
                    Date fechaHasta = rs.getDate("tc_fecha_hasta");
                    String incremento = rs.getString("tc_incremento");
                    String tarifa = rs.getString("tc_tarifa");

                   String queryTc  = "INSERT INTO tc_tarifas_clientes (tc_servicio, tc_servicio_destino tc_soporte, tc_fecha_desde, "+
                                     "tc_fecha_hasta, tc_fuera_mad, tc_incremento, tc_tarifa, cl_id) " +
                                     "VALUES ('" + servicio + "' ,'" + soporte + "' ,'" + fechaDesde + "', '" + fechaHasta + "'," +
                                     "'" + fueraMad + "', " + incremento + ", " + tarifa + ", " + idCliente+") ";
                                                   

                   System.out.println(queryTc);
                   rsTc = da.manipuladorDatos(queryTc);
                   if(rsTc)
                   {
                        jButtonGuardar.setEnabled(false);
                        JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar las tarifas en la base de datos</FONT></HTML>");
                        JOptionPane.showMessageDialog(null,errorFields);
                        jButtonGuardar.setEnabled(true);
                   }
                   da.cerrarConexion();
            }
            rs.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CSEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * Insertar los servicios especiales del cliente desde el cliente de plantilla
     * @param cliente
     */
    public void crearServiciosCliente(String idCliente)
    {
        String query = "SELECT * FROM sc_servicios_clientes WHERE cl_id = 1";

        ResultSet rs = datos.select(query);
        try {

            while (rs.next())
            {
                   DbConnection se = new DbConnection();
                   boolean rsSe = true;

                    String industrial = rs.getString("sc_industrial");
                    String todoterreno = rs.getString("sc_todoterreno");
                    String furgones = rs.getString("sc_furgones");
                    String itv = rs.getString("sc_itv");
                    String preItv = rs.getString("sc_pre_itv");
                    String chequeo = rs.getString("sc_chequeo");
                    String reacondicionamiento = rs.getString("sc_reacondicionamiento");
                    String campa = rs.getString("sc_campa");
                    String entradaCampa = rs.getString("sc_entrada_campa");
                    String lavado = rs.getString("sc_lavado");
                    String lavadoExIn = rs.getString("sc_lavado_exin");
                    String lavadoExtra = rs.getString("sc_lavado_extra");
                    String lavadoCom = rs.getString("sc_completo");
                    String lavadoHig = rs.getString("sc_higienizado");
                    String idaVuelta = rs.getString("sp_ida_vuelta");

                    String querySe  = "INSERT INTO sc_servicios_clientes (sc_industrial, sc_todoterreno, sc_furgones, " +
                                      "sc_itv, sc_pre_itv, sc_chequeo, sc_reacondicionamiento, sc_campa, sc_entrada_campa, " +
                                      "sc_lavado, sc_lavado_exin, sc_lavado_extra, sc_completo, sc_higienizado, cl_id) " +
                                      "VALUES ('" + industrial + "' ,'" + todoterreno + "' ,'" + furgones + "'," +
                                      "'" + itv + "', '"+ preItv + "', '" + chequeo + "', '" + reacondicionamiento+"', " +
                                      "'" + campa + "', "+ entradaCampa+", '" + lavado + "', '" + lavadoExIn + "', '" + lavadoExtra + "', " +
                                      "'" + lavadoCom + "', '" + lavadoHig + ", '" + idaVuelta + ", '" + idCliente + "') ";

                   System.out.println(querySe);
                   rsSe = se.manipuladorDatos(querySe);
                   if(rsSe)
                   {
                        jButtonGuardar.setEnabled(false);
                        JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar los servicios especiales en la base de datos</FONT></HTML>");
                        JOptionPane.showMessageDialog(null,errorFields);
                        jButtonGuardar.setEnabled(true);
                   }
                   se.cerrarConexion();
            }
            rs.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CSEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * Función para la limitación de los campos
     */
    private void limitacionesCampos()
    {
        LimitadorDeDocumento limitadorNombre= new LimitadorDeDocumento(50);
        jTextNombre.setDocument(limitadorNombre);
        LimitadorDeDocumento limitadorDNI= new LimitadorDeDocumento(10);
        jTextDNI.setDocument(limitadorDNI);
        LimitadorDeDocumento limitadorDireccion = new LimitadorDeDocumento(255);
        jTextDireccion.setDocument(limitadorDireccion);
        LimitadorDeDocumento limitador5= new LimitadorDeDocumento(5);
        jTextCodPostal.setDocument(limitador5);
        LimitadorDeDocumento limitadorPoblacion= new LimitadorDeDocumento(80);
        jTextPoblacion.setDocument(limitadorPoblacion);
        LimitadorDeDocumento limitadorTelefono= new LimitadorDeDocumento(13);
        jTextTelefono.setDocument(limitadorTelefono);
        LimitadorDeDocumento limitadorTelefono2= new LimitadorDeDocumento(13);
        jTextTelefono2.setDocument(limitadorTelefono2);
        LimitadorDeDocumento limitadorFax= new LimitadorDeDocumento(13);
        jTextFax.setDocument(limitadorFax);
        LimitadorDeDocumento limitadorEmail= new LimitadorDeDocumento(50);
        jTextEmail.setDocument(limitadorEmail);
        LimitadorDeDocumento limitadorWeb= new LimitadorDeDocumento(50);
        jTextWeb.setDocument(limitadorWeb);

        //Parte de Persona de Contacto
        LimitadorDeDocumento limitadorNombreContacto= new LimitadorDeDocumento(50);
        jTextNombreCon.setDocument(limitadorNombreContacto);
        LimitadorDeDocumento limitadorTelefonoContacto= new LimitadorDeDocumento(13);
        jTextTelefonoCon.setDocument(limitadorTelefonoContacto);
        LimitadorDeDocumento limitadorTelefonoContacto2= new LimitadorDeDocumento(13);
        jTextTelefonoCon2.setDocument(limitadorTelefonoContacto2);
        LimitadorDeDocumento limitadorEmailContacto= new LimitadorDeDocumento(50);
        jTextEmailCon.setDocument(limitadorEmailContacto);
    }

}