/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABBuscarPedido.java
 *
 * Created on 07-oct-2009, 17:50:47
 */

package neg;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.LimitadorDeDocumento;
import data.Cliente;
import data.Proveedor;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author depr73
 */
public class CSBuscarPedidoNew extends javax.swing.JPanel
{
    int clienteID=0;
    int proveedorID=0;

    /** Creates new form ABBuscarPedido */
    public CSBuscarPedidoNew()
    {
        CSDesktop.menuBuscarPedidoNew.setEnabled(false);
        initComponents();
        try {
            getComercial();
        } catch (SQLException ex) {
            Logger.getLogger(CSBuscarPedidoNew.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            getFactorCorrecion();
        } catch (SQLException ex) {
            Logger.getLogger(CSBuscarPedidoNew.class.getName()).log(Level.SEVERE, null, ex);
        }
        limitacionesCampos();

         KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonBuscar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };

        for (int k = 0; k < this.getComponents().length; k ++)
        {
            if (this.getComponents()[k] != jComboBoxProvinciaOrigen &&
                this.getComponents()[k] != jComboBoxProvinciaDestino &&
                this.getComponents()[k] != jComboFactor &&
                this.getComponents()[k] != jComboBoxEstado &&
                this.getComponents()[k] != jComboBoxComercial)
            {
                this.getComponents()[k].addKeyListener(l);
            }
        }
        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxSoporte = new javax.swing.JComboBox();
        lDestino1 = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        lMatricula = new javax.swing.JLabel();
        lPoblacionDestino = new javax.swing.JLabel();
        lVehiculo = new javax.swing.JLabel();
        jToggleButtonCliente = new javax.swing.JToggleButton();
        lCliente = new javax.swing.JLabel();
        lOrigen1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jToggleButtonProveedor = new javax.swing.JToggleButton();
        lProvinciaOrigen = new javax.swing.JLabel();
        jTextProveedor = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        jTextPoblacionOrigen = new javax.swing.JTextField();
        lEstado3 = new javax.swing.JLabel();
        jComboBoxProvinciaDestino = new javax.swing.JComboBox();
        lFechaIni = new javax.swing.JLabel();
        jTextPoblacionDestino = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox();
        jComboBoxProvinciaOrigen = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        jTextNumero = new javax.swing.JTextField();
        jTextCliente = new javax.swing.JTextField();
        lPoblacionOrigen = new javax.swing.JLabel();
        lProvinciaDestino = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        lFechaFin = new javax.swing.JLabel();
        jDateFechaFin = new com.toedter.calendar.JDateChooser();
        lServicioFMad2 = new javax.swing.JLabel();
        lServicio = new javax.swing.JLabel();
        lComercial = new javax.swing.JLabel();
        jComboBoxComercial = new javax.swing.JComboBox();
        jButtonBuscarSProv = new javax.swing.JButton();
        jCheckBoxUnidos = new javax.swing.JCheckBox();
        jComboOrden = new javax.swing.JComboBox();
        jLabelOrder = new javax.swing.JLabel();
        lEstado4 = new javax.swing.JLabel();
        jCBoxEstadoVehiculo = new javax.swing.JComboBox();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jComboFactor = new javax.swing.JComboBox();
        jComboBoxIncidencias = new javax.swing.JComboBox();
        lincidencias = new javax.swing.JLabel();
        lMatricula1 = new javax.swing.JLabel();
        lProveedor = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1050, 374));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setName("jButtonBuscar"); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxSoporte.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxSoporte.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxSoporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Portavehículos", "Camión completo", "Conductor", "Grúa Unitaria", "Custodia", "Vehículo Pesado", "Transporte Marítimo" }));
        jComboBoxSoporte.setName("jComboBoxSoporte"); // NOI18N

        lDestino1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lDestino1.setForeground(new java.awt.Color(170, 16, 4));
        lDestino1.setText("DATOS DEL DESTINO");
        lDestino1.setName("lDestino1"); // NOI18N

        jTextMatricula.setName("jTextMatricula"); // NOI18N
        jTextMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMatriculaActionPerformed(evt);
            }
        });
        jTextMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextMatriculaFocusLost(evt);
            }
        });

        lMatricula.setForeground(new java.awt.Color(0, 0, 100));
        lMatricula.setText("Matrícula / bastidor");
        lMatricula.setName("lMatricula"); // NOI18N

        lPoblacionDestino.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionDestino.setText("Población");
        lPoblacionDestino.setName("lPoblacionDestino"); // NOI18N

        lVehiculo.setForeground(new java.awt.Color(0, 0, 100));
        lVehiculo.setText("Soporte");
        lVehiculo.setName("lVehiculo"); // NOI18N

        jToggleButtonCliente.setText("Buscar Cliente");
        jToggleButtonCliente.setName("jToggleButtonCliente"); // NOI18N
        jToggleButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonClienteActionPerformed(evt);
            }
        });

        lCliente.setForeground(new java.awt.Color(0, 0, 100));
        lCliente.setText("Cliente");
        lCliente.setName("lCliente"); // NOI18N

        lOrigen1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lOrigen1.setForeground(new java.awt.Color(170, 16, 4));
        lOrigen1.setText("DATOS DEL ORIGEN");
        lOrigen1.setName("lOrigen1"); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator1.setName("jSeparator1"); // NOI18N

        jToggleButtonProveedor.setText("Buscar Proveedor");
        jToggleButtonProveedor.setName("jToggleButtonProveedor"); // NOI18N
        jToggleButtonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonProveedorActionPerformed(evt);
            }
        });

        lProvinciaOrigen.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaOrigen.setText("Provincia");
        lProvinciaOrigen.setName("lProvinciaOrigen"); // NOI18N

        jTextProveedor.setEditable(false);
        jTextProveedor.setName("jTextProveedor"); // NOI18N

        lNumero.setForeground(new java.awt.Color(0, 0, 100));
        lNumero.setText("Núm. de pedido PE/");
        lNumero.setName("lNumero"); // NOI18N

        jTextPoblacionOrigen.setName("jTextPoblacionOrigen"); // NOI18N
        jTextPoblacionOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionOrigenFocusLost(evt);
            }
        });

        lEstado3.setForeground(new java.awt.Color(0, 0, 100));
        lEstado3.setText("Estado");
        lEstado3.setName("lEstado3"); // NOI18N

        jComboBoxProvinciaDestino.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaDestino.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaDestino.setName("jComboBoxProvinciaDestino"); // NOI18N

        lFechaIni.setForeground(new java.awt.Color(0, 0, 100));
        lFechaIni.setText("Fecha ini");
        lFechaIni.setName("lFechaIni"); // NOI18N

        jTextPoblacionDestino.setName("jTextPoblacionDestino"); // NOI18N
        jTextPoblacionDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionDestinoFocusLost(evt);
            }
        });

        jComboBoxEstado.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxEstado.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Activo", "En Proceso", "Entregado", "Facturado", "Facturado y Validado", "Anulado", "Fallido" }));
        jComboBoxEstado.setName("jComboBoxEstado"); // NOI18N

        jComboBoxProvinciaOrigen.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaOrigen.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaOrigen.setName("jComboBoxProvinciaOrigen"); // NOI18N

        jSeparator5.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator5.setName("jSeparator5"); // NOI18N

        jTextNumero.setName("jTextNumero"); // NOI18N

        jTextCliente.setEditable(false);
        jTextCliente.setName("jTextCliente"); // NOI18N

        lPoblacionOrigen.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionOrigen.setText("Población");
        lPoblacionOrigen.setName("lPoblacionOrigen"); // NOI18N

        lProvinciaDestino.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaDestino.setText("Provincia");
        lProvinciaDestino.setName("lProvinciaDestino"); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator3.setName("jSeparator3"); // NOI18N

        jDateFecha.setDateFormatString("dd-MM-yyyy"); // NOI18N
        jDateFecha.setName("jDateFecha"); // NOI18N

        lFechaFin.setForeground(new java.awt.Color(0, 0, 100));
        lFechaFin.setText("Fecha fin");
        lFechaFin.setName("lFechaFin"); // NOI18N

        jDateFechaFin.setDateFormatString("dd-MM-yyyy"); // NOI18N
        jDateFechaFin.setName("jDateFechaFin"); // NOI18N

        lServicioFMad2.setForeground(new java.awt.Color(0, 0, 100));
        lServicioFMad2.setText("Tipo");
        lServicioFMad2.setName("lServicioFMad2"); // NOI18N

        lServicio.setFont(new java.awt.Font("Tahoma", 1, 11));
        lServicio.setForeground(new java.awt.Color(170, 16, 4));
        lServicio.setText("PROVEEDOR");
        lServicio.setName("lServicio"); // NOI18N

        lComercial.setForeground(new java.awt.Color(0, 0, 100));
        lComercial.setText("Comercial");
        lComercial.setName("lComercial"); // NOI18N

        jComboBoxComercial.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxComercial.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxComercial.setName("jComboBoxComercial"); // NOI18N

        jButtonBuscarSProv.setText("Pedidos sin Proveedor");
        jButtonBuscarSProv.setName("jButtonBuscarSProv"); // NOI18N
        jButtonBuscarSProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarSProvActionPerformed(evt);
            }
        });

        jCheckBoxUnidos.setForeground(new java.awt.Color(0, 0, 100));
        jCheckBoxUnidos.setText("Pedidos Unidos");
        jCheckBoxUnidos.setName("jCheckBoxUnidos"); // NOI18N
        jCheckBoxUnidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUnidosActionPerformed(evt);
            }
        });

        jComboOrden.setBackground(new java.awt.Color(255, 255, 102));
        jComboOrden.setForeground(new java.awt.Color(0, 0, 100));
        jComboOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Número de Pedido", "Fecha Pedido", "Tarifa Cliente", "Tarifa Proveedor", "Fecha Origen", "Fecha Entrega" }));
        jComboOrden.setName("jComboOrden"); // NOI18N
        jComboOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboOrdenActionPerformed(evt);
            }
        });

        jLabelOrder.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelOrder.setForeground(new java.awt.Color(170, 16, 4));
        jLabelOrder.setText("Orden");
        jLabelOrder.setName("jLabelOrder"); // NOI18N

        lEstado4.setForeground(new java.awt.Color(0, 0, 100));
        lEstado4.setText("Estado Ve");
        lEstado4.setName("lEstado4"); // NOI18N

        jCBoxEstadoVehiculo.setBackground(new java.awt.Color(228, 229, 255));
        jCBoxEstadoVehiculo.setForeground(new java.awt.Color(0, 0, 100));
        jCBoxEstadoVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Funciona", "Avería Mecánica", "Accidente Leve", "Accidente Grave" }));
        jCBoxEstadoVehiculo.setName("jCBoxEstadoVehiculo"); // NOI18N
        jCBoxEstadoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxEstadoVehiculoActionPerformed(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator6.setName("jSeparator6"); // NOI18N

        jSeparator9.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator9.setForeground(new java.awt.Color(0, 102, 51));
        jSeparator9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 53), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jSeparator9.setName("jSeparator9"); // NOI18N
        jSeparator9.setOpaque(true);
        jSeparator9.setPreferredSize(new java.awt.Dimension(5, 5));

        jComboFactor.setBackground(new java.awt.Color(228, 229, 255));
        jComboFactor.setForeground(new java.awt.Color(0, 0, 100));
        jComboFactor.setName("jComboFactor"); // NOI18N
        jComboFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboFactorActionPerformed(evt);
            }
        });

        jComboBoxIncidencias.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxIncidencias.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxIncidencias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Todas", "I", "IM", "IRD", "RFL", "RP", "RC" }));
        jComboBoxIncidencias.setName("jComboBoxIncidencias"); // NOI18N
        jComboBoxIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIncidenciasActionPerformed(evt);
            }
        });

        lincidencias.setForeground(new java.awt.Color(0, 0, 100));
        lincidencias.setText("Incidencias");
        lincidencias.setName("lincidencias"); // NOI18N

        lMatricula1.setForeground(new java.awt.Color(0, 0, 100));
        lMatricula1.setText("Matrícula/Bast");
        lMatricula1.setName("lMatricula1"); // NOI18N

        lProveedor.setForeground(new java.awt.Color(0, 0, 100));
        lProveedor.setText("Proveedor");
        lProveedor.setName("lProveedor"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(568, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(902, Short.MAX_VALUE)
                .addComponent(jToggleButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(902, Short.MAX_VALUE)
                .addComponent(jToggleButtonProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lPoblacionOrigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPoblacionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(779, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lOrigen1)
                .addGap(415, 415, 415)
                .addComponent(lDestino1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(266, 266, 266))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jButtonBuscarSProv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(478, 478, 478)
                .addComponent(jCheckBoxUnidos)
                .addContainerGap(475, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(825, Short.MAX_VALUE)
                .addComponent(lComercial)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addComponent(lServicio))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lFechaIni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lEstado3)
                                            .addComponent(lincidencias)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelOrder))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lServicioFMad2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxIncidencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboFactor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(lVehiculo)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lProvinciaOrigen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPoblacionDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(lMatricula1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 600, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextPoblacionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEstado4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxComercial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBoxEstadoVehiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProvinciaDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jToggleButtonCliente, jToggleButtonProveedor});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxEstado, jComboBoxIncidencias, jComboFactor, jComboOrden});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCBoxEstadoVehiculo, jComboBoxComercial, jComboBoxProvinciaDestino});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextMatricula, jTextPoblacionDestino, jTextPoblacionOrigen});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonCliente)
                    .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCliente))
                .addGap(14, 14, 14)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lOrigen1)
                    .addComponent(lDestino1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextPoblacionOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lPoblacionDestino)
                        .addComponent(jComboBoxProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lProvinciaOrigen))
                    .addComponent(jTextPoblacionDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lServicioFMad2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lMatricula1)
                        .addComponent(jComboBoxSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lVehiculo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lEstado4))
                    .addComponent(jCBoxEstadoVehiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lincidencias)
                    .addComponent(jToggleButtonProveedor)
                    .addComponent(jTextProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEstado3)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxUnidos)
                    .addComponent(lComercial))
                .addGap(26, 26, 26)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBuscar)
                        .addComponent(jButtonBuscarSProv)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelOrder)
                        .addComponent(jComboOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lMatricula)
                .addGap(199, 199, 199))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lPoblacionOrigen)
                .addGap(261, 261, 261))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jComboBoxProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lProvinciaDestino)
                .addGap(261, 261, 261))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCBoxEstadoVehiculo, jComboBoxSoporte, jComboFactor, jTextMatricula});

    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        System.out.println("\njButtonGuardar_actionPerformed(ActionEvent e) called.");

        String fechaI="";
        String fechaF="";

        int numeroN=0;
        String numero = new String(jTextNumero.getText());
        if(!numero.equals("")){
           numeroN=Integer.valueOf(numero);
        }

        Calendar fechaCalendar = jDateFecha.getCalendar();
        if (fechaCalendar!=null)
        {
            Date fecha = fechaCalendar.getTime();
            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
            fechaI=formatoDeFecha.format(fecha);
        }

        fechaCalendar = jDateFechaFin.getCalendar();
        if (fechaCalendar!=null)
        {
            Date fecha = fechaCalendar.getTime();
            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
            fechaF=formatoDeFecha.format(fecha);
        }
        String cliente=new String(jTextCliente.getText());
        String poblacionOrigen=new String(jTextPoblacionOrigen.getText());
        String provinciaOrigen=new String(jComboBoxProvinciaOrigen.getSelectedItem().toString());
        String poblacionDestino=new String(jTextPoblacionDestino.getText());
        String provinciaDestino=new String(jComboBoxProvinciaDestino.getSelectedItem().toString());
        int factor = new Integer(jComboFactor.getSelectedIndex());
        String soporte=new String(jComboBoxSoporte.getSelectedItem().toString());
        String matricula=new String(jTextMatricula.getText());
        String proveedor=new String(jTextProveedor.getText());
        String estado=new String(jComboBoxEstado.getSelectedItem().toString());
        String estado_ve=new String(jCBoxEstadoVehiculo.getSelectedItem().toString());
        int comercial = (jComboBoxComercial.getSelectedIndex()+1);
        boolean peUnidos = new Boolean(jCheckBoxUnidos.isSelected());
        String incidencia = new String(jComboBoxIncidencias.getSelectedItem().toString());
        incidencia = (incidencia.equals("Selecciona")) ? "" : incidencia;

        String query="SELECT DISTINCT(p.pe_num), p.pe_fecha, cl.cl_nombre, p.pe_provincia_origen, p.pe_poblacion_origen, p.pe_provincia_destino, " +
                "p.pe_poblacion_destino, p.pe_servicio, p.pe_kms, fc.fc_nombre, p.pe_ve_estado, p.pe_ve_matricula, p.pe_ve_marca, p.pe_ve_modelo, " +
                "p.pe_dias_campa, pr.pr_nombre_fiscal, p.pe_ta_es_cliente, p.pe_ta_es_proveedor, p.pe_suplemento, p.pe_fecha_origen, p.pe_fecha_destino, " +
                "p.pe_fecha_real_destino, p.pe_estado, p.pe_incidencia, p.pe_in_f_mas, p.pe_in_f_menos, p.pe_incidencia, p.pe_descripcion, p.pe_observaciones_carset, " +
                "p.pe_ob_general, p.pe_num_fa_cl, p.pe_num_fa_pr, cl.co_id, pc.cl_id, p.pe_num_unido, destino_unido, fecha_destino, real_destino, estado_unido, " +
                "po_destino, sv.sv_dias, p.pe_fin_unido, ta_pr_unido, f_menos_un "+
                " FROM (pe_pedidos p, pc_pedidos_clientes pc, pp_pedidos_proveedores pp, fc_factores_correccion fc)" +
                " LEFT JOIN sv_servicios sv on sv.cl_id = pc.cl_id " +
                " LEFT JOIN (SELECT pe_num_unido AS num_unido, pe_provincia_destino AS destino_unido, pe_fecha_destino AS fecha_destino, pe_poblacion_destino AS po_destino, " +
                " pe_fecha_real_destino as real_destino, pe_estado as estado_unido FROM pe_pedidos WHERE pe_fin_unido = 1 ORDER BY pe_num DESC)" +
                " pe_unido ON p.pe_num = pe_unido.num_unido " +
                "LEFT JOIN (SELECT pe_num_unido AS ta_unido, SUM(pe_ta_es_proveedor) as ta_pr_unido, SUM(pe_in_f_menos) AS f_menos_un " +
                "FROM pe_pedidos GROUP BY pe_num_unido) " +
                "tarifas_unido ON p.pe_num = tarifas_unido.ta_unido " +
                " INNER JOIN cl_clientes cl INNER JOIN pr_proveedores pr " +
                " WHERE pc.cl_id = cl.cl_id AND pp.pr_id = pr.pr_id  AND p.pe_num = pc.pe_num " +
                " AND p.pe_num = pp.pe_num AND p.fc_id = fc.fc_id";

        if (numero.equals("") && cliente.equals("") && proveedor.equals("") && (fechaI.equals("") && fechaF.equals("") && matricula.equals("")))
        {
            jButtonBuscar.setEnabled(false);
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Debe seleccionar el número de pedido, un Cliente, un Proveedor, período de fecha o matrícula</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields);
            jButtonBuscar.setEnabled(true);
        }
        else
        {
            try {
                if (!cliente.equals("") && !proveedor.equals("")) {
                    Cliente cliente2 = new Cliente();
                    clienteID = cliente2.getClienteID(cliente);
                    Proveedor proveedor2 = new Proveedor();
                    proveedorID = proveedor2.getProveedorID(proveedor);
                    query = query + " AND pc.cl_id = " + clienteID + " AND pp.pr_id = " + proveedorID;
                } else if (!cliente.equals("")) {
                    Cliente cliente2 = new Cliente();
                    clienteID = cliente2.getClienteID(cliente);
                    query = query + " AND pc.cl_id = " + clienteID;
                } else if (!proveedor.equals("")) {
                    Proveedor proveedor2 = new Proveedor();
                    proveedorID = proveedor2.getProveedorID(proveedor);
                    query = query + " AND pp.pr_id = " + proveedorID;
                }
                if ((!fechaI.equals("")) && (!fechaF.equals(""))) {
                    query = query + " AND p.pe_fecha >='" + fechaI + "' AND p.pe_fecha<='" + fechaF + "'";
                }
                if (numeroN != 0) {
                    query = query + " AND p.pe_num = " + numeroN;
                }
                if (!matricula.equals("")) {
                    query = query + " AND p.pe_ve_matricula like '%" + matricula + "%'";
                }
  
                if (!poblacionOrigen.equals("")) {
                    query = query + " AND p.pe_poblacion_origen LIKE '%" + poblacionOrigen + "%'";
                }
                if (!provinciaOrigen.equals("Selecciona")) {
                    query = query + " AND p.pe_provincia_origen='" + provinciaOrigen + "'";
                }
 
                if (!poblacionDestino.equals("")) {
                    query = query + " AND p.pe_poblacion_destino LIKE '%" + poblacionDestino + "%'";
                }
                if (!provinciaDestino.equals("Selecciona")) {
                    query = query + " AND p.pe_provincia_destino='" + provinciaDestino + "'";
                }
                
                if (!soporte.equals("Selecciona")) {
                    query = query + " AND p.pe_soporte='" + soporte + "'";
                }
                if (factor != 0) {
                    query = query + " AND fc.fc_id='" + factor + "'";
                }
                if (!estado.equals("Selecciona")) {
                    query = query + " AND p.pe_estado='" + estado + "'";
                }
                if (comercial > 1) {
                    query = query + " AND co_id= '" + comercial + "'";
                }
                if (!estado_ve.equals("Selecciona")) {
                    query = query + " AND pe_ve_estado = '" + estado_ve + "'";
                }
                if (peUnidos) {
                    query = query + " AND (pe_num_unido != 0 OR destino_unido IS NOT null)";
                }
                if (incidencia.equals("Todas")) {
                    query = query + " AND (pe_incidencia != '' OR NOT NULL)";
                }else if(!incidencia.equals("")){
                    query = query + " AND pe_incidencia = '" + incidencia + "'";
                }

                //Orden de la query
                int orden = new Integer(jComboOrden.getSelectedIndex());

                String order = "";
                switch (orden) {
                    case 0:  order = "p.pe_num";
                             break;
                    case 1:  order = "p.pe_fecha";
                             break;
                    case 2:  order = "p.pe_ta_es_cliente";
                             break;
                    case 3:  order = "p.pe_ta_es_proveedor";
                             break;
                    case 4:  order = "p.pe_fecha_origen";
                             break;
                    case 5:  order = "p.pe_fecha_destino";
                             break;
                    default: order = "p.pe_fecha";
                             break;
                }

                query = query + " ORDER BY " + order + " ASC";
                System.out.println(query);
                CSResultBuscarPedidoNew resultBuscarPedido = new CSResultBuscarPedidoNew(query);
            } catch (UnknownHostException ex) {
                Logger.getLogger(CSBuscarPedidoNew.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CSBuscarPedidoNew.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CSBuscarPedidoNew.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void getComercial() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT co_id, co_nombre FROM co_comerciales");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("co_nombre");

            jComboBoxComercial.addItem(valor);
            jComboBoxComercial.setSelectedIndex(0);

            j++;
        }
     }

    private void jToggleButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonClienteActionPerformed

        System.out.println("\nBotón Buscar Cliente en Añadir Pedido.");
        CSDesktop.BuscaCliente = new JInternalFrame("Seleccionar Cliente", true, false, false, true );
        // adjuntar panel al panel de contenido del marco interno
        CSSelectCliente panel = new CSSelectCliente(jTextCliente,"",true);
        CSDesktop.BuscaCliente.getContentPane().add(panel,BorderLayout.CENTER);
        // establecer tama�o de marco interno en el tama�o de su contenido
        CSDesktop.BuscaCliente.pack();
        // adjuntar marco interno al escritorio y mostrarlo
        CSDesktop.elEscritorio.add( CSDesktop.BuscaCliente );
        CSDesktop.BuscaCliente.setLocation(150, 50);
        CSDesktop.BuscaCliente.setVisible( true );
}//GEN-LAST:event_jToggleButtonClienteActionPerformed

    private void jToggleButtonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonProveedorActionPerformed
        System.out.println("\nBotón Buscar Cliente en Añadir Pedido.");

        CSDesktop.BuscaProveedor = new JInternalFrame("Seleccionar Proveedor", true, false, false, true );
        // adjuntar panel al panel de contenido del marco interno
        CSSelectProveedor panel = new CSSelectProveedor(jTextProveedor,"",true);
        CSDesktop.BuscaProveedor.getContentPane().add( panel,BorderLayout.CENTER);
        // establecer tama�o de marco interno en el tama�o de su contenido
        CSDesktop.BuscaProveedor.pack();
        // adjuntar marco interno al escritorio y mostrarlo
        CSDesktop.elEscritorio.add( CSDesktop.BuscaProveedor );
        CSDesktop.BuscaProveedor.setLocation(150, 50);
        CSDesktop.BuscaProveedor.setVisible( true );
}//GEN-LAST:event_jToggleButtonProveedorActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       CSDesktop.BuscarPedidoNew.dispose();
       CSDesktop.menuBuscarPedidoNew.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextPoblacionOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionOrigenFocusLost
       String PoblacionOrigenM = jTextPoblacionOrigen.getText().toUpperCase();
       jTextPoblacionOrigen.setText(PoblacionOrigenM);
    }//GEN-LAST:event_jTextPoblacionOrigenFocusLost

    private void jTextPoblacionDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionDestinoFocusLost
       String PoblacionDestinoM = jTextPoblacionDestino.getText().toUpperCase();
       jTextPoblacionDestino.setText(PoblacionDestinoM);
    }//GEN-LAST:event_jTextPoblacionDestinoFocusLost

    private void jTextMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextMatriculaFocusLost
        String MatriculaM = jTextMatricula.getText().toUpperCase();
       jTextMatricula.setText(MatriculaM);
    }//GEN-LAST:event_jTextMatriculaFocusLost

    private void jButtonBuscarSProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarSProvActionPerformed

        String query="SELECT p.pe_num, p.pe_fecha, cl.cl_nombre, p.pe_servicio, p.pe_provincia_origen, p.pe_provincia_destino, " +
                    "fc.fc_nombre, p.pe_ve_matricula, pe_ve_marca, pe_ve_modelo, p.pe_ta_es_cliente, p.pe_ta_es_proveedor, " +
                    "p.pe_suplemento, p.pe_fecha_real_destino, p.pe_estado, p.pe_estado, p.pe_descripcion, cl.co_id" +
                    " FROM pe_pedidos p, pc_pedidos_clientes pc, fc_factores_correccion fc , pp_pedidos_proveedores pp" +
                    " INNER JOIN cl_clientes cl " +
                    " WHERE pc.cl_id = cl.cl_id AND pp.pr_id = 0 AND p.pe_num = pc.pe_num AND p.pe_num = pp.pe_num AND p.fc_id = fc.fc_id";

            System.out.println(query);

            CSResultBuscarSinPrPedido resultBuscarPedido = new CSResultBuscarSinPrPedido(query);
    }//GEN-LAST:event_jButtonBuscarSProvActionPerformed

    private void jCheckBoxUnidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUnidosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCheckBoxUnidosActionPerformed

    private void jCBoxEstadoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxEstadoVehiculoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCBoxEstadoVehiculoActionPerformed

    private void jTextMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMatriculaActionPerformed

    private void jComboFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboFactorActionPerformed

}//GEN-LAST:event_jComboFactorActionPerformed

    private void jComboBoxIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIncidenciasActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxIncidenciasActionPerformed

    private void jComboOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboOrdenActionPerformed

 public Dimension getPreferredSize()
   {
      return new Dimension( 1075,400 );
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarSProv;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jCBoxEstadoVehiculo;
    private javax.swing.JCheckBox jCheckBoxUnidos;
    private javax.swing.JComboBox jComboBoxComercial;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxIncidencias;
    private javax.swing.JComboBox jComboBoxProvinciaDestino;
    private javax.swing.JComboBox jComboBoxProvinciaOrigen;
    private javax.swing.JComboBox jComboBoxSoporte;
    private javax.swing.JComboBox jComboFactor;
    private javax.swing.JComboBox jComboOrden;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private com.toedter.calendar.JDateChooser jDateFechaFin;
    private javax.swing.JLabel jLabelOrder;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField jTextCliente;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPoblacionDestino;
    private javax.swing.JTextField jTextPoblacionOrigen;
    private javax.swing.JTextField jTextProveedor;
    private javax.swing.JToggleButton jToggleButtonCliente;
    private javax.swing.JToggleButton jToggleButtonProveedor;
    private javax.swing.JLabel lCliente;
    private javax.swing.JLabel lComercial;
    private javax.swing.JLabel lDestino1;
    private javax.swing.JLabel lEstado3;
    private javax.swing.JLabel lEstado4;
    private javax.swing.JLabel lFechaFin;
    private javax.swing.JLabel lFechaIni;
    private javax.swing.JLabel lMatricula;
    private javax.swing.JLabel lMatricula1;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lOrigen1;
    private javax.swing.JLabel lPoblacionDestino;
    private javax.swing.JLabel lPoblacionOrigen;
    private javax.swing.JLabel lProveedor;
    private javax.swing.JLabel lProvinciaDestino;
    private javax.swing.JLabel lProvinciaOrigen;
    private javax.swing.JLabel lServicio;
    private javax.swing.JLabel lServicioFMad2;
    private javax.swing.JLabel lVehiculo;
    private javax.swing.JLabel lincidencias;
    // End of variables declaration//GEN-END:variables


  /**
   *
   * @throws SQLException
   */
  private void getFactorCorrecion() throws SQLException
  {
        ResultSet rs = CSDesktop.datos.select("SELECT fc_id, fc_nombre FROM fc_factores_correccion");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            jComboFactor.addItem(rs.getString("fc_nombre"));
            jComboFactor.setSelectedIndex(0);
            j++;
        }
     }

    private void limitacionesCampos()
    {
       LimitadorDeDocumento limitadorPoblacionOrigen= new LimitadorDeDocumento(50);
       jTextPoblacionOrigen.setDocument(limitadorPoblacionOrigen);
       LimitadorDeDocumento limitadorPoblacionDestino= new LimitadorDeDocumento(50);
       jTextPoblacionDestino.setDocument(limitadorPoblacionDestino);
       LimitadorDeDocumento limitadorMatricula= new LimitadorDeDocumento(10);
       jTextMatricula.setDocument(limitadorMatricula);
    }
    
}