/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABBuscarPedido.java
 *
 * Created on 07-oct-2009, 17:50:47
 */

package neg;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.LimitadorDeDocumento;
import data.Cliente;
import data.Proveedor;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author depr73
 */
public class CSBuscarPedido extends javax.swing.JPanel
{
    int clienteID=0;
    int proveedorID=0;
    private String fecha2;

    /** Creates new form ABBuscarPedido */
    public CSBuscarPedido()
    {

        CSDesktop.menuBuscarPedido.setEnabled(false);
        initComponents();
        try {
            getComercial();
        } catch (SQLException ex) {
            Logger.getLogger(CSBuscarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        limitacionesCampos();

         KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonBuscar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };

        for (int k = 0; k < this.getComponents().length; k ++)
        {
            if (this.getComponents()[k] != jComboBoxProvinciaOrigen &&
                this.getComponents()[k] != jComboBoxProvinciaDestino &&
                this.getComponents()[k] != jComboFactor &&
                this.getComponents()[k] != jComboBoxServicioFMad &&
                this.getComponents()[k] != jComboBoxServicioFMadDestino &&
                this.getComponents()[k] != jComboBoxSoporte &&
                this.getComponents()[k] != jComboBoxEstado &&
                this.getComponents()[k] != jComboBoxComercial)
            {
                this.getComponents()[k].addKeyListener(l);
            }
        }
        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxSoporte = new javax.swing.JComboBox();
        jSeparator4 = new javax.swing.JSeparator();
        lDestino1 = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        lMatricula = new javax.swing.JLabel();
        lPoblacionDestino = new javax.swing.JLabel();
        lVehiculo = new javax.swing.JLabel();
        jToggleButtonCliente = new javax.swing.JToggleButton();
        lCliente = new javax.swing.JLabel();
        jTextDireccionOrigen1 = new javax.swing.JTextField();
        lOrigen1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lDireccionOrigen1 = new javax.swing.JLabel();
        jToggleButtonProveedor = new javax.swing.JToggleButton();
        lProvinciaOrigen = new javax.swing.JLabel();
        jTextProveedor = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        jTextPoblacionOrigen = new javax.swing.JTextField();
        lDireccionDestino1 = new javax.swing.JLabel();
        lEstado3 = new javax.swing.JLabel();
        lCodPostalDestino = new javax.swing.JLabel();
        jComboBoxProvinciaDestino = new javax.swing.JComboBox();
        jTextDireccionDestino1 = new javax.swing.JTextField();
        lFechaIni = new javax.swing.JLabel();
        jTextPoblacionDestino = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox();
        jTextCodPostalOrigen = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jComboBoxProvinciaOrigen = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        lCodPostalOrigen = new javax.swing.JLabel();
        jTextCodPostalDestino = new javax.swing.JTextField();
        jTextNumero = new javax.swing.JTextField();
        lProveedor = new javax.swing.JLabel();
        jTextCliente = new javax.swing.JTextField();
        lPoblacionOrigen = new javax.swing.JLabel();
        lProvinciaDestino = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        lFechaFin = new javax.swing.JLabel();
        jDateFechaFin = new com.toedter.calendar.JDateChooser();
        jComboBoxServicioFMad = new javax.swing.JComboBox();
        lServicioFMad2 = new javax.swing.JLabel();
        jComboFactor = new javax.swing.JComboBox();
        lServicio = new javax.swing.JLabel();
        lServicioFMad = new javax.swing.JLabel();
        jComboBoxServicioFMadDestino = new javax.swing.JComboBox();
        lServicioFMad1 = new javax.swing.JLabel();
        lSEspecial = new javax.swing.JLabel();
        jComboBoxServicioEspecial = new javax.swing.JComboBox();
        lComercial = new javax.swing.JLabel();
        jComboBoxComercial = new javax.swing.JComboBox();
        jButtonBuscarSProv = new javax.swing.JButton();

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setName("jButtonBuscar"); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxSoporte.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxSoporte.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxSoporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Grúa", "Camión completo", "Conductor", "Tren", "Custodia", "Traslado pesado" }));
        jComboBoxSoporte.setName("jComboBoxSoporte"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N

        lDestino1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lDestino1.setForeground(new java.awt.Color(170, 16, 4));
        lDestino1.setText("DATOS DEL DESTINO");
        lDestino1.setName("lDestino1"); // NOI18N

        jTextMatricula.setName("jTextMatricula"); // NOI18N
        jTextMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextMatriculaFocusLost(evt);
            }
        });

        lMatricula.setForeground(new java.awt.Color(0, 0, 100));
        lMatricula.setText("Matrícula");
        lMatricula.setName("lMatricula"); // NOI18N

        lPoblacionDestino.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionDestino.setText("Población");
        lPoblacionDestino.setName("lPoblacionDestino"); // NOI18N

        lVehiculo.setForeground(new java.awt.Color(0, 0, 100));
        lVehiculo.setText("Soporte");
        lVehiculo.setName("lVehiculo"); // NOI18N

        jToggleButtonCliente.setText("Buscar Cliente");
        jToggleButtonCliente.setName("jToggleButtonCliente"); // NOI18N
        jToggleButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonClienteActionPerformed(evt);
            }
        });

        lCliente.setForeground(new java.awt.Color(0, 0, 100));
        lCliente.setText("Cliente");
        lCliente.setName("lCliente"); // NOI18N

        jTextDireccionOrigen1.setName("jTextDireccionOrigen1"); // NOI18N
        jTextDireccionOrigen1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionOrigen1FocusLost(evt);
            }
        });

        lOrigen1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lOrigen1.setForeground(new java.awt.Color(170, 16, 4));
        lOrigen1.setText("DATOS DEL ORIGEN");
        lOrigen1.setName("lOrigen1"); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator1.setName("jSeparator1"); // NOI18N

        lDireccionOrigen1.setForeground(new java.awt.Color(0, 0, 100));
        lDireccionOrigen1.setText("Dirección");
        lDireccionOrigen1.setName("lDireccionOrigen1"); // NOI18N

        jToggleButtonProveedor.setText("Buscar Proveedor");
        jToggleButtonProveedor.setName("jToggleButtonProveedor"); // NOI18N
        jToggleButtonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonProveedorActionPerformed(evt);
            }
        });

        lProvinciaOrigen.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaOrigen.setText("Provincia");
        lProvinciaOrigen.setName("lProvinciaOrigen"); // NOI18N

        jTextProveedor.setEditable(false);
        jTextProveedor.setName("jTextProveedor"); // NOI18N

        lNumero.setForeground(new java.awt.Color(0, 0, 100));
        lNumero.setText("Núm. de pedido PE/");
        lNumero.setName("lNumero"); // NOI18N

        jTextPoblacionOrigen.setName("jTextPoblacionOrigen"); // NOI18N
        jTextPoblacionOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionOrigenFocusLost(evt);
            }
        });

        lDireccionDestino1.setForeground(new java.awt.Color(0, 0, 100));
        lDireccionDestino1.setText("Dirección");
        lDireccionDestino1.setName("lDireccionDestino1"); // NOI18N

        lEstado3.setForeground(new java.awt.Color(0, 0, 100));
        lEstado3.setText("Estado");
        lEstado3.setName("lEstado3"); // NOI18N

        lCodPostalDestino.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostalDestino.setText("Cód. Postal");
        lCodPostalDestino.setName("lCodPostalDestino"); // NOI18N

        jComboBoxProvinciaDestino.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaDestino.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaDestino.setName("jComboBoxProvinciaDestino"); // NOI18N

        jTextDireccionDestino1.setName("jTextDireccionDestino1"); // NOI18N
        jTextDireccionDestino1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionDestino1FocusLost(evt);
            }
        });

        lFechaIni.setForeground(new java.awt.Color(0, 0, 100));
        lFechaIni.setText("Fecha ini");
        lFechaIni.setName("lFechaIni"); // NOI18N

        jTextPoblacionDestino.setName("jTextPoblacionDestino"); // NOI18N
        jTextPoblacionDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionDestinoFocusLost(evt);
            }
        });

        jComboBoxEstado.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxEstado.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Activo", "En Proceso", "Entregado", "Facturado", "Facturado y Validado", "Cobrado", "Pagado", "Anulado", "Fallido" }));
        jComboBoxEstado.setName("jComboBoxEstado"); // NOI18N

        jTextCodPostalOrigen.setName("jTextCodPostalOrigen"); // NOI18N

        jSeparator6.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator6.setName("jSeparator6"); // NOI18N

        jComboBoxProvinciaOrigen.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaOrigen.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaOrigen.setName("jComboBoxProvinciaOrigen"); // NOI18N

        jSeparator5.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator5.setName("jSeparator5"); // NOI18N

        lCodPostalOrigen.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostalOrigen.setText("Cód. Postal");
        lCodPostalOrigen.setName("lCodPostalOrigen"); // NOI18N

        jTextCodPostalDestino.setName("jTextCodPostalDestino"); // NOI18N

        jTextNumero.setName("jTextNumero"); // NOI18N

        lProveedor.setForeground(new java.awt.Color(0, 0, 100));
        lProveedor.setText("Proveedor");
        lProveedor.setName("lProveedor"); // NOI18N

        jTextCliente.setEditable(false);
        jTextCliente.setName("jTextCliente"); // NOI18N

        lPoblacionOrigen.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionOrigen.setText("Población");
        lPoblacionOrigen.setName("lPoblacionOrigen"); // NOI18N

        lProvinciaDestino.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaDestino.setText("Provincia");
        lProvinciaDestino.setName("lProvinciaDestino"); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator3.setName("jSeparator3"); // NOI18N

        jDateFecha.setDateFormatString("dd-MM-yyyy"); // NOI18N
        jDateFecha.setName("jDateFecha"); // NOI18N

        lFechaFin.setForeground(new java.awt.Color(0, 0, 100));
        lFechaFin.setText("Fecha fin");
        lFechaFin.setName("lFechaFin"); // NOI18N

        jDateFechaFin.setDateFormatString("dd-MM-yyyy"); // NOI18N
        jDateFechaFin.setName("jDateFechaFin"); // NOI18N

        jComboBoxServicioFMad.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxServicioFMad.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxServicioFMad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA", "OTROS" }));
        jComboBoxServicioFMad.setName("jComboBoxServicioFMad"); // NOI18N

        lServicioFMad2.setForeground(new java.awt.Color(0, 0, 100));
        lServicioFMad2.setText("Factor");
        lServicioFMad2.setName("lServicioFMad2"); // NOI18N

        jComboFactor.setBackground(new java.awt.Color(228, 229, 255));
        jComboFactor.setForeground(new java.awt.Color(0, 0, 100));
        jComboFactor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Urbano", "Interurbano", "Provincial", "Urbano ITV", "Especial" }));
        jComboFactor.setName("jComboFactor"); // NOI18N

        lServicio.setFont(new java.awt.Font("Tahoma", 1, 11));
        lServicio.setForeground(new java.awt.Color(170, 16, 4));
        lServicio.setText("SERVICIOS");
        lServicio.setName("lServicio"); // NOI18N

        lServicioFMad.setForeground(new java.awt.Color(0, 0, 100));
        lServicioFMad.setText("Origen");
        lServicioFMad.setName("lServicioFMad"); // NOI18N

        jComboBoxServicioFMadDestino.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxServicioFMadDestino.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxServicioFMadDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA", "OTROS" }));
        jComboBoxServicioFMadDestino.setName("jComboBoxServicioFMadDestino"); // NOI18N

        lServicioFMad1.setForeground(new java.awt.Color(0, 0, 100));
        lServicioFMad1.setText("Destino");
        lServicioFMad1.setName("lServicioFMad1"); // NOI18N

        lSEspecial.setForeground(new java.awt.Color(0, 0, 100));
        lSEspecial.setText("Especial");
        lSEspecial.setName("lSEspecial"); // NOI18N

        jComboBoxServicioEspecial.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxServicioEspecial.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxServicioEspecial.setMaximumRowCount(20);
        jComboBoxServicioEspecial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Urgente", "ITV", "Pre_ITV", "ITV + Pre_ITV", "Peritación", "Mano obra Mecánica/Chapa", "Chequeo", "Repostaje", " ", "LAVADO DOMICILIO", "LD Exterior", "LD Interior y Exterior", "LD Integral", "LD Interior/Exterior 4x4", "LD Integral 4x4", "LD Interior/Exterior Industrial", "LD Integral Industrial", " ", "LAVADO CAMPA", "LC Exterior", "LC Interior y Exterior", "LC Integral", "LC Interior/Exterior 4x4", "LC Integral 4x4", "LC Interior/Exterior Industrial", "LC Integral Industrial", " ", "Desrotular pegatinas fácil", "Desrotular pegatinas normal", "Desrotular pegatinas difícil", "Rotular pegatinas fácil", "Rotular pegatinas normal", "Rotular pegatinas difícil", "Otros" }));
        jComboBoxServicioEspecial.setName("jComboBoxServicioEspecial"); // NOI18N
        jComboBoxServicioEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicioEspecialActionPerformed(evt);
            }
        });

        lComercial.setForeground(new java.awt.Color(0, 0, 100));
        lComercial.setText("Comercial");
        lComercial.setName("lComercial"); // NOI18N

        jComboBoxComercial.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxComercial.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxComercial.setName("jComboBoxComercial"); // NOI18N

        jButtonBuscarSProv.setText("Pedidos sin Proveedor");
        jButtonBuscarSProv.setName("jButtonBuscarSProv"); // NOI18N
        jButtonBuscarSProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarSProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBuscarSProv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDestino1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lDireccionDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDireccionDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(lPoblacionDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextPoblacionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lCodPostalDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextCodPostalDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lEstado3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(545, 545, 545)
                                .addComponent(lComercial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxComercial, 0, 143, Short.MAX_VALUE))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lVehiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(lMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButtonProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lFechaIni)
                                        .addGap(3, 3, 3)
                                        .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lFechaFin)
                                        .addGap(5, 5, 5)
                                        .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lOrigen1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lDireccionOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextDireccionOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(22, 22, 22)
                                            .addComponent(lPoblacionOrigen)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextPoblacionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lCodPostalOrigen)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextCodPostalOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lServicio)
                                .addGap(22, 22, 22)
                                .addComponent(lServicioFMad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lServicioFMad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxServicioFMad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lServicioFMad1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxServicioFMadDestino, 0, 165, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lSEspecial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxServicioEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lFechaIni)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButtonCliente)
                        .addComponent(lCliente))
                    .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lOrigen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccionOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCodPostalOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPoblacionOrigen)
                    .addComponent(jTextPoblacionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccionOrigen1)
                    .addComponent(jComboBoxProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodPostalOrigen)
                    .addComponent(lProvinciaOrigen))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDestino1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccionDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPoblacionDestino)
                    .addComponent(jTextPoblacionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccionDestino1)
                    .addComponent(jTextCodPostalDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodPostalDestino)
                    .addComponent(lProvinciaDestino)
                    .addComponent(jComboBoxProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxServicioEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lServicioFMad2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSEspecial)
                    .addComponent(jComboBoxServicioFMadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lServicioFMad1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxServicioFMad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lServicioFMad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lVehiculo)
                    .addComponent(jComboBoxSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonProveedor)
                    .addComponent(jTextProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProveedor)
                    .addComponent(lMatricula)
                    .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEstado3)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lComercial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonBuscarSProv))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        System.out.println("\njButtonGuardar_actionPerformed(ActionEvent e) called.");

        String fechaI="";
        String fechaF="";

        int numeroN=0;
        String numero = new String(jTextNumero.getText());
        if(!numero.equals(""))
           numeroN=Integer.valueOf(numero);

         Calendar fechaCalendar = jDateFecha.getCalendar();
        //String fecha = ConvertirFechaString(fechaCalendar);
        if (fechaCalendar!=null)
        {
            Date fecha = fechaCalendar.getTime();
            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
            fechaI=formatoDeFecha.format(fecha);
        }

        fechaCalendar = jDateFechaFin.getCalendar();
        //String fecha = ConvertirFechaString(fechaCalendar);
        if (fechaCalendar!=null)
        {
            Date fecha = fechaCalendar.getTime();
            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
            fechaF=formatoDeFecha.format(fecha);
        }
        String cliente=new String(jTextCliente.getText());
        String direccionOrigen=new String(jTextDireccionOrigen1.getText());
        String poblacionOrigen=new String(jTextPoblacionOrigen.getText());
        String provinciaOrigen=new String(jComboBoxProvinciaOrigen.getSelectedItem().toString());
        String codPostalOrigen=new String(jTextCodPostalOrigen.getText());
        String direccionDestino=new String(jTextDireccionDestino1.getText());
        String poblacionDestino=new String(jTextPoblacionDestino.getText());
        String provinciaDestino=new String(jComboBoxProvinciaDestino.getSelectedItem().toString());
        String codPostalDestino=new String(jTextCodPostalDestino.getText());
        int factor = new Integer(jComboFactor.getSelectedIndex());
        String servicio=new String(jComboFactor.getSelectedItem().toString());
        String servicioFMad=new String(jComboBoxServicioFMad.getSelectedItem().toString());
        String servicioFMadDestino=new String(jComboBoxServicioFMadDestino.getSelectedItem().toString());
        String soporte=new String(jComboBoxSoporte.getSelectedItem().toString());
        String matricula=new String(jTextMatricula.getText());
        String proveedor=new String(jTextProveedor.getText());
        String estado=new String(jComboBoxEstado.getSelectedItem().toString());
        int comercial = (jComboBoxComercial.getSelectedIndex()+1);

        String query="SELECT p.pe_num,p.pe_fecha,cl.cl_nombre,p.pe_servicio,p.pe_servicio_origen,p.pe_servicio_destino,"+
                " fc.fc_nombre,p.pe_ve_matricula, pe_ve_marca, pe_ve_modelo, pr.pr_nombre_fiscal," +
                " p.pe_ta_es_cliente, p.pe_ta_es_proveedor, p.pe_servicio_especial, p.pe_suplemento,pe_solred,p.pe_fecha_origen,p.pe_fecha_destino,p.pe_fecha_real_destino," +
                " p.pe_estado, p.pe_descripcion, p.pe_estado, cl.co_id, pc.cl_id" +
                " FROM pe_pedidos p, pc_pedidos_clientes pc, pp_pedidos_proveedores pp, fc_factores_correccion fc " +
                " INNER JOIN cl_clientes cl INNER JOIN pr_proveedores pr " +
                " WHERE pc.cl_id = cl.cl_id AND pp.pr_id = pr.pr_id  AND p.pe_num = pc.pe_num " +
                " AND p.pe_num = pp.pe_num AND p.fc_id = fc.fc_id";

//        String query = "SELECT DISTINCT p.pe_num, p.pe_fecha, p.pe_servicio_origen, p.pe_servicio_destino, " +
//               "p.pe_servicio, p.pe_servicio_origen, p.pe_servicio_destino, p.pe_servicio_especial, " +
//               "p.pe_dias_campa, p.pe_ida_vuelta, p.fc_id, p.pe_soporte, p.pe_ve_matricula, p.pe_ve_marca, " +
//               "p.pe_ve_modelo, p.pe_ta_es_cliente, p.pe_ta_es_proveedor, p.pe_suplemento,p.pe_num_en_camion, " +
//               "p.pe_descripcion, tc.tc_tarifa, sc_entrada_campa, sc_campa " +
//               "FROM pe_pedidos p, pc_pedidos_clientes pc, tc_tarifas_clientes tc, sc_servicios_clientes sc " +
//               "WHERE p.pe_num = pc.pe_num " +
//               "AND sc.cl_id = pc.cl_id " +
//               "AND tc.tc_fecha_hasta > p.pe_fecha " +
//               "AND sc.sc_fecha_hasta > p.pe_fecha " +
//               "AND tc.tc_servicio = p.pe_servicio " +
//               "AND tc.cl_id = pc.cl_id " +
//               "AND (tc.tc_servicio_origen = p.pe_servicio_origen " +
//               "OR tc.tc_servicio_origen = p.pe_servicio_destino) " +
//               "AND (tc.tc_servicio_destino = p.pe_servicio_destino " +
//               "OR tc.tc_servicio_destino = p.pe_servicio_origen) " +
//               "AND tc.tc_soporte = p.pe_soporte ";
               //"AND (pe.pe_estado = 'Activo' OR pe.pe_estado = 'En Proceso' OR pe.pe_estado = 'Entregado')"  +
               //"AND (pe.pe_estado != 'Entregado' OR pe.pe_estado = 'Fallido')"  +
               //"AND pe_fecha BETWEEN '"+fechaI+"' AND '"+fechaF+"' " +
               //"AND pc.cl_id = "+clienteID+"  GROUP BY pe.pe_num ORDER BY pe.pe_num ASC";

        if (numero.equals("") && cliente.equals("") && proveedor.equals("") && (fechaI.equals("") && fechaF.equals("") && matricula.equals("")))
        {
            jButtonBuscar.setEnabled(false);
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Debe seleccionar el número de pedido, un Cliente, un Proveedor, período de fecha o matrícula</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields);
            jButtonBuscar.setEnabled(true);
        }
        else
        {
            try {
                if (!cliente.equals("") && !proveedor.equals("")) {
                    Cliente cliente2 = new Cliente();
                    clienteID = cliente2.getClienteID(cliente);
                    Proveedor proveedor2 = new Proveedor();
                    proveedorID = proveedor2.getProveedorID(proveedor);
                    query = query + " AND pc.cl_id = " + clienteID + " AND pp.pr_id = " + proveedorID;
                } else if (!cliente.equals("")) {
                    Cliente cliente2 = new Cliente();
                    clienteID = cliente2.getClienteID(cliente);
                    query = query + " AND pc.cl_id = " + clienteID;
                } else if (!proveedor.equals("")) {
                    Proveedor proveedor2 = new Proveedor();
                    proveedorID = proveedor2.getProveedorID(proveedor);
                    query = query + " AND pp.pr_id = " + proveedorID;
                }
                if ((!fechaI.equals("")) && (!fechaF.equals(""))) {
                    query = query + " AND p.pe_fecha >='" + fechaI + "' AND p.pe_fecha<='" + fechaF + "'";
                }
                if (numeroN != 0) {
                    query = query + " AND p.pe_num = " + numeroN;
                }
                if (!matricula.equals("")) {
                    query = query + " AND p.pe_ve_matricula like '%" + matricula + "%'";
                }
                if (!direccionOrigen.equals("")) {
                    query = query + " AND p.pe_direccion_origen='" + direccionOrigen + "'";
                }
                if (!poblacionOrigen.equals("")) {
                    query = query + " AND p.pe_poblacion_origen='" + poblacionOrigen + "'";
                }
                if (!provinciaOrigen.equals("Selecciona")) {
                    query = query + " AND p.pe_provincia_origen='" + provinciaOrigen + "'";
                }
                if (!codPostalOrigen.equals("")) {
                    query = query + " AND p.pe_cp_origen='" + codPostalOrigen + "'";
                }
                if (!direccionDestino.equals("")) {
                    query = query + " AND p.pe_direccion_destino='" + direccionDestino + "'";
                }
                if (!poblacionDestino.equals("")) {
                    query = query + " AND p.pe_poblacion_destino='" + poblacionDestino + "'";
                }
                if (!provinciaDestino.equals("Selecciona")) {
                    query = query + " AND p.pe_provincia_destino='" + provinciaDestino + "'";
                }
                if (!codPostalDestino.equals("")) {
                    //query = query + " AND pe_cp_destino='"+codPostalDestino+"'";
                    query = query + " AND p.pe_cp_destino='" + codPostalDestino + "'";
                }
                if (!servicioFMad.equals("Selecciona")) {
                    query = query + " AND p.pe_servicio_origen='" + servicioFMad + "'";
                }
                if (!servicioFMadDestino.equals("Selecciona")) {
                    query = query + " AND p.pe_servicio_destino='" + servicioFMadDestino + "'";
                }
                if (!soporte.equals("Selecciona")) {
                    query = query + " AND p.pe_soporte='" + soporte + "'";
                }
                if (factor != 0) {
                    query = query + " AND fc.fc_id='" + factor + "'";
                }
                if (!estado.equals("Selecciona")) {
                    query = query + " AND p.pe_estado='" + estado + "'";
                }
                if (comercial > 1) {
                    query = query + " AND co_id= '" + comercial + "'";
                }
                query = query + " ORDER BY p.pe_fecha ASC";
                System.out.println(query);
                CSResultBuscarPedido resultBuscarPedido = new CSResultBuscarPedido(query);
            } catch (UnknownHostException ex) {
                Logger.getLogger(CSBuscarPedido.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CSBuscarPedido.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CSBuscarPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void getComercial() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT co_id, co_nombre FROM co_comerciales");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("co_nombre");

            jComboBoxComercial.addItem(valor);
            jComboBoxComercial.setSelectedIndex(0);

            j++;
        }
     }

    private void jToggleButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonClienteActionPerformed

        System.out.println("\nBotón Buscar Cliente en Añadir Pedido.");
        CSDesktop.BuscaCliente = new JInternalFrame("Seleccionar Cliente", true, false, false, true );
        // adjuntar panel al panel de contenido del marco interno
        CSSelectCliente panel = new CSSelectCliente(jTextCliente,"",true);
        CSDesktop.BuscaCliente.getContentPane().add(panel,BorderLayout.CENTER);
        // establecer tama�o de marco interno en el tama�o de su contenido
        CSDesktop.BuscaCliente.pack();
        // adjuntar marco interno al escritorio y mostrarlo
        CSDesktop.elEscritorio.add( CSDesktop.BuscaCliente );
        CSDesktop.BuscaCliente.setLocation(150, 50);
        CSDesktop.BuscaCliente.setVisible( true );
}//GEN-LAST:event_jToggleButtonClienteActionPerformed

    private void jToggleButtonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonProveedorActionPerformed
        System.out.println("\nBotón Buscar Cliente en Añadir Pedido.");

        CSDesktop.BuscaProveedor = new JInternalFrame("Seleccionar Proveedor", true, false, false, true );
        // adjuntar panel al panel de contenido del marco interno
        CSSelectProveedor panel = new CSSelectProveedor(jTextProveedor,"",true);
        CSDesktop.BuscaProveedor.getContentPane().add( panel,BorderLayout.CENTER);
        // establecer tama�o de marco interno en el tama�o de su contenido
        CSDesktop.BuscaProveedor.pack();
        // adjuntar marco interno al escritorio y mostrarlo
        CSDesktop.elEscritorio.add( CSDesktop.BuscaProveedor );
        CSDesktop.BuscaProveedor.setLocation(150, 50);
        CSDesktop.BuscaProveedor.setVisible( true );
}//GEN-LAST:event_jToggleButtonProveedorActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       CSDesktop.BuscarPedido.dispose();
       CSDesktop.menuBuscarPedido.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextDireccionOrigen1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionOrigen1FocusLost
       String DireccionOrigenM = jTextDireccionOrigen1.getText().toUpperCase();
       jTextDireccionOrigen1.setText(DireccionOrigenM);
    }//GEN-LAST:event_jTextDireccionOrigen1FocusLost

    private void jTextPoblacionOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionOrigenFocusLost
       String PoblacionOrigenM = jTextPoblacionOrigen.getText().toUpperCase();
       jTextPoblacionOrigen.setText(PoblacionOrigenM);
    }//GEN-LAST:event_jTextPoblacionOrigenFocusLost

    private void jTextDireccionDestino1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionDestino1FocusLost
        String DireccionDestinoM = jTextDireccionDestino1.getText().toUpperCase();
       jTextDireccionDestino1.setText(DireccionDestinoM);
    }//GEN-LAST:event_jTextDireccionDestino1FocusLost

    private void jTextPoblacionDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionDestinoFocusLost
       String PoblacionDestinoM = jTextPoblacionDestino.getText().toUpperCase();
       jTextPoblacionDestino.setText(PoblacionDestinoM);
    }//GEN-LAST:event_jTextPoblacionDestinoFocusLost

    private void jTextMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextMatriculaFocusLost
        String MatriculaM = jTextMatricula.getText().toUpperCase();
       jTextMatricula.setText(MatriculaM);
    }//GEN-LAST:event_jTextMatriculaFocusLost

    private void jComboBoxServicioEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicioEspecialActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxServicioEspecialActionPerformed

    private void jButtonBuscarSProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarSProvActionPerformed

        String query="SELECT p.pe_num,p.pe_fecha,cl.cl_nombre,p.pe_servicio,p.pe_servicio_origen,p.pe_servicio_destino,"+
                " fc.fc_nombre,p.pe_ve_matricula, pe_ve_marca, pe_ve_modelo, p.pe_ta_es_cliente, " +
                "p.pe_ta_es_proveedor,p.pe_suplemento,pe_solred,p.pe_fecha_real_destino," +
                " p.pe_estado, p.pe_estado, p.pe_descripcion, cl.co_id" +
                " FROM pe_pedidos p, pc_pedidos_clientes pc, fc_factores_correccion fc , pp_pedidos_proveedores pp" +
                " INNER JOIN cl_clientes cl " +
                " WHERE pc.cl_id = cl.cl_id AND pp.pr_id = 0 AND p.pe_num = pc.pe_num AND p.pe_num = pp.pe_num AND p.fc_id = fc.fc_id";

            System.out.println(query);

            CSResultBuscarSinPrPedido resultBuscarPedido = new CSResultBuscarSinPrPedido(query);
    }//GEN-LAST:event_jButtonBuscarSProvActionPerformed

 public Dimension getPreferredSize()
   {
      return new Dimension( 1020,500 );
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonBuscarSProv;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboBoxComercial;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxProvinciaDestino;
    private javax.swing.JComboBox jComboBoxProvinciaOrigen;
    private javax.swing.JComboBox jComboBoxServicioEspecial;
    private javax.swing.JComboBox jComboBoxServicioFMad;
    private javax.swing.JComboBox jComboBoxServicioFMadDestino;
    private javax.swing.JComboBox jComboBoxSoporte;
    private javax.swing.JComboBox jComboFactor;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private com.toedter.calendar.JDateChooser jDateFechaFin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTextField jTextCliente;
    private javax.swing.JTextField jTextCodPostalDestino;
    private javax.swing.JTextField jTextCodPostalOrigen;
    private javax.swing.JTextField jTextDireccionDestino1;
    private javax.swing.JTextField jTextDireccionOrigen1;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPoblacionDestino;
    private javax.swing.JTextField jTextPoblacionOrigen;
    private javax.swing.JTextField jTextProveedor;
    private javax.swing.JToggleButton jToggleButtonCliente;
    private javax.swing.JToggleButton jToggleButtonProveedor;
    private javax.swing.JLabel lCliente;
    private javax.swing.JLabel lCodPostalDestino;
    private javax.swing.JLabel lCodPostalOrigen;
    private javax.swing.JLabel lComercial;
    private javax.swing.JLabel lDestino1;
    private javax.swing.JLabel lDireccionDestino1;
    private javax.swing.JLabel lDireccionOrigen1;
    private javax.swing.JLabel lEstado3;
    private javax.swing.JLabel lFechaFin;
    private javax.swing.JLabel lFechaIni;
    private javax.swing.JLabel lMatricula;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lOrigen1;
    private javax.swing.JLabel lPoblacionDestino;
    private javax.swing.JLabel lPoblacionOrigen;
    private javax.swing.JLabel lProveedor;
    private javax.swing.JLabel lProvinciaDestino;
    private javax.swing.JLabel lProvinciaOrigen;
    private javax.swing.JLabel lSEspecial;
    private javax.swing.JLabel lServicio;
    private javax.swing.JLabel lServicioFMad;
    private javax.swing.JLabel lServicioFMad1;
    private javax.swing.JLabel lServicioFMad2;
    private javax.swing.JLabel lVehiculo;
    // End of variables declaration//GEN-END:variables


    private void limitacionesCampos()
    {
       LimitadorDeDocumento limitadorPoblacionOrigen= new LimitadorDeDocumento(50);
       jTextPoblacionOrigen.setDocument(limitadorPoblacionOrigen);
       LimitadorDeDocumento limitadorCPOrigen= new LimitadorDeDocumento(5);
       jTextCodPostalOrigen.setDocument(limitadorCPOrigen);
       LimitadorDeDocumento limitadorPoblacionDestino= new LimitadorDeDocumento(50);
       jTextPoblacionDestino.setDocument(limitadorPoblacionDestino);
       LimitadorDeDocumento limitadorCPDestino= new LimitadorDeDocumento(5);
       jTextCodPostalDestino.setDocument(limitadorCPDestino);
       LimitadorDeDocumento limitadorMatricula= new LimitadorDeDocumento(10);
       jTextMatricula.setDocument(limitadorMatricula);
    }
    
}