/*
 * CSEditarCliente.java
 *
 * Created on 06-oct-2009, 22:04:43
 */
package neg;

import java.net.UnknownHostException;
import utils.Utilidades;
import utils.TablaModelo;
import utils.LimitadorDeDocumento;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import data.DbConnection;
import javax.swing.JFileChooser;
import utils.FileChooser;

/**
 *
 * @author lito
 */
public class CSEditarClienteNew extends javax.swing.JPanel
{
    public static String urlTarifas = "";
    /** Creates new form ABEditarCliente */
    public CSEditarClienteNew(int cliente) throws SQLException
    {
        initComponents();      
        limitacionesCampos();
        getFPagoClientes();
        getComercial();
        this.datosCliente(cliente);
        this.ABResultBuscarContactos(cliente);
        
        if(CSDesktop.group == 3){
            jTextNombre.setEditable(false);
        }

        //getDepartamentoContacto();r

        KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {
            }
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonModificar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar1.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };

        for (int k = 0; k < this.jPanel1.getComponents().length; k ++)
        {
            if (this.jPanel1.getComponents()[k] != jComboBoxEstado &&
                this.jPanel1.getComponents()[k] != jComboBoxFPago &&
                this.jPanel1.getComponents()[k] != jComboBoxPlazo &&
                this.jPanel1.getComponents()[k] != jComboBoxProvinciaFiscal &&
                this.jPanel1.getComponents()[k] != jComboBoxTarifa &&
                this.jPanel1.getComponents()[k] != jComboBoxProvincia &&
                this.jPanel1.getComponents()[k] != jComboBoxTipo)
            {
                this.jPanel1.getComponents()[k].addKeyListener(l);
            }
        }
        this.jPanel1.addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lPContacto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContactos = new javax.swing.JTable();
        jButtonModificar = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSEspeciales = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextDireccionFiscal = new javax.swing.JTextField();
        lCodPostalFiscal = new javax.swing.JLabel();
        lPoblacionFiscal = new javax.swing.JLabel();
        jTextCodPostalFiscal = new javax.swing.JTextField();
        lProvinciaFiscal = new javax.swing.JLabel();
        jTextPoblacionFiscal = new javax.swing.JTextField();
        jComboBoxProvinciaFiscal = new javax.swing.JComboBox();
        lPContacto1 = new javax.swing.JLabel();
        lDireccion1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lTelefono = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jComboBoxPlazo = new javax.swing.JComboBox();
        lEmail = new javax.swing.JLabel();
        jTextFax = new javax.swing.JTextField();
        lFax = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        jDateChooserAlta = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxTarifa = new javax.swing.JComboBox();
        lTarifa = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox();
        lTipo = new javax.swing.JLabel();
        jTextSucursal = new javax.swing.JTextField();
        jCheckBoxCorreo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jTextEntidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lProvincia = new javax.swing.JLabel();
        lComercial = new javax.swing.JLabel();
        jComboBoxComercial = new javax.swing.JComboBox();
        jTextDNI = new javax.swing.JTextField();
        lDNI = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        lDireccion = new javax.swing.JLabel();
        jTextCodPostal = new javax.swing.JTextField();
        lCodPostal = new javax.swing.JLabel();
        jTextPoblacion = new javax.swing.JTextField();
        lPoblacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProvincia = new javax.swing.JComboBox();
        jLabelO = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextDigito = new javax.swing.JTextField();
        jTextNumCuenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextWeb = new javax.swing.JTextField();
        lWeb = new javax.swing.JLabel();
        jTextAtt = new javax.swing.JTextField();
        jTextNumIban = new javax.swing.JTextField();
        lNumCuenta = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        jComboBoxFPago = new javax.swing.JComboBox();
        lFPago = new javax.swing.JLabel();
        lPlazo = new javax.swing.JLabel();
        lEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        lFactura = new javax.swing.JLabel();
        lDiasPlazo = new javax.swing.JLabel();
        jTextDiasPlazo = new javax.swing.JTextField();
        jTextTelefono2 = new javax.swing.JTextField();
        lTelefono2 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(874, 661));

        jPanel1.setName("jPanel1"); // NOI18N

        lPContacto.setFont(new java.awt.Font("Tahoma", 1, 11));
        lPContacto.setForeground(new java.awt.Color(170, 16, 4));
        lPContacto.setText("PERSONA DE CONTACTO");
        lPContacto.setName("lPContacto"); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator1.setName("jSeparator1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablaContactos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaContactos.setName("tablaContactos"); // NOI18N
        jScrollPane1.setViewportView(tablaContactos);

        jButtonModificar.setText("Modificar");
        jButtonModificar.setName("jButtonModificar"); // NOI18N
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonCancelar1.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar1.setText("Cancelar");
        jButtonCancelar1.setName("jButtonCancelar1"); // NOI18N
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.setEnabled(false);
        Eliminar.setName("Eliminar"); // NOI18N
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("* Campos obligatorios");
        jLabel1.setName("jLabel1"); // NOI18N

        jButtonSEspeciales.setText("Editar Servicios");
        jButtonSEspeciales.setName("jButtonSEspeciales"); // NOI18N
        jButtonSEspeciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSEspecialesActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 100));
        jLabel7.setText("     Precios de Servicios Especiales");
        jLabel7.setName("jLabel7"); // NOI18N

        jTextDireccionFiscal.setName("jTextDireccionFiscal"); // NOI18N
        jTextDireccionFiscal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionFiscalFocusLost(evt);
            }
        });

        lCodPostalFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostalFiscal.setText("Código Postal");
        lCodPostalFiscal.setName("lCodPostalFiscal"); // NOI18N

        lPoblacionFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionFiscal.setText("   Población");
        lPoblacionFiscal.setName("lPoblacionFiscal"); // NOI18N

        jTextCodPostalFiscal.setName("jTextCodPostalFiscal"); // NOI18N

        lProvinciaFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaFiscal.setText("Provincia");
        lProvinciaFiscal.setName("lProvinciaFiscal"); // NOI18N

        jTextPoblacionFiscal.setName("jTextPoblacionFiscal"); // NOI18N
        jTextPoblacionFiscal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionFiscalFocusLost(evt);
            }
        });

        jComboBoxProvinciaFiscal.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaFiscal.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaFiscal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaFiscal.setName("jComboBoxProvinciaFiscal"); // NOI18N

        lPContacto1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lPContacto1.setForeground(new java.awt.Color(170, 16, 4));
        lPContacto1.setText("DOMICILIO FISCAL");
        lPContacto1.setName("lPContacto1"); // NOI18N

        lDireccion1.setForeground(new java.awt.Color(0, 0, 100));
        lDireccion1.setText("   Dirección");
        lDireccion1.setName("lDireccion1"); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator3.setName("jSeparator3"); // NOI18N

        lTelefono.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono.setText("Teléfono");
        lTelefono.setName("lTelefono"); // NOI18N

        jTextTelefono.setMinimumSize(new java.awt.Dimension(9, 9));
        jTextTelefono.setName("jTextTelefono"); // NOI18N

        jComboBoxPlazo.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxPlazo.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxPlazo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30 días FF", "15 días FF", "45 días FF", "60 días FF", "Especial" }));
        jComboBoxPlazo.setName("jComboBoxPlazo"); // NOI18N
        jComboBoxPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlazoActionPerformed(evt);
            }
        });

        lEmail.setForeground(new java.awt.Color(0, 0, 100));
        lEmail.setText("Att.");
        lEmail.setName("lEmail"); // NOI18N

        jTextFax.setName("jTextFax"); // NOI18N

        lFax.setForeground(new java.awt.Color(0, 0, 100));
        lFax.setText("Fax");
        lFax.setName("lFax"); // NOI18N

        jTextNumero.setEditable(false);
        jTextNumero.setEnabled(false);
        jTextNumero.setName("jTextNumero"); // NOI18N

        lNumero.setForeground(new java.awt.Color(0, 0, 100));
        lNumero.setText("    Nº. Cliente  CL/");
        lNumero.setName("lNumero"); // NOI18N

        jDateChooserAlta.setDateFormatString("dd-MM-yyyy");
        jDateChooserAlta.setName("jDateChooserAlta"); // NOI18N

        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("*");
        jLabel14.setName("jLabel14"); // NOI18N

        jComboBoxTarifa.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxTarifa.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxTarifa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  1", "  2", "  3", "  4", "  5", "  6", "  7", "  8", "  9", " 10" }));
        jComboBoxTarifa.setName("jComboBoxTarifa"); // NOI18N

        lTarifa.setForeground(new java.awt.Color(0, 0, 100));
        lTarifa.setText("Tipo de Tarifa");
        lTarifa.setName("lTarifa"); // NOI18N

        jTextNombre.setName("jTextNombre"); // NOI18N
        jTextNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreFocusLost(evt);
            }
        });

        jComboBoxTipo.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxTipo.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empresa", "Concesionario", "Renting", "Compraventa", "Particular", "Proveedor", "Fabricante", "Asistencia", "Rent a car", "Intermediario Renting", "Carrocero", "Otros" }));
        jComboBoxTipo.setName("jComboBoxTipo"); // NOI18N

        lTipo.setForeground(new java.awt.Color(0, 0, 100));
        lTipo.setText("    Tipo");
        lTipo.setName("lTipo"); // NOI18N

        jTextSucursal.setEnabled(false);
        jTextSucursal.setName("jTextSucursal"); // NOI18N

        jCheckBoxCorreo.setForeground(new java.awt.Color(0, 0, 100));
        jCheckBoxCorreo.setText("C. Ordinario");
        jCheckBoxCorreo.setName("jCheckBoxCorreo"); // NOI18N
        jCheckBoxCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCorreoActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("*");
        jLabel8.setName("jLabel8"); // NOI18N

        jTextEntidad.setEnabled(false);
        jTextEntidad.setName("jTextEntidad"); // NOI18N
        jTextEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEntidadActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("*");
        jLabel9.setName("jLabel9"); // NOI18N

        lProvincia.setForeground(new java.awt.Color(0, 0, 100));
        lProvincia.setText("Provincia");
        lProvincia.setName("lProvincia"); // NOI18N

        lComercial.setForeground(new java.awt.Color(0, 0, 100));
        lComercial.setText("Comercial");
        lComercial.setName("lComercial"); // NOI18N

        jComboBoxComercial.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxComercial.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxComercial.setName("jComboBoxComercial"); // NOI18N
        jComboBoxComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxComercialActionPerformed(evt);
            }
        });

        jTextDNI.setName("jTextDNI"); // NOI18N
        jTextDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDNIFocusLost(evt);
            }
        });

        lDNI.setForeground(new java.awt.Color(0, 0, 100));
        lDNI.setText("DNI/CIF");
        lDNI.setName("lDNI"); // NOI18N

        jTextDireccion.setName("jTextDireccion"); // NOI18N
        jTextDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionFocusLost(evt);
            }
        });

        lDireccion.setForeground(new java.awt.Color(0, 0, 100));
        lDireccion.setText("Dirección");
        lDireccion.setName("lDireccion"); // NOI18N

        jTextCodPostal.setName("jTextCodPostal"); // NOI18N

        lCodPostal.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostal.setText("Código Postal");
        lCodPostal.setName("lCodPostal"); // NOI18N

        jTextPoblacion.setName("jTextPoblacion"); // NOI18N
        jTextPoblacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionFocusLost(evt);
            }
        });

        lPoblacion.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacion.setText("Población");
        lPoblacion.setName("lPoblacion"); // NOI18N

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("*");
        jLabel2.setName("jLabel2"); // NOI18N

        jComboBoxProvincia.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvincia.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvincia.setName("jComboBoxProvincia"); // NOI18N

        jLabelO.setForeground(new java.awt.Color(204, 0, 0));
        jLabelO.setText("*");
        jLabelO.setName("jLabelO"); // NOI18N

        jToggleButton1.setText("Dir. Tarifas");
        jToggleButton1.setName("jToggleButton1"); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTextDigito.setEnabled(false);
        jTextDigito.setName("jTextDigito"); // NOI18N

        jTextNumCuenta.setEnabled(false);
        jTextNumCuenta.setName("jTextNumCuenta"); // NOI18N

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("*");
        jLabel4.setName("jLabel4"); // NOI18N

        jTextWeb.setName("jTextWeb"); // NOI18N
        jTextWeb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextWebFocusLost(evt);
            }
        });

        lWeb.setForeground(new java.awt.Color(0, 0, 100));
        lWeb.setText("Web");
        lWeb.setName("lWeb"); // NOI18N

        jTextAtt.setName("jTextAtt"); // NOI18N
        jTextAtt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAttFocusLost(evt);
            }
        });

        jTextNumIban.setEnabled(false);
        jTextNumIban.setName("jTextNumIban"); // NOI18N
        jTextNumIban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumIbanActionPerformed(evt);
            }
        });

        lNumCuenta.setForeground(new java.awt.Color(0, 0, 100));
        lNumCuenta.setText("IBAN");
        lNumCuenta.setName("lNumCuenta"); // NOI18N

        lNombre.setForeground(new java.awt.Color(0, 0, 100));
        lNombre.setText("Nombre");
        lNombre.setName("lNombre"); // NOI18N

        jComboBoxFPago.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxFPago.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxFPago.setName("jComboBoxFPago"); // NOI18N
        jComboBoxFPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFPagoActionPerformed(evt);
            }
        });

        lFPago.setForeground(new java.awt.Color(0, 0, 100));
        lFPago.setText("Forma de Pago");
        lFPago.setName("lFPago"); // NOI18N

        lPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lPlazo.setText("   Plazo");
        lPlazo.setName("lPlazo"); // NOI18N

        lEstado.setForeground(new java.awt.Color(0, 0, 100));
        lEstado.setText("   Estado");
        lEstado.setName("lEstado"); // NOI18N

        jComboBoxEstado.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxEstado.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        jComboBoxEstado.setName("jComboBoxEstado"); // NOI18N

        lFactura.setForeground(new java.awt.Color(0, 0, 100));
        lFactura.setText("Fecha Alta Cliente");
        lFactura.setName("lFactura"); // NOI18N

        lDiasPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lDiasPlazo.setText("Días");
        lDiasPlazo.setName("lDiasPlazo"); // NOI18N

        jTextDiasPlazo.setEnabled(false);
        jTextDiasPlazo.setName("jTextDiasPlazo"); // NOI18N
        jTextDiasPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiasPlazoActionPerformed(evt);
            }
        });

        jTextTelefono2.setMinimumSize(new java.awt.Dimension(9, 9));
        jTextTelefono2.setName("jTextTelefono2"); // NOI18N

        lTelefono2.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono2.setText("   Teléfono2");
        lTelefono2.setName("lTelefono2"); // NOI18N

        jSeparator8.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator8.setForeground(new java.awt.Color(0, 102, 51));
        jSeparator8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 53), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jSeparator8.setName("jSeparator8"); // NOI18N
        jSeparator8.setOpaque(true);
        jSeparator8.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSEspeciales))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDireccion1)
                            .addComponent(lPoblacionFiscal))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDireccionFiscal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                            .addComponent(jTextPoblacionFiscal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lProvinciaFiscal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxProvinciaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                    .addComponent(lPContacto1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE))
                    .addComponent(lPContacto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lPoblacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lTelefono)
                                .addGap(693, 693, 693))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lWeb))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(lEmail)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(249, 249, 249))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDateChooserAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lPlazo)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lProvincia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lCodPostal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(268, 268, 268)
                                        .addComponent(lFax)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                        .addComponent(jToggleButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxCorreo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jComboBoxPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lDiasPlazo)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lFPago)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jComboBoxFPago, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                                        .addComponent(lNumCuenta))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jComboBoxEstado, 0, 153, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lTipo)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lTarifa)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jComboBoxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(10, 10, 10)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jTextNumIban, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lFactura)
                                                .addGap(130, 130, 130))))))
                            .addComponent(jComboBoxComercial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxComercial, jComboBoxProvincia});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextEntidad, jTextNumIban});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextTelefono, jTextTelefono2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDNI)
                    .addComponent(jLabel2)
                    .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre)
                    .addComponent(jLabelO)
                    .addComponent(lNumero))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(lDireccion)
                    .addComponent(lCodPostal)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lPoblacion)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProvincia)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lTelefono)
                        .addComponent(jLabel5)
                        .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxCorreo)
                        .addComponent(jTextAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lEmail)
                        .addComponent(lFax)
                        .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lTelefono2)
                        .addComponent(jTextWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lWeb)
                        .addComponent(jTextTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lComercial)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lDiasPlazo)
                        .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lPlazo)
                        .addComponent(jComboBoxFPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lFPago))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextNumIban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lNumCuenta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lEstado)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lTipo)
                        .addComponent(lFactura)
                        .addComponent(jLabel11)
                        .addComponent(jComboBoxTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lTarifa))
                    .addComponent(jDateChooserAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButtonSEspeciales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lPContacto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion1)
                    .addComponent(lCodPostalFiscal)
                    .addComponent(jTextDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProvinciaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPoblacionFiscal)
                    .addComponent(lProvinciaFiscal)
                    .addComponent(jTextPoblacionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lPContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonCancelar1)
                    .addComponent(Eliminar)
                    .addComponent(jLabel1))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        int confirmado = JOptionPane.showConfirmDialog(this,"¿Estas seguro que quieres eliminar el cliente?");

        if (JOptionPane.OK_OPTION == confirmado) {
            int cl_id=Integer.parseInt(jTextNumero.getText());
            String query = "DELETE from cl_clientes where cl_id="+cl_id;
            //String query="UPDATE cl_clientes SET cl_estado='Inactivo' where cl_id='"+cl_id+"'";

            boolean rs = CSDesktop.datos.manipuladorDatos(query);
            if(rs)
            {
                jButtonModificar.setEnabled(false);
                JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al borrar el cliente de la base de datos</FONT></HTML>");
                JOptionPane.showMessageDialog(null,errorFields);
                jButtonModificar.setEnabled(true);
            } 
            else
            {
                jButtonModificar.setEnabled(false);
                JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>El cliente ha sido borrado correctamente.</FONT></HTML>");
                JOptionPane.showMessageDialog(null,mensaje);
                jButtonModificar.setEnabled(true);
                CSDesktop.EditarClienteNew.dispose();
                //CSDesktop.ResultCliente.dispose();
                CSDesktop.menuBuscarCliente.setEnabled(true);
            }
        }
}//GEN-LAST:event_EliminarActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        {
            CSDesktop.EditarClienteNew.dispose();
            CSDesktop.ResultCliente.setVisible(true);
        }
}//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        System.out.println("\nBoton Guardar de Añadir Clientes.");

        int confirmado = JOptionPane.showConfirmDialog(this,"¿Estas seguro que quieres modificar el cliente?");

        if (JOptionPane.OK_OPTION == confirmado) {
            String fecha2="";
            String numCuenta = "";
            String numero = new String(jTextNumero.getText());
            String nombre = new String(jTextNombre.getText());
            String dni = new String(jTextDNI.getText());
            String direccion = new String(jTextDireccion.getText());
            String codPostal = new String(jTextCodPostal.getText());
            String poblacion = new String(jTextPoblacion.getText());
            String provincia = new String(jComboBoxProvincia.getSelectedItem().toString());
            String telefono = new String(jTextTelefono.getText());
            String telefono2 = new String(jTextTelefono2.getText());
            String fax = new String(jTextFax.getText());
            String att = new String(jTextAtt.getText());
            String iban = "";
            String numIban = jTextNumIban.getText();
            String entidad = new String(jTextEntidad.getText());
            String sucursal = new String(jTextSucursal.getText());
            String digito = new String(jTextDigito.getText());

            if (!entidad.equals(""))
            {
                iban = new String(numIban+"/"+entidad+"/"+sucursal+"/"+digito+"/"+jTextNumCuenta.getText());
            }

            String web = new String(jTextWeb.getText());
            String plazo = new String(jComboBoxPlazo.getSelectedItem().toString());
            String diasPlazo = new String(jTextDiasPlazo.getText().toString());
            String fPago = new String(Integer.valueOf(jComboBoxFPago.getSelectedIndex()+1).toString());
            String estado = new String(jComboBoxEstado.getSelectedItem().toString());
            String co_id = new String(Integer.valueOf(jComboBoxComercial.getSelectedIndex()+1).toString());
            String direccionFiscal = new String(jTextDireccionFiscal.getText());
            String poblacionFiscal = new String(jTextPoblacionFiscal.getText());
            String provinciaFiscal = new String(jComboBoxProvinciaFiscal.getSelectedItem().toString());
            String codPostalFiscal = new String(jTextCodPostalFiscal.getText());
            String tipoTarifa = new String(jComboBoxTarifa.getSelectedItem().toString());
            String tipoCliente = new String(jComboBoxTipo.getSelectedItem().toString());
            Calendar fechaCalendar = jDateChooserAlta.getCalendar();

            if (fechaCalendar!=null)
            {
                Date fecha = fechaCalendar.getTime();
                SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
                fecha2=formatoDeFecha.format(fecha);
            }

            boolean correo = new Boolean(jCheckBoxCorreo.isSelected());
            int iCorreo = 0;
            if (correo)
            {
                iCorreo = 1;
            }

            if (!Utilidades.campoObligatorio(nombre,"nombre").equals("OK")) {
                ValidarFormatos(Utilidades.campoObligatorio(nombre,"nombre"));
            } else if (!Utilidades.campoObligatorio(dni,"DNI").equals("OK")) {
                ValidarFormatos(Utilidades.campoObligatorio(dni,"DNI"));
            } else if (!Utilidades.campoObligatorio(telefono,"telefono").equals("OK")) {
                ValidarFormatos(Utilidades.campoObligatorio(telefono,"telefono"));
            } else if (!Utilidades.campoObligatorioCombo(provincia,"Provincia").equals("OK")){
                ValidarFormatos(Utilidades.campoObligatorioCombo(provincia,"Provincia"));
            }else if(!Utilidades.formatoCodPostal(codPostal).equals("OK")) {
                ValidarFormatos(Utilidades.formatoCodPostal(codPostal));
            }else if(!Utilidades.formatoCodPostal(codPostalFiscal).equals("OK")) {
                ValidarFormatos(Utilidades.formatoCodPostal(codPostalFiscal));
            } else if(!Utilidades.formatoTelefono9(telefono).equals("OK")) {
                ValidarFormatos(Utilidades.formatoTelefono9(telefono));
            } else if(!Utilidades.formatoTelefono9(telefono2).equals("OK")) {
                ValidarFormatos(Utilidades.formatoTelefono9(telefono2));
            } else if(!Utilidades.formatoFax(fax).equals("OK")) {
                ValidarFormatos(Utilidades.formatoFax(fax));
            }else if(!Utilidades.formatoNumerico(diasPlazo).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoNumerico(diasPlazo));
            } else {

                String query = "UPDATE cl_clientes SET cl_fecha ='"+fecha2+"', cl_nombre='"+nombre+"',cl_DNI_CIF='"+dni+"', " +
                               "cl_direccion='"+direccion+"',cl_cod_postal='"+codPostal+"', cl_poblacion='"+poblacion+"', " +
                               "cl_provincia='"+provincia+"', cl_direccion_fiscal = '"+direccionFiscal+"', " +
                               "cl_cod_postal_fiscal='"+codPostalFiscal+"', cl_poblacion_fiscal= '"+poblacionFiscal+"', " +
                               "cl_provincia_fiscal='"+provinciaFiscal+"', cl_telefono='"+telefono+"',cl_telefono2='"+telefono2+"', " +
                               "cl_fax='"+fax+"',cl_email='"+att+"', cl_web='"+web+"',cl_plazo='"+plazo+"', cl_tarifa_url = '"+urlTarifas+"', " +
                               "cl_dias_plazo='"+diasPlazo+"',fp_id='"+fPago+"', cl_num_cuenta='"+iban+"', cl_estado='"+estado+"', " +
                               "co_id='"+co_id+"', cl_tipo_tarifa='"+tipoTarifa+"', cl_tipo='"+tipoCliente+"' , cl_correo='"+iCorreo+"' " +
                               "WHERE cl_id='"+numero+"'";

                System.out.println(query);
                boolean rs = CSDesktop.datos.manipuladorDatos(query);
                System.out.println(rs);
                if(rs) {
                    jButtonModificar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonModificar.setEnabled(true);
                } else {
                    jButtonModificar.setEnabled(false);
                    JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>Los datos se han guardado correctamente.</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,mensaje);
                    jButtonModificar.setEnabled(true);
                    //cerramos la conexión antes de cerrar la ventana
                    CSDesktop.EditarClienteNew.dispose();
                    //CSDesktop.ResultCliente.dispose();
                    CSDesktop.menuBuscarCliente.setEnabled(true);
                }
        }
        }
}//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonSEspecialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSEspecialesActionPerformed
        try {
            int cl_id = new Integer(Integer.parseInt(jTextNumero.getText()));
            String querySE = "SELECT * FROM sv_servicios WHERE cl_id = '"+cl_id+"'";
            CSServicioClienteNew serviciosCliente = new CSServicioClienteNew(querySE, cl_id);
            CSDesktop.EditarClienteNew.setVisible(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(CSEditarClienteNew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSEspecialesActionPerformed

    private void jTextPoblacionFiscalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionFiscalFocusLost
        String PoblacionFiscalConM = jTextPoblacionFiscal.getText().toUpperCase();
        jTextPoblacionFiscal.setText(PoblacionFiscalConM);
}//GEN-LAST:event_jTextPoblacionFiscalFocusLost

    private void jTextDireccionFiscalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionFiscalFocusLost
        String DireccionFiscalConM = jTextDireccionFiscal.getText().toUpperCase();
        jTextDireccionFiscal.setText(DireccionFiscalConM);
}//GEN-LAST:event_jTextDireccionFiscalFocusLost

    private void jComboBoxPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlazoActionPerformed
        if (jComboBoxPlazo.getSelectedItem().equals("Especial")) {
            jTextDiasPlazo.setEnabled(true);
        } else {
            jTextDiasPlazo.setEnabled(false);
        }
}//GEN-LAST:event_jComboBoxPlazoActionPerformed

    private void jTextNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreFocusLost
        String nombreM = jTextNombre.getText().toUpperCase();
        jTextNombre.setText(nombreM);
    }//GEN-LAST:event_jTextNombreFocusLost

    private void jCheckBoxCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCorreoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCheckBoxCorreoActionPerformed

    private void jTextEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEntidadActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextEntidadActionPerformed

    private void jComboBoxComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxComercialActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxComercialActionPerformed

    private void jTextDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDNIFocusLost
        String DNIM = jTextDNI.getText().toUpperCase();
        jTextDNI.setText(DNIM);
}//GEN-LAST:event_jTextDNIFocusLost

    private void jTextDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionFocusLost
        String DireccionM = jTextDireccion.getText().toUpperCase();
        jTextDireccion.setText(DireccionM);
}//GEN-LAST:event_jTextDireccionFocusLost

    private void jTextPoblacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionFocusLost
        String PoblacionM = jTextPoblacion.getText().toUpperCase();
        jTextPoblacion.setText(PoblacionM);
}//GEN-LAST:event_jTextPoblacionFocusLost

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        FileChooser utilFc = new FileChooser();
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        urlTarifas = utilFc.editTarifasUrl(urlTarifas);

}//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextWebFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextWebFocusLost
        String WebM = jTextWeb.getText().toUpperCase();
        jTextWeb.setText(WebM);
}//GEN-LAST:event_jTextWebFocusLost

    private void jTextAttFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAttFocusLost
        String MailM = jTextAtt.getText().toUpperCase();
        jTextAtt.setText(MailM);
}//GEN-LAST:event_jTextAttFocusLost

    private void jTextNumIbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumIbanActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextNumIbanActionPerformed

    private void jComboBoxFPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFPagoActionPerformed
        if (jComboBoxFPago.getSelectedItem().equals("Recibo Domiciliado")) {
            jTextNumIban.setEnabled(true);
            jTextDigito.setEnabled(true);
            jTextEntidad.setEnabled(true);
            jTextSucursal.setEnabled(true);
            jTextNumCuenta.setEnabled(true);
        } else {
            jTextNumIban.setEnabled(false);
            jTextDigito.setEnabled(false);
            jTextEntidad.setEnabled(false);
            jTextSucursal.setEnabled(false);
            jTextNumCuenta.setEnabled(false);
        }
}//GEN-LAST:event_jComboBoxFPagoActionPerformed

    private void jTextDiasPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiasPlazoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextDiasPlazoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonSEspeciales;
    private javax.swing.JCheckBox jCheckBoxCorreo;
    private javax.swing.JComboBox jComboBoxComercial;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxFPago;
    private javax.swing.JComboBox jComboBoxPlazo;
    private javax.swing.JComboBox jComboBoxProvincia;
    private javax.swing.JComboBox jComboBoxProvinciaFiscal;
    private javax.swing.JComboBox jComboBoxTarifa;
    private javax.swing.JComboBox jComboBoxTipo;
    private com.toedter.calendar.JDateChooser jDateChooserAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextAtt;
    private javax.swing.JTextField jTextCodPostal;
    private javax.swing.JTextField jTextCodPostalFiscal;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextDiasPlazo;
    private javax.swing.JTextField jTextDigito;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextDireccionFiscal;
    private javax.swing.JTextField jTextEntidad;
    private javax.swing.JTextField jTextFax;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumCuenta;
    private javax.swing.JTextField jTextNumIban;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPoblacion;
    private javax.swing.JTextField jTextPoblacionFiscal;
    private javax.swing.JTextField jTextSucursal;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jTextTelefono2;
    private javax.swing.JTextField jTextWeb;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lCodPostal;
    private javax.swing.JLabel lCodPostalFiscal;
    private javax.swing.JLabel lComercial;
    private javax.swing.JLabel lDNI;
    private javax.swing.JLabel lDiasPlazo;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lDireccion1;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lFPago;
    private javax.swing.JLabel lFactura;
    private javax.swing.JLabel lFax;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNumCuenta;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lPContacto;
    private javax.swing.JLabel lPContacto1;
    private javax.swing.JLabel lPlazo;
    private javax.swing.JLabel lPoblacion;
    private javax.swing.JLabel lPoblacionFiscal;
    private javax.swing.JLabel lProvincia;
    private javax.swing.JLabel lProvinciaFiscal;
    private javax.swing.JLabel lTarifa;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel lTelefono2;
    private javax.swing.JLabel lTipo;
    private javax.swing.JLabel lWeb;
    private javax.swing.JTable tablaContactos;
    // End of variables declaration//GEN-END:variables

    public Dimension getPreferredSize()
    {
      return new Dimension( 856,625 );
    }

    /**
     * Función para sacar todos los datos del cliente de la bd
     * @param cliente
     * @return
     * @throws SQLException
     */
    public void datosCliente(int cliente)
    {
    	String query = "SELECT * FROM cl_clientes c WHERE cl_id = "+cliente;

        ResultSet rs = CSDesktop.datos.select(query+" ORDER BY cl_nombre DESC");
        int numeroFila = 0;
        String cl_id="";

        try
        {
            while(rs.next())
            {
                cl_id=rs.getString("cl_id");
                jTextNumero.setText(rs.getString("cl_id"));

                String fecha = rs.getString("cl_fecha");               
                String [] temp = null;
                    temp = fecha.split("\\-");
                    String anyo=temp[0];
                    String mes=temp[1];
                    String dia=temp[2];
                    String nueva=dia+"-"+mes+"-"+anyo;
                SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy");
                Date d=sdf.parse(nueva);
                jDateChooserAlta.setDate(d);

                jTextNombre.setText(rs.getString("cl_nombre"));
                jTextDNI.setText(rs.getString("cl_DNI_CIF"));
                jTextDireccion.setText(rs.getString("cl_direccion"));
                jTextCodPostal.setText(rs.getString("cl_cod_postal"));
                jTextPoblacion.setText(rs.getString("cl_poblacion"));
                jComboBoxProvincia.setSelectedItem(rs.getString("cl_provincia"));
                jTextDireccionFiscal.setText(rs.getString("cl_direccion_fiscal"));
                jTextCodPostalFiscal.setText(rs.getString("cl_cod_postal_fiscal"));
                jTextPoblacionFiscal.setText(rs.getString("cl_poblacion_fiscal"));
                jComboBoxProvinciaFiscal.setSelectedItem(rs.getString("cl_provincia_fiscal"));
                jTextTelefono.setText(rs.getString("cl_telefono"));
                jTextTelefono2.setText(rs.getString("cl_telefono2"));
                jTextFax.setText(rs.getString("cl_fax"));
                jTextAtt.setText(rs.getString("cl_email"));
                jTextWeb.setText(rs.getString("cl_web"));
                jComboBoxPlazo.setSelectedItem(rs.getString("cl_plazo"));
                jTextDiasPlazo.setText(rs.getString("cl_dias_plazo"));
                jComboBoxFPago.setSelectedIndex(rs.getInt("fp_id")-1);
                String cuenta = rs.getString("cl_num_cuenta");
                if(!cuenta.equals(""))
                {
                    String [] tempN = null;
                    tempN = cuenta.split("\\/");
                    if(cuenta.length() ==23){
                        jTextEntidad.setText(tempN[0]);
                        jTextSucursal.setText(tempN[1]);
                        jTextDigito.setText(tempN[2]);
                        jTextNumCuenta.setText(tempN[3]);
                    }else{
                        jTextNumIban.setText(tempN[0]);
                        jTextEntidad.setText(tempN[1]);
                        jTextSucursal.setText(tempN[2]);
                        jTextDigito.setText(tempN[3]);
                        jTextNumCuenta.setText(tempN[4]);
                    }
                }
                jComboBoxComercial.setSelectedIndex(rs.getInt("co_id")-1);
                jComboBoxEstado.setSelectedItem(rs.getString("cl_estado"));
                jComboBoxTarifa.setSelectedIndex(rs.getInt("cl_tipo_tarifa")-1);
                jComboBoxTipo.setSelectedItem(rs.getString("cl_tipo"));
                boolean vCorreo = false;
                if (rs.getInt("cl_correo") == 1)
                {
                    vCorreo = true;
                }
                jCheckBoxCorreo.setSelected(vCorreo);
                urlTarifas = rs.getString("cl_tarifa_url");
                numeroFila++;
            }
            rs.close();

        } catch (Exception ex){
            ex.printStackTrace();
        }

        if (numeroFila == 0)
        {
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>No se han encontrado Clientes, con los parámetros de búsqueda seleccionados.</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields);
        }
    }

    public void ValidarFormatos(String accion)
    {
         jButtonModificar.setEnabled(false);
         JLabel errorFields = new JLabel(accion);
         JOptionPane.showMessageDialog(null,errorFields);
         jButtonModificar.setEnabled(true);
    }

    /**
     * Función para rellenar el select de forma de pago
     * @throws SQLException
     */
    private void getFPagoClientes() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT fp_id, fp_tipo FROM fp_forma_pago");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("fp_tipo");

            jComboBoxFPago.addItem(valor);
            //jComboBoxFPago.setSelectedIndex(index);
            j++;
        }
     }

    /**
     * Función para mostrar los contactos de un cliente
     * @param cliente
     */
    public void ABResultBuscarContactos(int cliente)
    {
        TablaModelo modelo = new TablaModelo();
        String queryCont = "SELECT * FROM cc_contactos_cliente WHERE cl_id = '"+cliente+"'";
        ResultSet rs = CSDesktop.datos.select(queryCont);

        modelo.setColumnIdentifiers(new String[] {"NUM","NOMBRE", "TELEFONO", "MAIL"});

        int numeroFila = 0;
        try
        {
            while (rs.next())
            {
                Object[] datosFila = new Object[modelo.getColumnCount()];
                int j = 0;
                for (int k = 0; k < 10; k++)
                {
                    if (k == 0 || k == 1 || k == 2 || k == 4)
                    {
                        datosFila[j] = rs.getObject(k + 1);
                        System.out.println("Dato" + k + " " + rs.getObject(k + 1));
                        j++;
                    }
                    else
                    {
                        //datosFila[k] = rs.getObject(k + 1);
                        //System.out.println("No Dato"+k+" "+rs.getObject(k + 1));
                    }
                }
                modelo.addRow(datosFila);
                numeroFila++;
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(CSResultBuscarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
         if (numeroFila == 0)
        {
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>No se han encontrado contactos de este Cliente con los parámetros de búsqueda seleccionados.</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields);
        }       
        //initComponents();
        tablaContactos.setModel(modelo);
        TableColumn columna = tablaContactos.getColumnModel().getColumn(0);
        columna.setPreferredWidth(50);
        TableColumn columna1 = tablaContactos.getColumnModel().getColumn(1);
        columna1.setPreferredWidth(300);
        TableColumn columna2 = tablaContactos.getColumnModel().getColumn(2);
        columna2.setPreferredWidth(100);
        TableColumn columna3 = tablaContactos.getColumnModel().getColumn(3);
        columna3.setPreferredWidth(250);

        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        tablaContactos.getColumnModel().getColumn(0).setCellRenderer(tcr);
        tablaContactos.getColumnModel().getColumn(2).setCellRenderer(tcr);

        tablaContactos.addMouseListener(new MouseAdapter()
        {
        public void mouseClicked(MouseEvent e)
        {
            int fila = tablaContactos.rowAtPoint(e.getPoint());
            int columna = tablaContactos.columnAtPoint(e.getPoint());

            if ((fila > -1) && (columna > -1))
            {
               int id_contacto = Integer.parseInt((String)tablaContactos.getValueAt(fila,0).toString());
               CSDesktop.EditarContactoCliente = new JInternalFrame("Editar contacto Cliente", true, false, false, true );
               // adjuntar panel al panel de contenido del marco interno
               CSEditarContactoCliente editarCC = null;
                    try {
                        editarCC = new CSEditarContactoCliente(id_contacto);
                    } catch (SQLException ex) {
                        Logger.getLogger(CSEditarClienteNew.class.getName()).log(Level.SEVERE, null, ex);
                    }
               CSDesktop.EditarContactoCliente.getContentPane().add( editarCC,BorderLayout.CENTER);
               // establecer tama�o de marco interno en el tama�o de su contenido
               CSDesktop.EditarContactoCliente.pack();
               // adjuntar marco interno al escritorio y mostrarlo
               CSDesktop.elEscritorio.add( CSDesktop.EditarContactoCliente );
               //ABDesktop.ResultCliente.dispose();
               Dimension pantalla = CSDesktop.elEscritorio.getSize();
               Dimension ventana = CSDesktop.EditarClienteNew.getSize();
               CSDesktop.EditarContactoCliente.setLocation(
                    (pantalla.width - ventana.width) / 2,
                    (pantalla.height - ventana.height) / 2);
               CSDesktop.EditarContactoCliente.setVisible( true );

            System.out.println(tablaContactos.getValueAt(fila,columna));
         }
        }
        }    );
    }

    /**
     * Función para sacar todos los comerciales de la base da datos
     * @throws SQLException
     */
    private void getComercial() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT co_id, co_nombre FROM co_comerciales");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("co_nombre");

            jComboBoxComercial.addItem(valor);
            jComboBoxComercial.setSelectedIndex(0);

            j++;
        }
     }

    /**
     * Modificamos las tarifas del cliente si ha seleccionado un incremento
     * @param cliente
     * @param incremento
     */
    public void incrementarTarifas(String cliente, String incremento) throws UnknownHostException
    {
        String query = "SELECT * FROM tc_tarifas_clientes WHERE cl_id = '"+cliente+"' AND tc_fecha_hasta = '2050-01-01'";

        ResultSet rs = CSDesktop.datos.select(query);
        try {
            DbConnection da = new DbConnection();
            while (rs.next())
            {
                   boolean rsTc = true;
                   int tc_id = rs.getInt("tc_id");
                   String tarifa =  rs.getString("tc_tarifa");
                   double tarifaN = Double.valueOf(tarifa).doubleValue();
                   double incrementoN = Double.valueOf(incremento).doubleValue();
                   tarifaN = tarifaN + ((tarifaN * incrementoN) / 100.0);

                   String queryTc = "UPDATE tc_tarifas_clientes SET tc_incremento='"+incremento+"', tc_tarifa="+tarifaN+
                                    " WHERE tc_id = '"+tc_id+"'";
                           
                   System.out.println(queryTc);
                   rsTc = da.manipuladorDatos(queryTc);
                   if(rsTc)
                   {
                        jButtonModificar.setEnabled(false);
                        JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al modificar las tarifas en la base de datos</FONT></HTML>");
                        JOptionPane.showMessageDialog(null,errorFields);
                        jButtonModificar.setEnabled(true);
                   }
             
            }
            da.cerrarConexion();
            rs.close();
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(CSEditarClienteNew.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

     private void limitacionesCampos()
    {
         LimitadorDeDocumento limitadorNombre= new LimitadorDeDocumento(50);
        jTextNombre.setDocument(limitadorNombre);
        LimitadorDeDocumento limitadorDNI= new LimitadorDeDocumento(10);
        jTextDNI.setDocument(limitadorDNI);
        LimitadorDeDocumento limitadorDireccion = new LimitadorDeDocumento(255);
        jTextDireccion.setDocument(limitadorDireccion);
        LimitadorDeDocumento limitador5= new LimitadorDeDocumento(5);
        jTextCodPostal.setDocument(limitador5);
        LimitadorDeDocumento limitadorCPFiscal= new LimitadorDeDocumento(5);
        jTextCodPostalFiscal.setDocument(limitadorCPFiscal);
        LimitadorDeDocumento limitadorPoblacion= new LimitadorDeDocumento(80);
        jTextPoblacion.setDocument(limitadorPoblacion);
        LimitadorDeDocumento limitadorPoblacionFiscal= new LimitadorDeDocumento(80);
        jTextPoblacionFiscal.setDocument(limitadorPoblacionFiscal);
        LimitadorDeDocumento limitadorTelefono= new LimitadorDeDocumento(9);
        jTextTelefono.setDocument(limitadorTelefono);
        LimitadorDeDocumento limitadorTelefono2= new LimitadorDeDocumento(9);
        jTextTelefono2.setDocument(limitadorTelefono2);
        LimitadorDeDocumento limitadorFax= new LimitadorDeDocumento(9);
        jTextFax.setDocument(limitadorFax);
        LimitadorDeDocumento limitadorWeb= new LimitadorDeDocumento(50);
        jTextWeb.setDocument(limitadorWeb);
        LimitadorDeDocumento limitadorEntidad= new LimitadorDeDocumento(4);
        jTextEntidad.setDocument(limitadorEntidad);
        LimitadorDeDocumento limitadorSucursal= new LimitadorDeDocumento(4);
        jTextSucursal.setDocument(limitadorSucursal);
        LimitadorDeDocumento limitadorDigito= new LimitadorDeDocumento(2);
        jTextDigito.setDocument(limitadorDigito);
        LimitadorDeDocumento limitadorNumC= new LimitadorDeDocumento(10);
        jTextNumCuenta.setDocument(limitadorNumC);
        LimitadorDeDocumento limitadorNumIban= new LimitadorDeDocumento(4);
        jTextNumIban.setDocument(limitadorNumIban);
    }

}