/*
 * ABEditarProveedores.java
 *
 * Created on 07-oct-2009, 12:40:18
 */

package neg;
import java.net.UnknownHostException;
import utils.Utilidades;
import utils.TablaModelo;
import utils.LimitadorDeDocumento;
import data.DbConnection;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import utils.FileChooser;

/**
 *
 * @author lito
 */
public class CSEditarProveedorNew extends javax.swing.JPanel
{
    int proveedor;
    public static String urlTarifas = "";
    /** Creates new form ABEditarProveedores */
    public CSEditarProveedorNew(int proveedor) throws SQLException
    {
        initComponents();
        limitacionesCampos();
        getFPagoProveedores();
        this.datosProveedor(proveedor);
        this.ABResultBuscarContactos(proveedor);

        KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonModificar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };

        for (int k = 0; k < this.getComponents().length; k ++)
        {
            if (this.getComponents()[k] != jComboBoxEstado &&
                this.getComponents()[k] != jComboBoxFPago &&
                this.getComponents()[k] != jComboBoxPlazo &&
                this.getComponents()[k] != jComboBoxDiaFactura &&
                this.getComponents()[k] != jComboBoxRegimen &&
                this.getComponents()[k] != jComboBoxTipo &&
                this.getComponents()[k] != jComboBoxProvinciaFiscal &&
                this.getComponents()[k] != jComboBoxProvincia)
            {
                this.getComponents()[k].addKeyListener(l);
            }
        }
        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonModificar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        lPContacto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContactos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lCodPostal = new javax.swing.JLabel();
        jTextCodPostal = new javax.swing.JTextField();
        jComboBoxDiaFactura = new javax.swing.JComboBox();
        lFactura = new javax.swing.JLabel();
        jTextDiasPlazo = new javax.swing.JTextField();
        lFPago = new javax.swing.JLabel();
        lDiasPlazo = new javax.swing.JLabel();
        jComboBoxFPago = new javax.swing.JComboBox();
        lDireccion = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        lTipo = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        lDNI = new javax.swing.JLabel();
        jTextDNI = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lRegimen = new javax.swing.JLabel();
        jComboBoxRegimen = new javax.swing.JComboBox();
        jComboBoxTipo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lPoblacion = new javax.swing.JLabel();
        jTextDigito = new javax.swing.JTextField();
        lPlazo = new javax.swing.JLabel();
        jTextSucursal = new javax.swing.JTextField();
        lEstado = new javax.swing.JLabel();
        jTextTelefono2 = new javax.swing.JTextField();
        lTelefono2 = new javax.swing.JLabel();
        jComboBoxPlazo = new javax.swing.JComboBox();
        jComboBoxEstado = new javax.swing.JComboBox();
        jTextEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextNumCuenta = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        lFax = new javax.swing.JLabel();
        jTextFax = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        jTextPoblacion = new javax.swing.JTextField();
        lProvincia = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        jTextEntidad = new javax.swing.JTextField();
        jComboBoxProvincia = new javax.swing.JComboBox();
        lFactura1 = new javax.swing.JLabel();
        jDateChooserAlta = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lCodPostalFiscal = new javax.swing.JLabel();
        jTextCodPostalFiscal = new javax.swing.JTextField();
        lDireccion1 = new javax.swing.JLabel();
        lPContacto1 = new javax.swing.JLabel();
        lPoblacionFiscal = new javax.swing.JLabel();
        jTextDireccionFiscal = new javax.swing.JTextField();
        lProvinciaFiscal = new javax.swing.JLabel();
        jTextPoblacionFiscal = new javax.swing.JTextField();
        jComboBoxProvinciaFiscal = new javax.swing.JComboBox();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator8 = new javax.swing.JSeparator();
        lNumCuenta = new javax.swing.JLabel();
        jTextNumIban = new javax.swing.JTextField();

        jButtonModificar.setText("Modificar");
        jButtonModificar.setName("jButtonModificar"); // NOI18N
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.setName("jButtonEliminar"); // NOI18N
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        lPContacto.setFont(new java.awt.Font("Tahoma", 1, 11));
        lPContacto.setForeground(new java.awt.Color(170, 16, 4));
        lPContacto.setText("PERSONA DE CONTACTO");
        lPContacto.setName("lPContacto"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablaContactos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaContactos.setName("tablaContactos"); // NOI18N
        jScrollPane1.setViewportView(tablaContactos);

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("* Campos obligatorios");
        jLabel1.setName("jLabel1"); // NOI18N

        lCodPostal.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostal.setText("Cód. Postal");
        lCodPostal.setName("lCodPostal"); // NOI18N

        jTextCodPostal.setName("jTextCodPostal"); // NOI18N

        jComboBoxDiaFactura.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxDiaFactura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jComboBoxDiaFactura.setName("jComboBoxDiaFactura"); // NOI18N
        jComboBoxDiaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaFacturaActionPerformed(evt);
            }
        });

        lFactura.setForeground(new java.awt.Color(0, 0, 100));
        lFactura.setText("Día del mes para facturar");
        lFactura.setName("lFactura"); // NOI18N

        jTextDiasPlazo.setEnabled(false);
        jTextDiasPlazo.setName("jTextDiasPlazo"); // NOI18N

        lFPago.setForeground(new java.awt.Color(0, 0, 100));
        lFPago.setText("Forma de Pago");
        lFPago.setName("lFPago"); // NOI18N

        lDiasPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lDiasPlazo.setText("Días");
        lDiasPlazo.setName("lDiasPlazo"); // NOI18N

        jComboBoxFPago.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxFPago.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxFPago.setName("jComboBoxFPago"); // NOI18N
        jComboBoxFPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFPagoActionPerformed(evt);
            }
        });

        lDireccion.setForeground(new java.awt.Color(0, 0, 100));
        lDireccion.setText("Dirección");
        lDireccion.setName("lDireccion"); // NOI18N

        jTextDireccion.setName("jTextDireccion"); // NOI18N
        jTextDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionFocusLost(evt);
            }
        });

        lTipo.setForeground(new java.awt.Color(0, 0, 100));
        lTipo.setText("Tipo");
        lTipo.setName("lTipo"); // NOI18N

        jTextNombre.setName("jTextNombre"); // NOI18N
        jTextNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreFocusLost(evt);
            }
        });

        lDNI.setForeground(new java.awt.Color(0, 0, 100));
        lDNI.setText("DNI/NIF");
        lDNI.setName("lDNI"); // NOI18N

        jTextDNI.setName("jTextDNI"); // NOI18N
        jTextDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDNIFocusLost(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("*");
        jLabel10.setName("jLabel10"); // NOI18N

        lRegimen.setForeground(new java.awt.Color(0, 0, 100));
        lRegimen.setText("Régimen");
        lRegimen.setName("lRegimen"); // NOI18N

        jComboBoxRegimen.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxRegimen.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxRegimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empresa", "Autónomo", "Otros" }));
        jComboBoxRegimen.setName("jComboBoxRegimen"); // NOI18N

        jComboBoxTipo.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxTipo.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Provincial", "Larga Distancia", "Otros" }));
        jComboBoxTipo.setName("jComboBoxTipo"); // NOI18N

        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("*");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("*");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("*");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("*");
        jLabel13.setName("jLabel13"); // NOI18N

        lNombre.setForeground(new java.awt.Color(0, 0, 100));
        lNombre.setText("Nombre");
        lNombre.setName("lNombre"); // NOI18N

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("*");
        jLabel16.setName("jLabel16"); // NOI18N

        lPoblacion.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacion.setText("Población");
        lPoblacion.setName("lPoblacion"); // NOI18N

        jTextDigito.setEnabled(false);
        jTextDigito.setName("jTextDigito"); // NOI18N

        lPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lPlazo.setText("    Plazo");
        lPlazo.setName("lPlazo"); // NOI18N

        jTextSucursal.setEnabled(false);
        jTextSucursal.setName("jTextSucursal"); // NOI18N

        lEstado.setForeground(new java.awt.Color(0, 0, 100));
        lEstado.setText("    Estado");
        lEstado.setName("lEstado"); // NOI18N

        jTextTelefono2.setName("jTextTelefono2"); // NOI18N

        lTelefono2.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono2.setText("Teléfono 2");
        lTelefono2.setName("lTelefono2"); // NOI18N

        jComboBoxPlazo.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxPlazo.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxPlazo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30 días FF", "15 días FF", "45 días FF", "60 días FF", "Especial" }));
        jComboBoxPlazo.setName("jComboBoxPlazo"); // NOI18N
        jComboBoxPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlazoActionPerformed(evt);
            }
        });

        jComboBoxEstado.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxEstado.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        jComboBoxEstado.setName("jComboBoxEstado"); // NOI18N

        jTextEmail.setName("jTextEmail"); // NOI18N
        jTextEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailFocusLost(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("*");
        jLabel18.setName("jLabel18"); // NOI18N

        jTextNumCuenta.setEnabled(false);
        jTextNumCuenta.setName("jTextNumCuenta"); // NOI18N

        jTextTelefono.setName("jTextTelefono"); // NOI18N

        lFax.setForeground(new java.awt.Color(0, 0, 100));
        lFax.setText("Fax");
        lFax.setName("lFax"); // NOI18N

        jTextFax.setName("jTextFax"); // NOI18N
        jTextFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFaxActionPerformed(evt);
            }
        });

        lEmail.setForeground(new java.awt.Color(0, 0, 100));
        lEmail.setText("Email");
        lEmail.setName("lEmail"); // NOI18N

        jTextPoblacion.setName("jTextPoblacion"); // NOI18N
        jTextPoblacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionFocusLost(evt);
            }
        });

        lProvincia.setForeground(new java.awt.Color(0, 0, 100));
        lProvincia.setText("Provincia");
        lProvincia.setName("lProvincia"); // NOI18N

        lTelefono.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono.setText("Teléfono");
        lTelefono.setName("lTelefono"); // NOI18N

        jTextNumero.setEditable(false);
        jTextNumero.setEnabled(false);
        jTextNumero.setName("jTextNumero"); // NOI18N

        lNumero.setForeground(new java.awt.Color(0, 0, 100));
        lNumero.setText("   Núm. Proveedor PR/");
        lNumero.setName("lNumero"); // NOI18N

        jTextEntidad.setEnabled(false);
        jTextEntidad.setName("jTextEntidad"); // NOI18N

        jComboBoxProvincia.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvincia.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvincia.setName("jComboBoxProvincia"); // NOI18N

        lFactura1.setForeground(new java.awt.Color(0, 0, 100));
        lFactura1.setText("Fecha Alta Proveedor");
        lFactura1.setName("lFactura1"); // NOI18N

        jDateChooserAlta.setDateFormatString("dd-MM-yyyy");
        jDateChooserAlta.setName("jDateChooserAlta"); // NOI18N

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("*");
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*");
        jLabel19.setName("jLabel19"); // NOI18N

        lCodPostalFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostalFiscal.setText("Código Postal");
        lCodPostalFiscal.setName("lCodPostalFiscal"); // NOI18N

        jTextCodPostalFiscal.setName("jTextCodPostalFiscal"); // NOI18N

        lDireccion1.setForeground(new java.awt.Color(0, 0, 100));
        lDireccion1.setText("  Dirección");
        lDireccion1.setName("lDireccion1"); // NOI18N

        lPContacto1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lPContacto1.setForeground(new java.awt.Color(170, 16, 4));
        lPContacto1.setText("DOMICILIO FISCAL");
        lPContacto1.setName("lPContacto1"); // NOI18N

        lPoblacionFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionFiscal.setText("  Población");
        lPoblacionFiscal.setName("lPoblacionFiscal"); // NOI18N

        jTextDireccionFiscal.setName("jTextDireccionFiscal"); // NOI18N
        jTextDireccionFiscal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionFiscalFocusLost(evt);
            }
        });

        lProvinciaFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaFiscal.setText("Provincia");
        lProvinciaFiscal.setName("lProvinciaFiscal"); // NOI18N

        jTextPoblacionFiscal.setName("jTextPoblacionFiscal"); // NOI18N
        jTextPoblacionFiscal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionFiscalFocusLost(evt);
            }
        });

        jComboBoxProvinciaFiscal.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaFiscal.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaFiscal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVEDRA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaFiscal.setName("jComboBoxProvinciaFiscal"); // NOI18N

        jSeparator4.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator4.setName("jSeparator4"); // NOI18N

        jSeparator5.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator5.setName("jSeparator5"); // NOI18N

        jToggleButton1.setText("Dir. Tarifas");
        jToggleButton1.setName("jToggleButton1"); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator8.setForeground(new java.awt.Color(0, 102, 51));
        jSeparator8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 53), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jSeparator8.setName("jSeparator8"); // NOI18N
        jSeparator8.setOpaque(true);
        jSeparator8.setPreferredSize(new java.awt.Dimension(5, 5));

        lNumCuenta.setForeground(new java.awt.Color(0, 0, 100));
        lNumCuenta.setText("IBAN");
        lNumCuenta.setName("lNumCuenta"); // NOI18N

        jTextNumIban.setEnabled(false);
        jTextNumIban.setName("jTextNumIban"); // NOI18N
        jTextNumIban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumIbanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lPContacto)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPContacto1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lPoblacionFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(lDireccion1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextDireccionFiscal)
                                    .addComponent(jTextPoblacionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(lProvinciaFiscal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextCodPostalFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                        .addGap(17, 17, 17))
                                    .addComponent(jComboBoxProvinciaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEstado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lRegimen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lPoblacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lTelefono))
                            .addComponent(lPlazo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDiasPlazo)
                                .addGap(20, 20, 20)
                                .addComponent(lFPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxFPago, 0, 193, Short.MAX_VALUE)
                                .addGap(13, 13, 13)
                                .addComponent(lNumCuenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNumIban, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTextDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lTelefono2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lFax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextPoblacion, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lProvincia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lFactura1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lFactura)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxDiaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextDireccionFiscal, jTextPoblacionFiscal});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextCodPostal, jTextCodPostalFiscal});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator4, jSeparator5, jSeparator8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumero)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDNI)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTipo)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(lRegimen)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPoblacion)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProvincia)
                    .addComponent(jLabel14)
                    .addComponent(lCodPostal)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefono2)
                    .addComponent(jTextTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFax)
                    .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEmail)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefono)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDiasPlazo)
                    .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFPago)
                    .addComponent(lPlazo)
                    .addComponent(jTextNumIban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumCuenta))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEstado)
                            .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lFactura1)
                                    .addComponent(jLabel18)))
                            .addComponent(jDateChooserAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lFactura)
                                .addComponent(jComboBoxDiaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButton1)))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lPContacto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lDireccion1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCodPostalFiscal)
                            .addComponent(jTextCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxProvinciaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lProvinciaFiscal)
                            .addComponent(lPoblacionFiscal)))
                    .addComponent(jTextDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jTextPoblacionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        
        System.out.println("\njButtonGuardar_actionPerformed(ActionEvent e) called.");

        String fecha2="";
        String numero = new String(jTextNumero.getText());
        String nombre = new String(jTextNombre.getText());
        String dni = new String(jTextDNI.getText());
        String regimen = new String(jComboBoxRegimen.getSelectedItem().toString());
        String tipo = new String(jComboBoxTipo.getSelectedItem().toString());
        String direccion = new String(jTextDireccion.getText());
        String codPostal = new String(jTextCodPostal.getText());
        String poblacion = new String(jTextPoblacion.getText());
        String provincia = new String(jComboBoxProvincia.getSelectedItem().toString());
        String telefono = new String(jTextTelefono.getText());
        String telefono2 = new String(jTextTelefono2.getText());
        String fax = new String(jTextFax.getText());
        String email = new String(jTextEmail.getText());
        String iban = "";
        String numIban = jTextNumIban.getText();
        String entidad = new String(jTextEntidad.getText());
        String sucursal = new String(jTextSucursal.getText());
        String digito = new String(jTextDigito.getText());

        if (!entidad.equals(""))
        {
            iban = new String(numIban+"/"+entidad+"/"+sucursal+"/"+digito+"/"+jTextNumCuenta.getText());
        }
        String plazo = new String(jComboBoxPlazo.getSelectedItem().toString());
        String diasPlazo = new String(jTextDiasPlazo.getText().toString());
        String fPago = new String(Integer.valueOf(jComboBoxFPago.getSelectedIndex()+1).toString());
        String estado = new String(jComboBoxEstado.getSelectedItem().toString());
        String diaFactura = new String(jComboBoxDiaFactura.getSelectedItem().toString());
        String direccionFiscal = new String(jTextDireccionFiscal.getText());
        String poblacionFiscal = new String(jTextPoblacionFiscal.getText());
        String provinciaFiscal = new String(jComboBoxProvinciaFiscal.getSelectedItem().toString());
        String codPostalFiscal = new String(jTextCodPostalFiscal.getText());

        Calendar fechaCalendar = jDateChooserAlta.getCalendar();

        if (fechaCalendar!=null)
        {
            Date fecha = fechaCalendar.getTime();
            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
            fecha2=formatoDeFecha.format(fecha);
         }

        if (!Utilidades.campoObligatorio(nombre,"nombre").equals("OK")) {
            ValidarFormatos(Utilidades.campoObligatorio(nombre,"nombre"));
        } else if (!Utilidades.campoObligatorio(dni,"DNI").equals("OK")) {
            ValidarFormatos(Utilidades.campoObligatorio(dni,"DNI"));
        } else if (!Utilidades.campoObligatorio(telefono,"telefono").equals("OK")) {
            ValidarFormatos(Utilidades.campoObligatorio(telefono,"telefono"));
        } else if (!Utilidades.campoObligatorioCombo(provincia,"Provincia").equals("OK")){
            ValidarFormatos(Utilidades.campoObligatorioCombo(provincia,"Provincia"));
        }else if(!Utilidades.formatoCodPostal(codPostalFiscal).equals("OK")) {
            ValidarFormatos(Utilidades.formatoCodPostal(codPostalFiscal));
        }else if(!Utilidades.formatoCodPostal(codPostal).equals("OK")) {
            ValidarFormatos(Utilidades.formatoCodPostal(codPostal));
        } else if(!Utilidades.formatoTelefono9(telefono).equals("OK")) {
            ValidarFormatos(Utilidades.formatoTelefono9(telefono));
        } else if(!Utilidades.formatoTelefono9(telefono2).equals("OK")) {
            ValidarFormatos(Utilidades.formatoTelefono9(telefono2));
        } else if(!Utilidades.formatoFax(fax).equals("OK")) {
            ValidarFormatos(Utilidades.formatoFax(fax));
        } else if(!Utilidades.formatoCorreo(email).equals("OK")) {
            ValidarFormatos(Utilidades.formatoCorreo(email));
        }else if(!Utilidades.formatoNumerico(diasPlazo).equals("OK"))
        {
            ValidarFormatos(Utilidades.formatoNumerico(diasPlazo));
        }
        else if(!Utilidades.formatoCodPostal(codPostalFiscal).equals("OK"))
        {
            ValidarFormatos(Utilidades.formatoCodPostal(codPostalFiscal));
        }
        else
        {
            String query = "UPDATE pr_proveedores SET pr_fecha ='"+fecha2+"', pr_nombre_fiscal = '"+nombre+"', " +
                           "pr_DNI_CIF = '"+dni+"', pr_regimen = '"+regimen+"', pr_tipo = '"+tipo+"', " +
                           "pr_direccion = '"+direccion+"', pr_cod_postal = '"+codPostal+"', pr_poblacion = '"+poblacion+"' , " +
                           "pr_provincia = '"+provincia+"', pr_direccion_fiscal = '"+direccionFiscal+"', " +
                           "pr_cod_postal_fiscal='"+codPostalFiscal+"', pr_poblacion_fiscal= '"+poblacionFiscal+"', " +
                           "pr_provincia_fiscal='"+provinciaFiscal+"', pr_telefono = '"+telefono+"', pr_telefono2='"+telefono2+"', " +
                           "pr_fax = '"+fax+"', pr_email = '"+email+"', pr_plazo = '"+plazo+"', pr_dias_plazo='"+diasPlazo+"', " +
                           "fp_id = '"+fPago+"', pr_num_cuenta = '"+iban+"', pr_estado = '"+estado+"', " +
                           "pr_dia_factura = '"+diaFactura+"', pr_tarifa_url = '"+urlTarifas+"'" +
                           "WHERE pr_id = "+numero+"";

            System.out.println(query);
            boolean rs = CSDesktop.datos.manipuladorDatos(query);
            System.out.println(rs);
            if(rs)
            {
                jButtonModificar.setEnabled(false);
                JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                JOptionPane.showMessageDialog(null,errorFields);
                jButtonModificar.setEnabled(true);
                //this.setVisible(true);
            } 
            else
            {
                jButtonModificar.setEnabled(false);
                JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>Los datos se han guardado correctamente.</FONT></HTML>");
                JOptionPane.showMessageDialog(null,mensaje);
                jButtonModificar.setEnabled(true);
                //Cerramos la conexión antes de cerrar la ventana
                CSDesktop.EditarProveedorNew.dispose();
                CSDesktop.ResultProveedor.dispose();
                CSDesktop.menuBuscarProveedor.setEnabled(true);
            }
        }
}//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        CSDesktop.EditarProveedorNew.dispose();
        CSDesktop.ResultProveedor.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int confirmado = JOptionPane.showConfirmDialog(this,"¿Estas seguro que quieres eliminar el proveedor?");

        if (JOptionPane.OK_OPTION == confirmado)
        {
            int pr_id = Integer.parseInt(jTextNumero.getText());
            String query="DELETE from pr_proveedores where pr_id="+pr_id;
            //String query = "UPDATE pr_proveedores SET pr_estado='Inactivo' where pr_id='"+pr_id+"'";

            boolean rs = CSDesktop.datos.manipuladorDatos(query);
             if(rs)
             {
                    jButtonModificar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al borrar el proveedor de la base de datos</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonModificar.setEnabled(true);
            }
            else
            {
                    jButtonModificar.setEnabled(false);
                    JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>El proveedor ha sido borrado correctamente.</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,mensaje);
                    jButtonModificar.setEnabled(true);
                    CSDesktop.EditarProveedorNew.dispose();
                    CSDesktop.ResultProveedor.dispose();
                    CSDesktop.menuBuscarProveedor.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jComboBoxDiaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaFacturaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxDiaFacturaActionPerformed

    private void jComboBoxFPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFPagoActionPerformed
        if (jComboBoxFPago.getSelectedItem().equals("Transferencia")) {
            jTextDigito.setEnabled(true);
            jTextEntidad.setEnabled(true);
            jTextSucursal.setEnabled(true);
            jTextNumCuenta.setEnabled(true);
            jTextNumIban.setEnabled(true);
        } else {
            jTextDigito.setEnabled(false);
            jTextEntidad.setEnabled(false);
            jTextSucursal.setEnabled(false);
            jTextNumCuenta.setEnabled(false);
            jTextNumIban.setEnabled(false);
        }
}//GEN-LAST:event_jComboBoxFPagoActionPerformed

    private void jTextDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionFocusLost
        String DireccionM = jTextDireccion.getText().toUpperCase();
        jTextDireccion.setText(DireccionM);
}//GEN-LAST:event_jTextDireccionFocusLost

    private void jTextNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreFocusLost
        String nombreM = jTextNombre.getText().toUpperCase();
        jTextNombre.setText(nombreM);
}//GEN-LAST:event_jTextNombreFocusLost

    private void jTextDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDNIFocusLost
        String DNIM = jTextDNI.getText().toUpperCase();
        jTextDNI.setText(DNIM);
}//GEN-LAST:event_jTextDNIFocusLost

    private void jComboBoxPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlazoActionPerformed
        if (jComboBoxPlazo.getSelectedItem().equals("Especial")) {
            jTextDiasPlazo.setEnabled(true);
        } else {
            jTextDiasPlazo.setEnabled(false);
        }
}//GEN-LAST:event_jComboBoxPlazoActionPerformed

    private void jTextEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailFocusLost
        String MailM = jTextEmail.getText().toUpperCase();
        jTextEmail.setText(MailM);
}//GEN-LAST:event_jTextEmailFocusLost

    private void jTextFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFaxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFaxActionPerformed

    private void jTextPoblacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionFocusLost
        String PoblacionM = jTextPoblacion.getText().toUpperCase();
        jTextPoblacion.setText(PoblacionM);
}//GEN-LAST:event_jTextPoblacionFocusLost

    private void jTextDireccionFiscalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionFiscalFocusLost
        String DireccionFiscalConM = jTextDireccionFiscal.getText().toUpperCase();
        jTextDireccionFiscal.setText(DireccionFiscalConM);
}//GEN-LAST:event_jTextDireccionFiscalFocusLost

    private void jTextPoblacionFiscalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionFiscalFocusLost
        String PoblacionFiscalConM = jTextPoblacionFiscal.getText().toUpperCase();
        jTextPoblacionFiscal.setText(PoblacionFiscalConM);
}//GEN-LAST:event_jTextPoblacionFiscalFocusLost

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        FileChooser utilFc = new FileChooser();
        final JFileChooser fc = new JFileChooser();
        //In response to a button click:
        urlTarifas = utilFc.editTarifasUrl(urlTarifas);
}//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextNumIbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumIbanActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextNumIbanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox jComboBoxDiaFactura;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxFPago;
    private javax.swing.JComboBox jComboBoxPlazo;
    private javax.swing.JComboBox jComboBoxProvincia;
    private javax.swing.JComboBox jComboBoxProvinciaFiscal;
    private javax.swing.JComboBox jComboBoxRegimen;
    private javax.swing.JComboBox jComboBoxTipo;
    private com.toedter.calendar.JDateChooser jDateChooserAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextCodPostal;
    private javax.swing.JTextField jTextCodPostalFiscal;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextDiasPlazo;
    private javax.swing.JTextField jTextDigito;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextDireccionFiscal;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEntidad;
    private javax.swing.JTextField jTextFax;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumCuenta;
    private javax.swing.JTextField jTextNumIban;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPoblacion;
    private javax.swing.JTextField jTextPoblacionFiscal;
    private javax.swing.JTextField jTextSucursal;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jTextTelefono2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lCodPostal;
    private javax.swing.JLabel lCodPostalFiscal;
    private javax.swing.JLabel lDNI;
    private javax.swing.JLabel lDiasPlazo;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lDireccion1;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lFPago;
    private javax.swing.JLabel lFactura;
    private javax.swing.JLabel lFactura1;
    private javax.swing.JLabel lFax;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNumCuenta;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lPContacto;
    private javax.swing.JLabel lPContacto1;
    private javax.swing.JLabel lPlazo;
    private javax.swing.JLabel lPoblacion;
    private javax.swing.JLabel lPoblacionFiscal;
    private javax.swing.JLabel lProvincia;
    private javax.swing.JLabel lProvinciaFiscal;
    private javax.swing.JLabel lRegimen;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel lTelefono2;
    private javax.swing.JLabel lTipo;
    private javax.swing.JTable tablaContactos;
    // End of variables declaration//GEN-END:variables

    public Dimension getPreferredSize()
    {
      return new Dimension( 850,600 );
    }
     /**
     * Función para la validación de los campos
     * @param accion
     */
    public void ValidarFormatos(String accion)
    {
         jButtonModificar.setEnabled(false);
         JLabel errorFields = new JLabel(accion);
         JOptionPane.showMessageDialog(null,errorFields);
         jButtonModificar.setEnabled(true);
    }

    /**
     * Función para rellenar el formulario de la bd
     * @param proveedor
     */
     public void datosProveedor(int proveedor)
    {
    	String query = "SELECT * FROM pr_proveedores " +
                       "WHERE pr_id = "+proveedor;

        ResultSet rs = CSDesktop.datos.select(query);
        System.out.println(query);
        int numeroFila = 0;

        try
        {
            while(rs.next())
            {
                String fecha = rs.getString("pr_fecha");
                String [] temp = null;
                    temp = fecha.split("\\-");
                    String anyo=temp[0];
                    String mes=temp[1];
                    String dia=temp[2];
                    String nueva=dia+"-"+mes+"-"+anyo;
                SimpleDateFormat sdf= new SimpleDateFormat("dd-MM-yyyy");
                Date d=sdf.parse(nueva);
                jDateChooserAlta.setDate(d);

                jTextNumero.setText(rs.getString("pr_id"));
                jTextNombre.setText(rs.getString("pr_nombre_fiscal"));
                jTextDNI.setText(rs.getString("pr_DNI_CIF"));
                jComboBoxRegimen.setSelectedItem(rs.getString("pr_regimen"));
                jComboBoxTipo.setSelectedItem(rs.getString("pr_tipo"));
                jTextDireccion.setText(rs.getString("pr_direccion"));
                jTextCodPostal.setText(rs.getString("pr_cod_postal"));
                jTextPoblacion.setText(rs.getString("pr_poblacion"));
                jComboBoxProvincia.setSelectedItem(rs.getString("pr_provincia"));
                jTextDireccionFiscal.setText(rs.getString("pr_direccion_fiscal"));
                jTextCodPostalFiscal.setText(rs.getString("pr_cod_postal_fiscal"));
                jTextPoblacionFiscal.setText(rs.getString("pr_poblacion_fiscal"));
                jComboBoxProvinciaFiscal.setSelectedItem(rs.getString("pr_provincia_fiscal"));
                jTextTelefono.setText(rs.getString("pr_telefono"));
                jTextTelefono2.setText(rs.getString("pr_telefono2"));
                jTextFax.setText(rs.getString("pr_fax"));
                jTextEmail.setText(rs.getString("pr_email"));
                jComboBoxPlazo.setSelectedItem(rs.getString("pr_plazo"));
                jTextDiasPlazo.setText(rs.getString("pr_dias_plazo"));
                jComboBoxFPago.setSelectedIndex(rs.getInt("fp_id")-1);
                String cuenta = rs.getString("pr_num_cuenta");
                if(!cuenta.equals(""))
                {
                    String [] tempN = null;
                    tempN = cuenta.split("\\/");
                    if(cuenta.length() ==23){
                        jTextEntidad.setText(tempN[0]);
                        jTextSucursal.setText(tempN[1]);
                        jTextDigito.setText(tempN[2]);
                        jTextNumCuenta.setText(tempN[3]);
                    }else{
                        jTextNumIban.setText(tempN[0]);
                        jTextEntidad.setText(tempN[1]);
                        jTextSucursal.setText(tempN[2]);
                        jTextDigito.setText(tempN[3]);
                        jTextNumCuenta.setText(tempN[4]);
                    }
                }
                jComboBoxEstado.setSelectedItem(rs.getString("pr_estado"));
                jComboBoxDiaFactura.setSelectedItem(rs.getString("pr_dia_factura"));
                urlTarifas = rs.getString("pr_tarifa_url");
                numeroFila++;
            }
            rs.close();

        } catch (Exception ex)
        {
            ex.printStackTrace();
        }

        if (numeroFila == 0)
        {
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>No se han encontrado Proveedores, con los parámetros de búsqueda seleccionados.</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields);
        }

    }

    /**
     * FunciÃ³n para sacar todas las formas de pago de la bd
     * @return
     * @throws SQLException
     */
    private void getFPagoProveedores() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT fp_id, fp_tipo FROM fp_forma_pago");

        //jComboBoxFPago = new JComboBox();
        //jTarifas.setSelectedIndex(0);
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("fp_tipo");

             jComboBoxFPago.addItem(valor);
             //jCombPago.addItem(rs.getString("fp_tipo"))
             j++;
        }
     }

    /**
     * Función para mostrar los contactos de un proveedor
     * @param cliente
     */
    public void ABResultBuscarContactos(int proveedor)
    {
        TablaModelo modelo = new TablaModelo();
        String queryCont = "SELECT * FROM cp_contactos_proveedor WHERE pr_id = '"+proveedor+"'";
        ResultSet rs = CSDesktop.datos.select(queryCont);

        modelo.setColumnIdentifiers(new String[] {"NUM","NOMBRE", "TELEFONO", "MAIL"});

        int numeroFila = 0;
        try
        {
            while (rs.next())
            {
                Object[] datosFila = new Object[modelo.getColumnCount()];
                int j = 0;
                for (int k = 0; k < 10; k++)
                {
                    if (k == 0 || k == 1 || k == 2 || k == 4)
                    {
                        datosFila[j] = rs.getObject(k + 1);
                        System.out.println("Dato" + k + " " + rs.getObject(k + 1));
                        j++;
                    }
                }
               
                modelo.addRow(datosFila);
                numeroFila++;
            }
            rs.close();
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(CSResultBuscarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (numeroFila == 0)
        {
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>No se han encontrado contactos de este Proveedor con los parámetros de búsqueda seleccionados.</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields);
        }
        else
        {
            tablaContactos.setModel(modelo);
            TableColumn columna = tablaContactos.getColumnModel().getColumn(0);
            columna.setPreferredWidth(50);
            TableColumn columna1 = tablaContactos.getColumnModel().getColumn(1);
            columna1.setPreferredWidth(300);
            TableColumn columna2 = tablaContactos.getColumnModel().getColumn(2);
            columna2.setPreferredWidth(100);
            TableColumn columna3 = tablaContactos.getColumnModel().getColumn(3);
            columna3.setPreferredWidth(200);

              tablaContactos.setModel(modelo);

            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            tablaContactos.getColumnModel().getColumn(0).setCellRenderer(tcr);
            tablaContactos.getColumnModel().getColumn(2).setCellRenderer(tcr);


            tablaContactos.addMouseListener(new MouseAdapter()
            {
            public void mouseClicked(MouseEvent e)
            {
                int fila = tablaContactos.rowAtPoint(e.getPoint());
                int columna = tablaContactos.columnAtPoint(e.getPoint());

                if ((fila > -1) && (columna > -1))
                {
                   int id_contacto = Integer.parseInt((String)tablaContactos.getValueAt(fila,0).toString());
                   CSDesktop.EditarContactoProveedor = new JInternalFrame("Editar contacto Proveeedor", true, false, false, true );
                   // adjuntar panel al panel de contenido del marco interno
                   CSEditarContactoProveedor editarCP = null;
                        try {
                            editarCP = new CSEditarContactoProveedor(id_contacto);
                        } catch (SQLException ex) {
                            Logger.getLogger(CSEditarContactoProveedor.class.getName()).log(Level.SEVERE, null, ex);
                        }
                   CSDesktop.EditarContactoProveedor.getContentPane().add( editarCP,BorderLayout.CENTER);
                   // establecer tamaño de marco interno en el tama�o de su contenido
                   CSDesktop.EditarContactoProveedor.pack();
                   // adjuntar marco interno al escritorio y mostrarlo
                   CSDesktop.elEscritorio.add( CSDesktop.EditarContactoProveedor);
                   Dimension pantalla = CSDesktop.elEscritorio.getSize();
                   Dimension ventana = CSDesktop.EditarProveedorNew.getSize();
                   CSDesktop.EditarContactoProveedor.setLocation(
                        (pantalla.width - ventana.width) / 2,
                        (pantalla.height - ventana.height) / 2);
                   CSDesktop.EditarContactoProveedor.setVisible( true );

                   System.out.println(tablaContactos.getValueAt(fila,columna));
                }
            }
           }    );
        }
    }
    /**
     * Modificamos las tarifas del proveedor si ha seleccionado un incremento
     * @param proveedor
     * @param incremento
     */
    public void incrementarTarifas(String proveedor, String incremento) throws UnknownHostException
    {
        String query = "SELECT * FROM tp_tarifas_proveedores WHERE pr_id = '"+proveedor+"' AND tp_fecha_hasta = '2050-01-01'";

        ResultSet rs = CSDesktop.datos.select(query);
        try {
            
            DbConnection da = new DbConnection();
            while (rs.next())
            {
                   boolean rsTp = true;
                   int tp_id = rs.getInt("tp_id");
                   String tarifa =  rs.getString("tp_tarifa");
                   double tarifaN = Double.valueOf(tarifa).doubleValue();
                   double incrementoN = Double.valueOf(incremento).doubleValue();
                   tarifaN = tarifaN + ((tarifaN * incrementoN) / 100.0);

                   String queryTp = "UPDATE tp_tarifas_proveedores SET tp_incremento='"+incremento+"', tp_tarifa="+tarifaN+
                                    " WHERE tp_id = '"+tp_id+"'";

                   System.out.println(queryTp);
                   rsTp = da.manipuladorDatos(queryTp);
                   if(rsTp)
                   {
                        jButtonModificar.setEnabled(false);
                        JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al modificar las tarifas en la base de datos</FONT></HTML>");
                        JOptionPane.showMessageDialog(null,errorFields);
                        jButtonModificar.setEnabled(true);
                   }
            }
            da.cerrarConexion();
            rs.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CSEditarProveedorNew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Función para la limitación de los campos
     */
    private void limitacionesCampos()
    {
        LimitadorDeDocumento limitadorDNI= new LimitadorDeDocumento(10);
        jTextDNI.setDocument(limitadorDNI);
        LimitadorDeDocumento limitador5= new LimitadorDeDocumento(5);
        jTextCodPostal.setDocument(limitador5);
        LimitadorDeDocumento limitadorNombre= new LimitadorDeDocumento(50);
        jTextNombre.setDocument(limitadorNombre);
        LimitadorDeDocumento limitadorEmail= new LimitadorDeDocumento(50);
        jTextEmail.setDocument(limitadorEmail);
        LimitadorDeDocumento limitadorEntidad= new LimitadorDeDocumento(4);
        jTextEntidad.setDocument(limitadorEntidad);
        LimitadorDeDocumento limitadorSucursal= new LimitadorDeDocumento(4);
        jTextSucursal.setDocument(limitadorSucursal);
        LimitadorDeDocumento limitadorDigito= new LimitadorDeDocumento(2);
        jTextDigito.setDocument(limitadorDigito);
        LimitadorDeDocumento limitadorNumC= new LimitadorDeDocumento(10);
        jTextNumCuenta.setDocument(limitadorNumC);
        LimitadorDeDocumento limitadorNumIban= new LimitadorDeDocumento(4);
        jTextNumIban.setDocument(limitadorNumIban);
    }
}