/*
 * CSInformeCOmercial.java
 *
 * Created on 10-dic-2009, 8:48:09
 */

package neg;


import com.mysql.jdbc.Connection;
import data.DbConnection;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static neg.CSDesktop.InformeComercial;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import utils.Utilidades;

/**
 *
 * @author depr102
 */
public class CSInformeComercial extends javax.swing.JPanel
{
    /** Creates new form CSInformeDet1 */
    public CSInformeComercial() throws SQLException
    {
        initComponents();
        CSDesktop.menuInformeDetallado1.setEnabled(false);
        KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonGenerar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };
        jDateAnyo.addKeyListener(l);
        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButtonGenerar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        lFechaFin = new javax.swing.JLabel();
        jDateAnyo = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(170, 16, 4));
        jLabel1.setText("INFORME COMERCIAL");
        jLabel1.setName("jLabel1"); // NOI18N

        jSeparator7.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator7.setName("jSeparator7"); // NOI18N

        jSeparator6.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator6.setName("jSeparator6"); // NOI18N

        jButtonGenerar.setText("Generar");
        jButtonGenerar.setName("jButtonGenerar"); // NOI18N
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(255, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        lFechaFin.setForeground(new java.awt.Color(0, 0, 100));
        lFechaFin.setText("Año");
        lFechaFin.setName("lFechaFin"); // NOI18N

        jDateAnyo.setDateFormatString("yyyy"); // NOI18N
        jDateAnyo.setName("jDateFechaAnyo"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator7))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jButtonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(lFechaFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateAnyo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerar)
                    .addComponent(jButtonCancelar))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed

        GenerarInforme();
    }

    public void GenerarInforme(){

         // BORRAR LA TABLA AUXILIAR DE INFORMES
         String queryDel = "DELETE FROM fo_informe_comercial_aux";
         boolean resDel = CSDesktop.datos.manipuladorDatos(queryDel);

        //Se comprueba que haya seleccionado un cliente
        String anyo = new String(jDateAnyo.toString());

        if (!Utilidades.campoObligatorio(anyo, "Año").equals("OK"))
        {
                ValidarFormatos(Utilidades.campoObligatorio(anyo, "Año"));
        }
        else
        {


            String fechaSIni="";
            String fechaSFin="";

            //SE RECOGEN LAS FECHAS DE GENERACION DEL INFORME
            
            //FECHA INICIO
            String fechaIni="2014-01-01";

            //FECHA FIN
            String fechaFin="2014-12-31";
            
            // SE EJECUTA LA QUERY NECEARIA PARA RECOGER LOS DATOS NECESARIOS PARA REALIZAR EL INFORME
            // POR LO QUE PARECE, EL CLIENTE SIEMPRE TIENE QUE APARECER PORQUE EN LA QUERY ESTA.
            String query="SELECT cl.cl_id, cl.cl_nombre, MONTH(pe.pe_fecha) AS mes, SUM(pe.pe_ta_es_cliente) AS ta_cliente, " +
                         "FROM carset.pe_pedidos pe INNER JOIN carset.pc_pedidos_clientes pc ON pe.pe_num = pc.pe_num " +
                         "INNER JOIN carset.cl_clientes cl ON pc.cl_id = cl.cl_id " +
                         "WHERE cl.cl_estado = 'Activo'";
            if ((!fechaIni.equals("")) && (!fechaFin.equals(""))) {
                query = query + " AND pe.pe_fecha BETWEEN '"+fechaIni+"' AND '"+fechaFin+"'";
            }
            query = query + " GROUP BY cl.cl_nombre, mes";

            System.out.println(query);

            ResultSet rs = CSDesktop.datos.select(query);
            try
            {
                while (rs.next())
                {
                    //TOTAL
//                    double importeTotalAux = importeTarifa + dSuplemento - IdaVuelta2 + importeServicio;
//                    importeTotalAux=redondear(importeTotalAux, 2);
                    

                    // SE INTRODUCEN LOS VALORES EN LA TABLA AUXILIAR DE INFORMES
                    /*String query = "INSERT INTO fo_informe_comercial_aux (fo_nombre, fo_total, fo_num_pedidos, " +
                                   "fo_enero, fo_febrero, fo_marzo, fo_abril, fo_mayo, fo_junio, fo_julio, fo_agosto, " +
                                   "fo_septiembre, fo_octubre, fo_noviembre, fo_dicienbre, fo_anyo) VALUES (";
                    query = query + "'"+finalNum+"','"+fecha+"','"+soporte+"','"+finalServicio+"', '"+servicioEspecial+"','"+importeServicioEs+"','"+Vehiculo+"','"+matricula+"'," +
                                    "'"+importeTarifa+"','"+dSuplemento+"','"+IdaVuelta2+"','"+importeTotalAux+"','"+fechaPrevistaRecogida+"','"+fechaPrevistaEntrega+"', " +
                                    "'"+estado+"','"+nuevaFechaRealEntrega+"','"+observaciones+"')";
                    */
                    System.out.println(query);
                    boolean rs3 = CSDesktop.datos.manipuladorDatos(query);

                    // SE VAN REALIZANDO LAS SUMAS INTERMEDIAS PARA CALCULAR LA SUMA TOTAL
                   /* traslado=traslado + importeTarifa;
                    suplemento=suplemento + dSuplemento;
                    descuento= descuento + IdaVuelta2;
                    neto = neto + importeTotalAux;*/
            } // FIN DEL FOR QUE RECORRE LA LISTA
            } catch (SQLException ex) {
            Logger.getLogger(CSResultBuscarProveedor.class.getName()).log(Level.SEVERE, null, ex);
            }
            Map pars = new HashMap();
            //pars.put("Mes",Utilidades.LiteralMes(mes)+" "+anyo);
            pars.put("Query", query);
            pars.put("FechaInicio", fechaSIni);
            pars.put("FechaFin", fechaSFin);

            JasperReport jasperReport = null;
            JasperPrint jasperPrint;
            Connection con = null;

            try {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CSInformeDet1.class.getName()).log(Level.SEVERE, null, ex);
                }
                 DbConnection conexion = null;
                try {
                    conexion = new DbConnection();
                } catch (UnknownHostException ex) {
                    Logger.getLogger(CSInformeDet2.class.getName()).log(Level.SEVERE, null, ex);
                }
                    con=(Connection) conexion.getConexion();
                    //1-Compilamos el archivo XML y lo cargamos en memoria
                    jasperReport = JasperCompileManager.compileReport(getClass().getResourceAsStream("/data/reportes/InformeComercial.jrxml"));

                    //2-Llenamos el reporte con la informaci�n y par�metros necesarios
                    jasperPrint = JasperFillManager.fillReport(getClass().getResourceAsStream("/data/reportes/InformeComercial.jasper"), pars, con);

                    JRViewerDet2 jrViewer = new JRViewerDet2(jasperPrint);
                    CSDesktop.InformeComercial = new JInternalFrame("Informe Comercial", true, false, false, true );
                    CSDesktop.InformeComercial.getContentPane().add( jrViewer, BorderLayout.CENTER );
                    CSDesktop.InformeComercial.pack();

                    CSDesktop.elEscritorio.add( CSDesktop.InformeComercial );
                    Dimension pantalla = CSDesktop.elEscritorio.getSize();
                    CSDesktop.InformeComercial.setSize(pantalla);
                    CSDesktop.InformeComercial.setVisible(true);
            } catch (JRException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        CSDesktop.InformeComercial.dispose();
        CSDesktop.InformeComercial.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGenerar;
    private com.toedter.calendar.JDateChooser jDateAnyo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lFechaFin;
    // End of variables declaration//GEN-END:variables

     public void ValidarFormatos(String accion)
    {
         jButtonGenerar.setEnabled(false);
         JLabel errorFields = new JLabel(accion);
         JOptionPane.showMessageDialog(null,errorFields);
         jButtonGenerar.setEnabled(true);
    }

}
