/*
 * ABAnyadirCliente.java
 *
 * Created on 03-oct-2009, 0:25:10
 */

package neg;

import utils.LimitadorDeDocumento;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author lito
 */
public class CSServicioProveedorNew extends javax.swing.JPanel
{
    int pr_id = 0;

    public CSServicioProveedorNew(String query, int proveedor) throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select(query);

        CSDesktop.EditarProveedorNew.setEnabled(false);
        initComponents();
        limitacionesCampos();
        pr_id = proveedor;
        int numeroFila = 0;

        try{
            while (rs.next()){
                jTextTurismo.setText(rs.getString("sr_turismo"));
                jTextFLM.setText(rs.getString("sr_flm"));
                jTex4x4.setText(rs.getString("sr_todoterreno"));
                jTextFurgoneta.setText(rs.getString("sr_furgoneta"));
                jTextFurgon.setText(rs.getString("sr_furgon"));
                jTextSuv.setText(rs.getString("sr_suv"));
                jTextEspecial.setText(rs.getString("sr_especial"));
                jTextDias.setText(rs.getString("sr_dias"));
                numeroFila++;
            }
            rs.close();
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(CSResultBuscarProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        CSDesktop.ServicioProveedor = new JInternalFrame("Servicios Especiales de Proveedor", true, false, false, true );
        CSDesktop.ServicioProveedor.getContentPane().add( this, BorderLayout.CENTER );
        CSDesktop.ServicioProveedor.pack();
        CSDesktop.ServicioProveedor.dispose();
        CSDesktop.elEscritorio.add( CSDesktop.ServicioProveedor );
        Dimension pantalla = CSDesktop.elEscritorio.getSize();
        Dimension ventana = CSDesktop.ServicioProveedor.getSize();
        CSDesktop.ServicioProveedor.setLocation(
           (pantalla.width - ventana.width) / 2,
           (pantalla.height - ventana.height) / 2);
        CSDesktop.ServicioProveedor.setVisible( true );
         
        KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonModificar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };
        
        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTurismo = new javax.swing.JLabel();
        jTextTurismo = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        lFCorrecion = new javax.swing.JLabel();
        lFLM = new javax.swing.JLabel();
        jTextFLM = new javax.swing.JTextField();
        lFurgoneta = new javax.swing.JLabel();
        jTextFurgoneta = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFurgon = new javax.swing.JTextField();
        lFurgon = new javax.swing.JLabel();
        lSuv = new javax.swing.JLabel();
        jTextDias = new javax.swing.JTextField();
        jTextSuv = new javax.swing.JTextField();
        lFCorrecion3 = new javax.swing.JLabel();
        lDias = new javax.swing.JLabel();
        l4x4 = new javax.swing.JLabel();
        jTex4x4 = new javax.swing.JTextField();
        lEuro28 = new javax.swing.JLabel();
        lEuro29 = new javax.swing.JLabel();
        lEuro30 = new javax.swing.JLabel();
        lEuro31 = new javax.swing.JLabel();
        lEuro32 = new javax.swing.JLabel();
        lEuro33 = new javax.swing.JLabel();
        lEspecial = new javax.swing.JLabel();
        jTextEspecial = new javax.swing.JTextField();
        lEuro34 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(361, 525));

        lTurismo.setForeground(new java.awt.Color(0, 0, 100));
        lTurismo.setLabelFor(jTextTurismo);
        lTurismo.setText("Turismo");
        lTurismo.setName("lTurismo"); // NOI18N

        jTextTurismo.setName("jTextTurismo"); // NOI18N
        jTextTurismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTurismoActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Guardar");
        jButtonModificar.setName("jButtonModificar"); // NOI18N
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        lFCorrecion.setFont(new java.awt.Font("Tahoma", 1, 11));
        lFCorrecion.setForeground(new java.awt.Color(170, 16, 4));
        lFCorrecion.setText("TIPO DE VEHÍCULO");
        lFCorrecion.setName("lFCorrecion"); // NOI18N

        lFLM.setForeground(new java.awt.Color(0, 0, 100));
        lFLM.setLabelFor(jTextTurismo);
        lFLM.setText("Furgoneta ligera o Monovolumen");
        lFLM.setName("lFLM"); // NOI18N

        jTextFLM.setName("jTextFLM"); // NOI18N

        lFurgoneta.setForeground(new java.awt.Color(0, 0, 100));
        lFurgoneta.setLabelFor(jTextTurismo);
        lFurgoneta.setText("Furgoneta");
        lFurgoneta.setName("lFurgoneta"); // NOI18N

        jTextFurgoneta.setName("jTextFurgoneta"); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator3.setName("jSeparator3"); // NOI18N

        jTextFurgon.setName("jTextFurgon"); // NOI18N

        lFurgon.setForeground(new java.awt.Color(0, 0, 100));
        lFurgon.setLabelFor(jTextTurismo);
        lFurgon.setText("Furgón");
        lFurgon.setName("lFurgon"); // NOI18N

        lSuv.setForeground(new java.awt.Color(0, 0, 100));
        lSuv.setLabelFor(jTextTurismo);
        lSuv.setText("SUV");
        lSuv.setName("lSuv"); // NOI18N

        jTextDias.setName("jTextDias"); // NOI18N

        jTextSuv.setName("jTextSuv"); // NOI18N

        lFCorrecion3.setFont(new java.awt.Font("Tahoma", 1, 11));
        lFCorrecion3.setForeground(new java.awt.Color(170, 16, 4));
        lFCorrecion3.setText("DÍAS HÁBILES MÁXIMOS DE ENTREGA");
        lFCorrecion3.setName("lFCorrecion3"); // NOI18N

        lDias.setForeground(new java.awt.Color(0, 0, 100));
        lDias.setText("Días");
        lDias.setName("lDias"); // NOI18N

        l4x4.setForeground(new java.awt.Color(0, 0, 100));
        l4x4.setLabelFor(jTextTurismo);
        l4x4.setText("Todoterreno");
        l4x4.setName("l4x4"); // NOI18N

        jTex4x4.setName("jTex4x4"); // NOI18N

        lEuro28.setForeground(new java.awt.Color(0, 0, 100));
        lEuro28.setText("€ / Km.");
        lEuro28.setName("lEuro28"); // NOI18N

        lEuro29.setForeground(new java.awt.Color(0, 0, 100));
        lEuro29.setText("€ / Km.");
        lEuro29.setName("lEuro29"); // NOI18N

        lEuro30.setForeground(new java.awt.Color(0, 0, 100));
        lEuro30.setText("€ / Km.");
        lEuro30.setName("lEuro30"); // NOI18N

        lEuro31.setForeground(new java.awt.Color(0, 0, 100));
        lEuro31.setText("€ / Km.");
        lEuro31.setName("lEuro31"); // NOI18N

        lEuro32.setForeground(new java.awt.Color(0, 0, 100));
        lEuro32.setText("€ / Km.");
        lEuro32.setName("lEuro32"); // NOI18N

        lEuro33.setForeground(new java.awt.Color(0, 0, 100));
        lEuro33.setText("€ / Km.");
        lEuro33.setName("lEuro33"); // NOI18N

        lEspecial.setForeground(new java.awt.Color(0, 0, 100));
        lEspecial.setLabelFor(jTextTurismo);
        lEspecial.setText("Especial");
        lEspecial.setName("lEspecial"); // NOI18N

        jTextEspecial.setName("jTextEspecial"); // NOI18N

        lEuro34.setForeground(new java.awt.Color(0, 0, 100));
        lEuro34.setText("€ / Km.");
        lEuro34.setName("lEuro34"); // NOI18N

        jSeparator4.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator4.setName("jSeparator4"); // NOI18N

        jSeparator8.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator8.setForeground(new java.awt.Color(0, 102, 51));
        jSeparator8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 53), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jSeparator8.setName("jSeparator8"); // NOI18N
        jSeparator8.setOpaque(true);
        jSeparator8.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lFCorrecion, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jTextDias, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lDias)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lFCorrecion3)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEspecial)
                    .addComponent(lSuv)
                    .addComponent(lFurgon)
                    .addComponent(lFurgoneta)
                    .addComponent(l4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTurismo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lFLM, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTex4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFLM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTurismo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFurgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFurgon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextSuv, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addComponent(jTextEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lEuro28))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEuro30)
                            .addComponent(lEuro29)
                            .addComponent(lEuro31)
                            .addComponent(lEuro32)
                            .addComponent(lEuro33)
                            .addComponent(lEuro34))))
                .addGap(48, 48, 48))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTex4x4, jTextDias, jTextEspecial, jTextFLM, jTextFurgon, jTextFurgoneta, jTextSuv, jTextTurismo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator3, jSeparator4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFCorrecion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTurismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro28)
                    .addComponent(lTurismo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro29)
                    .addComponent(lFLM))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTex4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro30)
                    .addComponent(l4x4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFurgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro31)
                    .addComponent(lFurgoneta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFurgon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro32)
                    .addComponent(lFurgon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSuv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro33)
                    .addComponent(lSuv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEuro34)
                    .addComponent(jTextEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEspecial))
                .addGap(25, 25, 25)
                .addComponent(lFCorrecion3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDias))
                .addGap(11, 11, 11)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificar)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar)
                .addGap(21, 21, 21))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextDias, jTextFLM, jTextFurgon, jTextFurgoneta, jTextSuv, jTextTurismo});

    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
 
            System.out.println("\nBoton Servicios Proveedor.");

            String turismo = new String(jTextTurismo.getText());
            String flm = new String(jTextFLM.getText());
            String todoterreno = new String(jTex4x4.getText());
            String especial = new String(jTextEspecial.getText());
            String furgonetas = new String(jTextFurgoneta.getText());
            String furgones = new String(jTextFurgon.getText());
            String suv = new String(jTextSuv.getText());
            String dias = new String(jTextDias.getText());

            //CAMPOS OBLIGATORIOS
           /* if (!Utilidades.campoObligatorio(todoterreno,"todoterreno").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(todoterreno,"todoterreno"));
            }
            else if (!Utilidades.campoObligatorio(furgones,"Furgones").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(furgones,"Furgones"));
            }
            else if (!Utilidades.campoObligatorio(furgonetas,"Furgonetas").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(furgonetas,"Furgonetas"));
            }
            else if (!Utilidades.campoObligatorio(turismo,"Turismo").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(turismo,"Turismo"));
            }
            else
            {*/
                int exist = 0;
                try {
                    exist = buscarServiciosProveedor(pr_id);
                } catch (SQLException ex) {
                    Logger.getLogger(CSServicioProveedorNew.class.getName()).log(Level.SEVERE, null, ex);
                }
                String query = "";
                if (exist > 0){
                    query = "UPDATE sr_servicios SET sr_turismo  = '"+turismo+"', sr_flm  = '"+flm+"', " +
                            "sr_todoterreno  = '"+todoterreno+"', sr_furgoneta  = '"+furgonetas+"', sr_furgon  = '"+furgones+"', " +
                            "sr_suv  = '"+suv+"', sr_especial  = '"+especial+"', sr_dias= '"+dias+"'" +
                            "WHERE pr_id = "+ pr_id+"";
                }else{
                    query = "INSERT INTO sr_servicios (sr_turismo, sr_flm, sr_todoterreno, " +
                            "sr_furgoneta, sr_furgon, sr_suv, sr_especial, sr_dias, pr_id) values (" +
                            "'"+turismo+"', '"+flm+"', '"+todoterreno+"', '"+furgonetas+"', " +
                            "'"+furgones+"', '"+suv+"', '"+especial+"', '"+dias+"',  '"+ pr_id+"')";
                }
                System.out.println(query);
                boolean rs = CSDesktop.datos.manipuladorDatos(query);
                System.out.println(rs);
                if(rs)
                {
                    jButtonModificar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonModificar.setEnabled(true);
                }
                else
                {
                    jButtonModificar.setEnabled(false);
                    JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>Los datos se han guardado correctamente.</FONT></HTML>");
                    JOptionPane.showMessageDialog(null, mensaje);
                    jButtonModificar.setEnabled(true);
                    CSDesktop.ServicioProveedor.dispose();
                    CSDesktop.EditarProveedorNew.setVisible(true);
                }
           // }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    public Dimension getPreferredSize()
    {
      return new Dimension( 365,505 );
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
            {
               CSDesktop.EditarProveedorNew.setEnabled(true);
               CSDesktop.ServicioProveedor.dispose();
               CSDesktop.EditarProveedorNew.setVisible(true);
            }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextTurismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTurismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTurismoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTex4x4;
    private javax.swing.JTextField jTextDias;
    private javax.swing.JTextField jTextEspecial;
    private javax.swing.JTextField jTextFLM;
    private javax.swing.JTextField jTextFurgon;
    private javax.swing.JTextField jTextFurgoneta;
    private javax.swing.JTextField jTextSuv;
    private javax.swing.JTextField jTextTurismo;
    private javax.swing.JLabel l4x4;
    private javax.swing.JLabel lDias;
    private javax.swing.JLabel lEspecial;
    private javax.swing.JLabel lEuro28;
    private javax.swing.JLabel lEuro29;
    private javax.swing.JLabel lEuro30;
    private javax.swing.JLabel lEuro31;
    private javax.swing.JLabel lEuro32;
    private javax.swing.JLabel lEuro33;
    private javax.swing.JLabel lEuro34;
    private javax.swing.JLabel lFCorrecion;
    private javax.swing.JLabel lFCorrecion3;
    private javax.swing.JLabel lFLM;
    private javax.swing.JLabel lFurgon;
    private javax.swing.JLabel lFurgoneta;
    private javax.swing.JLabel lSuv;
    private javax.swing.JLabel lTurismo;
    // End of variables declaration//GEN-END:variables

    public void ValidarFormatos(String accion)
    {
         jButtonModificar.setEnabled(false);
         JLabel errorFields = new JLabel(accion);
         JOptionPane.showMessageDialog(null,errorFields);
         jButtonModificar.setEnabled(true);
    }

    private void limitacionesCampos()
    {
        LimitadorDeDocumento limitador4= new LimitadorDeDocumento(10);
        jTextFLM.setDocument(limitador4);
        LimitadorDeDocumento limitadorFurgones= new LimitadorDeDocumento(10);
        jTextFurgoneta.setDocument(limitadorFurgones);
        LimitadorDeDocumento limitadorIndustrial= new LimitadorDeDocumento(10);
        jTextTurismo.setDocument(limitadorIndustrial);
    }

    /**
     * Insertar los servicios especiales del Proveedor desde el Proveedor de plantilla
     * @param proveedor
     */
    public int buscarServiciosProveedor(int idPr) throws SQLException
    {
        int exist = 0;

        String query = "SELECT count(1) as cont FROM sr_servicios WHERE pr_id = '"+idPr+"'";

        System.out.println(query);
        ResultSet rsExist = CSDesktop.datos.select(query);
        try {
            rsExist.next();
        } catch (SQLException ex) {
            Logger.getLogger(CSServicioProveedorNew.class.getName()).log(Level.SEVERE, null, ex);
        }
        exist = rsExist.getInt("cont");
        rsExist.close();

        return exist;
    }
}