/*
 * BuscaClientesPanel.java
 *
 * Created on 06-oct-2009, 11:09:27
 */

package neg;

import data.BeanCorreoCliente;
import java.io.IOException;
import javax.mail.MessagingException;
import utils.TablaModelo;
import javax.swing.table.TableColumn;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author depr102
 */
public class CSSelectMailClienteFactura extends javax.swing.JPanel
{
    TablaModelo modelo = new TablaModelo();
    private HashMap datosMail = new HashMap();
    private HashMap nombresMail = new HashMap();
    String nombreF="";
    BeanCorreoCliente mailF=new BeanCorreoCliente();

    /** Creates new form BuscaClientesPanel */
    public CSSelectMailClienteFactura(String query,BeanCorreoCliente mail,String nombre)
    {
        mailF=mail;
        nombreF=nombre;
        
        ResultSet rs = CSDesktop.datos.select(query);

        modelo.setColumnIdentifiers(new String[] {"NOMBRE", "EMAIL"});

        int numeroFila = 0;
        try {
            int z=0;
            while (rs.next()) {
                Object[] datosFila = new Object[modelo.getColumnCount()];
                int j = 0;
                for (int k = 0; k < 2; k++)
                {
                    if (k==0)
                    {
                        datosFila[j] = rs.getObject(k + 1);
//                        System.out.println("Dato" + k + " " + rs.getObject(k + 1));
                        nombresMail.put(z,rs.getObject(k + 1));
                        j++;
                    }
                    else if ( k == 1)
                    {
                        datosFila[j] = rs.getObject(k + 1);
//                        System.out.println("Dato" + k + " " + rs.getObject(k + 1));
                        datosMail.put(z,rs.getObject(k + 1));
                        j++;
                    }
                }
                modelo.addRow(datosFila);
                numeroFila++;
                z++;
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(CSResultBuscarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
        jTable1.setModel(modelo);
        TableColumn columna = jTable1.getColumnModel().getColumn(0);
        columna.setPreferredWidth(200);
        TableColumn columna1 = jTable1.getColumnModel().getColumn(1);
        columna1.setPreferredWidth(300);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonMandar = new javax.swing.JButton();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEditingRow(0);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.setPreferredSize(new java.awt.Dimension(264, 375));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Cerrar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonMandar.setText("Mandar");
        jButtonMandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMandarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton1)
                        .addGap(101, 101, 101)
                        .addComponent(jButtonMandar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonMandar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CSDesktop.BuscaMailCliente.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
      
        
}//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonMandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMandarActionPerformed
         int [] celdas1=jTable1.getSelectedRows();

         CSDesktop.mailCliente.clear();
         CSDesktop.nombreCliente.clear();
         for (int i=0;i<celdas1.length;i++)
         {
            int celda=celdas1[i];
            CSDesktop.mailCliente.put(i,datosMail.get(celda));
            CSDesktop.nombreCliente.put(i,nombresMail.get(celda));
         }
         for(int i=0;i<CSDesktop.mailCliente.size();i++)
         {
             CSLanzarFactura factura = new CSLanzarFactura();
            try {
                try {
                    factura.enviarMail(mailF, nombreF, CSDesktop.mailCliente.get(i).toString(), CSDesktop.nombreCliente.get(i).toString());
                } catch (MessagingException ex) {
                    Logger.getLogger(CSSelectMailClienteFactura.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (IOException ex) {
                Logger.getLogger(CSSelectMailClienteFactura.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         CSDesktop.BuscaMailCliente.dispose();
    }//GEN-LAST:event_jButtonMandarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMandar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}