/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABAnyadirProveedores.java
 *
 * Created on 29-sep-2009, 21:04:18
 */

package neg;

import utils.LimitadorDeDocumento;
import data.DbConnection;
import data.Proveedor;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utils.Utilidades;

/**
 *
 * @author lito
 */
public class CSAnyadirProveedor extends JPanel
{
    /** Creates new form ABAnyadirProveedores */
    public CSAnyadirProveedor() throws SQLException
    {
        CSDesktop.menuNuevoProveedor.setEnabled(false);
        this.setLayout(new GridBagLayout());

        Date hoy = new Date();
        initComponents();
        jDateChooserAlta.setDate(hoy);
        limitacionesCampos();
        getFPagoProveedores();
        getDepartamentoContacto();

        KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonGuardar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };

        for (int k = 0; k < this.getComponents().length; k ++)
        {
            if (this.getComponents()[k] != jComboBoxEstado &&
                this.getComponents()[k] != jComboBoxFPago &&
                this.getComponents()[k] != jComboBoxPlazo &&
                this.getComponents()[k] != jComboBoxRegimen &&
                this.getComponents()[k] != jComboBoxDepartamento &&
                this.getComponents()[k] != jComboBoxTipo &&
                this.getComponents()[k] != jComboBoxDiaFactura &&
                this.getComponents()[k] != jComboBoxProvinciaFiscal &&
                this.getComponents()[k] != jComboBoxProvincia)
            {
                this.getComponents()[k].addKeyListener(l);
            }
        }
        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lPoblacion = new javax.swing.JLabel();
        jTextPoblacion = new javax.swing.JTextField();
        lProvincia = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        lFax = new javax.swing.JLabel();
        jTextFax = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        lNumCuenta = new javax.swing.JLabel();
        jTextNumCuenta = new javax.swing.JTextField();
        lFPago = new javax.swing.JLabel();
        jComboBoxFPago = new javax.swing.JComboBox();
        jButtonGuardar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonCancelar = new javax.swing.JButton();
        lTipo = new javax.swing.JLabel();
        lDireccion = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        lCodPostal = new javax.swing.JLabel();
        jTextCodPostal = new javax.swing.JTextField();
        lNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        lDNI = new javax.swing.JLabel();
        jTextDNI = new javax.swing.JTextField();
        lRegimen = new javax.swing.JLabel();
        jComboBoxRegimen = new javax.swing.JComboBox();
        jComboBoxTipo = new javax.swing.JComboBox();
        lEmailCon = new javax.swing.JLabel();
        jTextEmailCon = new javax.swing.JTextField();
        lTelefonoCon = new javax.swing.JLabel();
        jTextTelefonoCon = new javax.swing.JTextField();
        lPContacto = new javax.swing.JLabel();
        lNombreCon = new javax.swing.JLabel();
        jTextNombreCon = new javax.swing.JTextField();
        jComboBoxDepartamento = new javax.swing.JComboBox();
        lDepartamento = new javax.swing.JLabel();
        lNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jComboBoxProvincia = new javax.swing.JComboBox();
        jTextEntidad = new javax.swing.JTextField();
        jTextSucursal = new javax.swing.JTextField();
        jTextDigito = new javax.swing.JTextField();
        lPlazo = new javax.swing.JLabel();
        jComboBoxPlazo = new javax.swing.JComboBox();
        lTelefono2 = new javax.swing.JLabel();
        jTextTelefono2 = new javax.swing.JTextField();
        lEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lTelefonoCon2 = new javax.swing.JLabel();
        jTextTelefonoCon2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextDiasPlazo = new javax.swing.JTextField();
        lDiasPlazo = new javax.swing.JLabel();
        jComboBoxDiaFactura = new javax.swing.JComboBox();
        lFactura = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lPContacto1 = new javax.swing.JLabel();
        lDireccion1 = new javax.swing.JLabel();
        jTextCodPostalFiscal = new javax.swing.JTextField();
        lCodPostalFiscal = new javax.swing.JLabel();
        jTextDireccionFiscal = new javax.swing.JTextField();
        lPoblacionFiscal = new javax.swing.JLabel();
        jTextPoblacionFiscal = new javax.swing.JTextField();
        lProvinciaFiscal = new javax.swing.JLabel();
        jComboBoxProvinciaFiscal = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        lFactura1 = new javax.swing.JLabel();
        jDateChooserAlta = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setForeground(new java.awt.Color(0, 0, 100));

        lPoblacion.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacion.setText("Población");
        lPoblacion.setName("lPoblacion"); // NOI18N

        jTextPoblacion.setName("jTextPoblacion"); // NOI18N
        jTextPoblacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionFocusLost(evt);
            }
        });

        lProvincia.setForeground(new java.awt.Color(0, 0, 100));
        lProvincia.setText("Provincia");
        lProvincia.setName("lProvincia"); // NOI18N

        lTelefono.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono.setText("Teléfono");
        lTelefono.setName("lTelefono"); // NOI18N

        jTextTelefono.setName("jTextTelefono"); // NOI18N

        lFax.setForeground(new java.awt.Color(0, 0, 100));
        lFax.setText("Fax");
        lFax.setName("lFax"); // NOI18N

        jTextFax.setName("jTextFax"); // NOI18N
        jTextFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFaxActionPerformed(evt);
            }
        });

        lEmail.setForeground(new java.awt.Color(0, 0, 100));
        lEmail.setText("Email");
        lEmail.setName("lEmail"); // NOI18N

        jTextEmail.setName("jTextEmail"); // NOI18N
        jTextEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailFocusLost(evt);
            }
        });

        lNumCuenta.setForeground(new java.awt.Color(0, 0, 100));
        lNumCuenta.setText("Núm. cuenta");
        lNumCuenta.setName("lNumCuenta"); // NOI18N

        jTextNumCuenta.setEnabled(false);
        jTextNumCuenta.setName("jTextNumCuenta"); // NOI18N

        lFPago.setForeground(new java.awt.Color(0, 0, 100));
        lFPago.setText("Forma de Pago");
        lFPago.setName("lFPago"); // NOI18N

        jComboBoxFPago.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxFPago.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxFPago.setName("jComboBoxFPago"); // NOI18N
        jComboBoxFPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFPagoActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setName("jButtonGuardar"); // NOI18N
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator2.setName("jSeparator2"); // NOI18N

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        lTipo.setForeground(new java.awt.Color(0, 0, 100));
        lTipo.setText("Tipo");
        lTipo.setName("lTipo"); // NOI18N

        lDireccion.setForeground(new java.awt.Color(0, 0, 100));
        lDireccion.setText("Dirección");
        lDireccion.setName("lDireccion"); // NOI18N

        jTextDireccion.setName("jTextDireccion"); // NOI18N
        jTextDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionFocusLost(evt);
            }
        });

        lCodPostal.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostal.setText("Cód. Postal");
        lCodPostal.setName("lCodPostal"); // NOI18N

        jTextCodPostal.setName("jTextCodPostal"); // NOI18N

        lNombre.setForeground(new java.awt.Color(0, 0, 100));
        lNombre.setText("Nombre");
        lNombre.setName("lNombre"); // NOI18N

        jTextNombre.setName("jTextNombre"); // NOI18N
        jTextNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreFocusLost(evt);
            }
        });

        lDNI.setForeground(new java.awt.Color(0, 0, 100));
        lDNI.setText("DNI/NIF");
        lDNI.setName("lDNI"); // NOI18N

        jTextDNI.setName("jTextDNI"); // NOI18N
        jTextDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDNIFocusLost(evt);
            }
        });

        lRegimen.setForeground(new java.awt.Color(0, 0, 100));
        lRegimen.setText("Régimen");
        lRegimen.setName("lRegimen"); // NOI18N

        jComboBoxRegimen.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxRegimen.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxRegimen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empresa", "Régimen General", "Autónomo" }));
        jComboBoxRegimen.setName("jComboBoxRegimen"); // NOI18N

        jComboBoxTipo.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxTipo.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gruero", "Conductor", "Tren", "Custodia", "Global" }));
        jComboBoxTipo.setName("jComboBoxTipo"); // NOI18N

        lEmailCon.setForeground(new java.awt.Color(0, 0, 100));
        lEmailCon.setText("Email");
        lEmailCon.setName("lEmailCon"); // NOI18N

        jTextEmailCon.setName("jTextEmailCon"); // NOI18N
        jTextEmailCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmailConFocusLost(evt);
            }
        });

        lTelefonoCon.setForeground(new java.awt.Color(0, 0, 100));
        lTelefonoCon.setText("Teléfono");
        lTelefonoCon.setName("lTelefonoCon"); // NOI18N

        jTextTelefonoCon.setName("jTextTelefonoCon"); // NOI18N

        lPContacto.setFont(new java.awt.Font("Tahoma", 1, 11));
        lPContacto.setForeground(new java.awt.Color(170, 16, 4));
        lPContacto.setText("PERSONA DE CONTACTO");
        lPContacto.setName("lPContacto"); // NOI18N

        lNombreCon.setForeground(new java.awt.Color(0, 0, 100));
        lNombreCon.setText("Nombre");
        lNombreCon.setName("lNombreCon"); // NOI18N

        jTextNombreCon.setName("jTextNombreCon"); // NOI18N
        jTextNombreCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreConFocusLost(evt);
            }
        });

        jComboBoxDepartamento.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxDepartamento.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxDepartamento.setName("jComboBoxDepartamento"); // NOI18N

        lDepartamento.setForeground(new java.awt.Color(0, 0, 100));
        lDepartamento.setText("Departamento");
        lDepartamento.setName("lDepartamento"); // NOI18N

        lNumero.setForeground(new java.awt.Color(0, 0, 100));
        lNumero.setText("   Núm. Proveedor PR/");
        lNumero.setName("lNumero"); // NOI18N

        jTextNumero.setEditable(false);
        jTextNumero.setEnabled(false);
        jTextNumero.setName("jTextNumero"); // NOI18N

        jComboBoxProvincia.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvincia.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJ.", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVED.", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvincia.setName("jComboBoxProvincia"); // NOI18N

        jTextEntidad.setEnabled(false);
        jTextEntidad.setName("jTextEntidad"); // NOI18N

        jTextSucursal.setEnabled(false);
        jTextSucursal.setName("jTextSucursal"); // NOI18N

        jTextDigito.setEnabled(false);
        jTextDigito.setName("jTextDigito"); // NOI18N

        lPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lPlazo.setText("    Plazo");
        lPlazo.setName("lPlazo"); // NOI18N

        jComboBoxPlazo.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxPlazo.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxPlazo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30 días FF", "15 días FF", "45 días FF", "60 días FF", "Especial" }));
        jComboBoxPlazo.setName("jComboBoxPlazo"); // NOI18N
        jComboBoxPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlazoActionPerformed(evt);
            }
        });

        lTelefono2.setForeground(new java.awt.Color(0, 0, 100));
        lTelefono2.setText("Teléfono 2");
        lTelefono2.setName("lTelefono2"); // NOI18N

        jTextTelefono2.setName("jTextTelefono2"); // NOI18N

        lEstado.setForeground(new java.awt.Color(0, 0, 100));
        lEstado.setText("   Estado");
        lEstado.setName("lEstado"); // NOI18N

        jComboBoxEstado.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxEstado.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        jComboBoxEstado.setName("jComboBoxEstado"); // NOI18N

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("*");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("*");
        jLabel7.setName("jLabel7"); // NOI18N

        lTelefonoCon2.setForeground(new java.awt.Color(0, 0, 100));
        lTelefonoCon2.setText("Teléfono 2");
        lTelefonoCon2.setName("lTelefonoCon2"); // NOI18N

        jTextTelefonoCon2.setName("jTextTelefonoCon2"); // NOI18N

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("* Campos obligatorios");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("*");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("*");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("*");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("*");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("*");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("*");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("*");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("*");
        jLabel17.setName("jLabel17"); // NOI18N

        jTextDiasPlazo.setEnabled(false);
        jTextDiasPlazo.setName("jTextDiasPlazo"); // NOI18N

        lDiasPlazo.setForeground(new java.awt.Color(0, 0, 100));
        lDiasPlazo.setText("Días");
        lDiasPlazo.setName("lDiasPlazo"); // NOI18N

        jComboBoxDiaFactura.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxDiaFactura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jComboBoxDiaFactura.setName("jComboBoxDiaFactura"); // NOI18N
        jComboBoxDiaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaFacturaActionPerformed(evt);
            }
        });

        lFactura.setForeground(new java.awt.Color(0, 0, 100));
        lFactura.setText("Día del mes para facturar");
        lFactura.setName("lFactura"); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator1.setName("jSeparator1"); // NOI18N

        lPContacto1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lPContacto1.setForeground(new java.awt.Color(170, 16, 4));
        lPContacto1.setText("DOMICILIO FISCAL");
        lPContacto1.setName("lPContacto1"); // NOI18N

        lDireccion1.setForeground(new java.awt.Color(0, 0, 100));
        lDireccion1.setText("  Dirección");
        lDireccion1.setName("lDireccion1"); // NOI18N

        jTextCodPostalFiscal.setName("jTextCodPostalFiscal"); // NOI18N

        lCodPostalFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostalFiscal.setText("Código Postal");
        lCodPostalFiscal.setName("lCodPostalFiscal"); // NOI18N

        jTextDireccionFiscal.setName("jTextDireccionFiscal"); // NOI18N
        jTextDireccionFiscal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionFiscalFocusLost(evt);
            }
        });

        lPoblacionFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionFiscal.setText("  Población");
        lPoblacionFiscal.setName("lPoblacionFiscal"); // NOI18N

        jTextPoblacionFiscal.setName("jTextPoblacionFiscal"); // NOI18N
        jTextPoblacionFiscal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionFiscalFocusLost(evt);
            }
        });

        lProvinciaFiscal.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaFiscal.setText("Provincia");
        lProvinciaFiscal.setName("lProvinciaFiscal"); // NOI18N

        jComboBoxProvinciaFiscal.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaFiscal.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaFiscal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "A CORUÑA", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERÍA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CÓRDOBA", "CUENCA", "GIRONA", "GRANADA", "GUADALAJ.", "GUIPÚZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LA RIOJA", "LAS PALMAS", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MÁLAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PONTEVED.", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaFiscal.setName("jComboBoxProvinciaFiscal"); // NOI18N

        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("*");
        jLabel18.setName("jLabel18"); // NOI18N

        lFactura1.setForeground(new java.awt.Color(0, 0, 100));
        lFactura1.setText("Fecha Alta Proveedor");
        lFactura1.setName("lFactura1"); // NOI18N

        jDateChooserAlta.setDateFormatString("dd-MM-yyyy");
        jDateChooserAlta.setName("jDateChooserAlta"); // NOI18N

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("*");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("*");
        jLabel16.setName("jLabel16"); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator3.setName("jSeparator3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lPContacto)
                .addContainerGap(628, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lPContacto1)
                .addContainerGap(654, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPlazo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lEstado)
                        .addGap(27, 27, 27)
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lFactura1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(lFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDiaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lRegimen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPoblacion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTelefono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextPoblacion, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lProvincia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jComboBoxPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDiasPlazo)
                                .addGap(20, 20, 20)
                                .addComponent(lFPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxFPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lTelefono2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lFax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lNumCuenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTextDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(752, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(221, 221, 221)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNombreCon)
                                    .addComponent(lTelefonoCon)))
                            .addComponent(lPoblacionFiscal)
                            .addComponent(lDireccion1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextTelefonoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lTelefonoCon2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextTelefonoCon2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lEmailCon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextEmailCon, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextNombreCon, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDepartamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextPoblacionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lProvinciaFiscal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxProvinciaFiscal, 0, 157, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextDireccionFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextCodPostal, jTextCodPostalFiscal});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumero)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDNI)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTipo)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(lRegimen)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPoblacion)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProvincia)
                    .addComponent(jLabel14)
                    .addComponent(lCodPostal)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefono2)
                    .addComponent(jTextTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFax)
                    .addComponent(jTextFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEmail)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefono)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumCuenta)
                    .addComponent(jComboBoxFPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDiasPlazo)
                    .addComponent(jTextDiasPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFPago)
                    .addComponent(lPlazo))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lEstado)
                        .addComponent(lFactura1)
                        .addComponent(lFactura)
                        .addComponent(jComboBoxDiaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addComponent(jDateChooserAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPContacto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccion1)
                    .addComponent(jTextCodPostalFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodPostalFiscal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPoblacionFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProvinciaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProvinciaFiscal)
                    .addComponent(lPoblacionFiscal))
                .addGap(23, 23, 23)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPContacto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombreCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDepartamento)
                    .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lNombreCon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelefonoCon)
                    .addComponent(jLabel7)
                    .addComponent(jTextTelefonoCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTelefonoCon2)
                    .addComponent(jTextTelefonoCon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEmailCon)
                    .addComponent(jLabel17)
                    .addComponent(jTextEmailCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonGuardar)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxFPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFPagoActionPerformed
        if (jComboBoxFPago.getSelectedItem().equals("Transferencia"))
        {
            jTextDigito.setEnabled(true);
            jTextEntidad.setEnabled(true);
            jTextSucursal.setEnabled(true);
            jTextNumCuenta.setEnabled(true);
        }
        else
        {
            jTextDigito.setEnabled(false);
            jTextEntidad.setEnabled(false);
            jTextSucursal.setEnabled(false);
            jTextNumCuenta.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxFPagoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        
            System.out.println("\nButton Añadir Cliente");
            Proveedor proveedor = new Proveedor();
            String fecha2="";
            String numCuenta="";
            String nombre = new String(jTextNombre.getText());
            String dni = new String(jTextDNI.getText());
            String regimen = new String(jComboBoxRegimen.getSelectedItem().toString());
            String tipo = new String(jComboBoxTipo.getSelectedItem().toString());
            String direccion = new String(jTextDireccion.getText());
            String codPostal = new String(jTextCodPostal.getText());
            String poblacion = new String(jTextPoblacion.getText());
            String provincia = new String(jComboBoxProvincia.getSelectedItem().toString());
            String telefono = new String(jTextTelefono.getText());
            String telefono2 = new String(jTextTelefono2.getText());
            String fax = new String(jTextFax.getText());
            String email = new String(jTextEmail.getText());
            String entidad = new String(jTextEntidad.getText());
            String sucursal = new String(jTextSucursal.getText());
            String digito = new String(jTextDigito.getText());
            if (!entidad.equals(""))
            {
                numCuenta = new String(entidad+"/"+sucursal+"/"+digito+"/"+jTextNumCuenta.getText());
            }
            String plazo = new String(jComboBoxPlazo.getSelectedItem().toString());
            String diasPlazo = new String(jTextDiasPlazo.getText());
            int dPlazo = 0;
            if (!diasPlazo.equals(""))
            {
                dPlazo = Integer.valueOf(diasPlazo);
            }
            String fPago = new String(Integer.valueOf(jComboBoxFPago.getSelectedIndex()+1).toString());
            String estado = new String(jComboBoxEstado.getSelectedItem().toString());
            String diaFactura = new String(jComboBoxDiaFactura.getSelectedItem().toString());
            String nombreContacto = new String(jTextNombreCon.getText());
            String telefContacto = new String(jTextTelefonoCon.getText());
            String telefContacto2 = new String(jTextTelefonoCon2.getText());
            String emailContacto = new String(jTextEmailCon.getText());
            String fDepartamento = new String(Integer.valueOf(jComboBoxDepartamento.getSelectedIndex()+1).toString());
            String departamento = new String(jComboBoxDepartamento.getSelectedItem().toString());
            String direccionFiscal = new String(jTextDireccionFiscal.getText());
            String poblacionFiscal = new String(jTextPoblacionFiscal.getText());
            String provinciaFiscal = new String(jComboBoxProvinciaFiscal.getSelectedItem().toString());
            String codPostalFiscal = new String(jTextCodPostalFiscal.getText());

            Calendar fechaCalendar = jDateChooserAlta.getCalendar();

            if (fechaCalendar!=null)
            {
                Date fecha = fechaCalendar.getTime();
                SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
                fecha2=formatoDeFecha.format(fecha);
            }

            if (!Utilidades.campoObligatorio(nombre,"nombre").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(nombre,"nombre"));
            }
            else if (!Utilidades.campoObligatorio(dni,"DNI").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(dni,"DNI"));
            }
            else if (!Utilidades.campoObligatorio(direccion,"Direccion").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(direccion,"Direccion"));
            }
            else if (!Utilidades.campoObligatorio(poblacion,"Poblacion").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(poblacion,"Poblacion"));
            }
            else if (!Utilidades.campoObligatorio(provincia,"Provincia").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(provincia,"Provincia"));
            }
            else if (!Utilidades.campoObligatorioCombo(departamento,"Departamento").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorioCombo(departamento,"Departamento"));
            }
            else if (!Utilidades.campoObligatorio(telefono,"telefono").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(telefono,"telefono"));
            }
            else if (!Utilidades.campoObligatorio(nombreContacto,"Nombre Contacto").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(nombreContacto,"Nombre Contacto"));
            }
            else if (!Utilidades.campoObligatorio(telefContacto,"Telefono Contacto").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(telefContacto,"Telefono Contacto"));
            }
            else if (!Utilidades.campoObligatorio(emailContacto,"Email Contacto").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(emailContacto,"Email Contacto"));
            }

            //VALIDACION DE FORMATOS
            else if(!Utilidades.formatoCodPostal(codPostal).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCodPostal(codPostal));
            }
             else if(!Utilidades.formatoTelefono9(telefono).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoTelefono9(telefono));
            }
             else if(!Utilidades.formatoFax(fax).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoFax(fax));
            }
            else if(!Utilidades.formatoCorreo(email).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCorreo(email));
            }
            else if(!Utilidades.formatoCorreo(emailContacto).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCorreo(emailContacto));
            }
            else if(!Utilidades.formatoNumerico(diasPlazo).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoNumerico(diasPlazo));
            }
            else if(!Utilidades.formatoCodPostal(codPostalFiscal).equals("OK"))
            {
                ValidarFormatos(Utilidades.formatoCodPostal(codPostalFiscal));
            }
            else if(proveedor.isProveedor(nombre, dni))
            {
                    jButtonGuardar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Ya existe un Proveedor con ese nombre y NIF</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonGuardar.setEnabled(true);
            }
            else
            {
            String query = "INSERT INTO pr_proveedores (pr_fecha, pr_nombre_fiscal, pr_DNI_CIF, pr_regimen, pr_tipo, " +
                                                        "pr_direccion, pr_cod_postal, pr_poblacion, pr_provincia, " +
                                                        "pr_direccion_fiscal, pr_cod_postal_fiscal, pr_poblacion_fiscal, pr_provincia_fiscal, " +
                                                        "pr_telefono, pr_telefono2, pr_fax, pr_email, pr_plazo, pr_dias_plazo, " +
                                                        "fp_id, pr_num_cuenta, pr_estado, pr_dia_factura) VALUES (" +
                                                        "'"+fecha2+"','"+nombre+"', '"+dni+"', '"+regimen+"','"+tipo+"' ,'"+direccion+"', " +
                                                        "'"+codPostal+"' ,'"+poblacion+"' ,'"+provincia+"', '"+direccionFiscal+"', " +
                                                        "'"+codPostalFiscal+"', '"+poblacionFiscal+"', '"+provinciaFiscal+"','"+telefono+"', " +
                                                        "'"+telefono2+"', '"+fax+"', '"+email+"','"+plazo+"','"+dPlazo+"', '"+fPago+"', " +
                                                        "'"+numCuenta+"','"+estado+"', '"+diaFactura+"')";

                System.out.println(query);
                CSDesktop.datos = new DbConnection();
                boolean rs = CSDesktop.datos.manipuladorDatos(query);
                System.out.println(rs);
                if(rs)
                {
                    jButtonGuardar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonGuardar.setEnabled(true);
                    //this.setVisible(true);
                }
                else
                {
                    query = "select distinct last_insert_id() from pr_proveedores";
                    String pr_id = "";
                    ResultSet rs2 = CSDesktop.datos.select(query);
                    try {
                           if (rs2.first())
                            {
                                pr_id = Integer.valueOf(rs2.getInt("last_insert_id()")).toString();
                                //System.out.println(rs2.getInt("last_insert_id()"));
                                String queryCon = "INSERT INTO cp_contactos_proveedor (cp_nombre, cp_telefono, cp_telefono2, cp_email, pr_id, dp_id) "+
                                                  "VALUES ('"+nombreContacto+"','"+telefContacto+"','"+telefContacto2+"','"+emailContacto+"', "+
                                                  "'"+pr_id+"', '"+fDepartamento+"')";

                                System.out.println(queryCon);
                                boolean rsCon = CSDesktop.datos.manipuladorDatos(queryCon);
                                System.out.println(queryCon);
                                if(rsCon)
                                {
                                    jButtonGuardar.setEnabled(false);
                                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                                    JOptionPane.showMessageDialog(null,errorFields);
                                    jButtonGuardar.setEnabled(true);
                                }
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(CSAnyadirProveedor.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    //Controlar posible error
                    //Creamos las tarifas de la plantilla
                    crearTarifasProveedor(pr_id);
                    //Creamos los servicios de la plantilla
                    crearServiciosProveedor(pr_id);

                    jButtonGuardar.setEnabled(false);
                    JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>Los datos se han guardado correctamente.</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,mensaje);
                    jButtonGuardar.setEnabled(true);
                    CSDesktop.NuevoProveedor.dispose();
                    CSDesktop.menuNuevoProveedor.setEnabled(true);
                }
            }
    }//GEN-LAST:event_jButtonGuardarActionPerformed
    public Dimension getPreferredSize()
   {
      return new Dimension( 850,600 );
   }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        CSDesktop.NuevoProveedor.dispose();
        CSDesktop.menuNuevoProveedor.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreFocusLost
       String nombreM = jTextNombre.getText().toUpperCase();
       jTextNombre.setText(nombreM);
    }//GEN-LAST:event_jTextNombreFocusLost

    private void jTextDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDNIFocusLost
       String DNIM = jTextDNI.getText().toUpperCase();
       jTextDNI.setText(DNIM);
    }//GEN-LAST:event_jTextDNIFocusLost

    private void jTextDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionFocusLost
       String DireccionM = jTextDireccion.getText().toUpperCase();
       jTextDireccion.setText(DireccionM);
    }//GEN-LAST:event_jTextDireccionFocusLost

    private void jTextPoblacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionFocusLost
       String PoblacionM = jTextPoblacion.getText().toUpperCase();
       jTextPoblacion.setText(PoblacionM);
    }//GEN-LAST:event_jTextPoblacionFocusLost

    private void jTextEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailFocusLost
       String MailM = jTextEmail.getText().toUpperCase();
       jTextEmail.setText(MailM);
    }//GEN-LAST:event_jTextEmailFocusLost

    private void jTextNombreConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreConFocusLost
       String NombreConM = jTextNombreCon.getText().toUpperCase();
       jTextNombreCon.setText(NombreConM);
    }//GEN-LAST:event_jTextNombreConFocusLost

    private void jTextEmailConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmailConFocusLost
       String MailConM = jTextEmailCon.getText().toUpperCase();
       jTextEmailCon.setText(MailConM);
    }//GEN-LAST:event_jTextEmailConFocusLost

    private void jComboBoxPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlazoActionPerformed
        if (jComboBoxPlazo.getSelectedItem().equals("Especial"))
        {
            jTextDiasPlazo.setEnabled(true);
        }
        else
        {
            jTextDiasPlazo.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxPlazoActionPerformed

    private void jComboBoxDiaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDiaFacturaActionPerformed

    private void jTextFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFaxActionPerformed

    private void jTextDireccionFiscalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionFiscalFocusLost
        String DireccionFiscalConM = jTextDireccionFiscal.getText().toUpperCase();
        jTextDireccionFiscal.setText(DireccionFiscalConM);
}//GEN-LAST:event_jTextDireccionFiscalFocusLost

    private void jTextPoblacionFiscalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionFiscalFocusLost
        String PoblacionFiscalConM = jTextPoblacionFiscal.getText().toUpperCase();
        jTextPoblacionFiscal.setText(PoblacionFiscalConM);
}//GEN-LAST:event_jTextPoblacionFiscalFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox jComboBoxDepartamento;
    private javax.swing.JComboBox jComboBoxDiaFactura;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxFPago;
    private javax.swing.JComboBox jComboBoxPlazo;
    private javax.swing.JComboBox jComboBoxProvincia;
    private javax.swing.JComboBox jComboBoxProvinciaFiscal;
    private javax.swing.JComboBox jComboBoxRegimen;
    private javax.swing.JComboBox jComboBoxTipo;
    private com.toedter.calendar.JDateChooser jDateChooserAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextCodPostal;
    private javax.swing.JTextField jTextCodPostalFiscal;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextDiasPlazo;
    private javax.swing.JTextField jTextDigito;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextDireccionFiscal;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEmailCon;
    private javax.swing.JTextField jTextEntidad;
    private javax.swing.JTextField jTextFax;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNombreCon;
    private javax.swing.JTextField jTextNumCuenta;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPoblacion;
    private javax.swing.JTextField jTextPoblacionFiscal;
    private javax.swing.JTextField jTextSucursal;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JTextField jTextTelefono2;
    private javax.swing.JTextField jTextTelefonoCon;
    private javax.swing.JTextField jTextTelefonoCon2;
    private javax.swing.JLabel lCodPostal;
    private javax.swing.JLabel lCodPostalFiscal;
    private javax.swing.JLabel lDNI;
    private javax.swing.JLabel lDepartamento;
    private javax.swing.JLabel lDiasPlazo;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lDireccion1;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEmailCon;
    private javax.swing.JLabel lEstado;
    private javax.swing.JLabel lFPago;
    private javax.swing.JLabel lFactura;
    private javax.swing.JLabel lFactura1;
    private javax.swing.JLabel lFax;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lNombreCon;
    private javax.swing.JLabel lNumCuenta;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lPContacto;
    private javax.swing.JLabel lPContacto1;
    private javax.swing.JLabel lPlazo;
    private javax.swing.JLabel lPoblacion;
    private javax.swing.JLabel lPoblacionFiscal;
    private javax.swing.JLabel lProvincia;
    private javax.swing.JLabel lProvinciaFiscal;
    private javax.swing.JLabel lRegimen;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel lTelefono2;
    private javax.swing.JLabel lTelefonoCon;
    private javax.swing.JLabel lTelefonoCon2;
    private javax.swing.JLabel lTipo;
    // End of variables declaration//GEN-END:variables

    /**
     * Función para la validación de los campos
     * @param accion
     */
    public void ValidarFormatos(String accion)
    {
         jButtonGuardar.setEnabled(false);
         JLabel errorFields = new JLabel(accion);
         JOptionPane.showMessageDialog(null,errorFields);
         jButtonGuardar.setEnabled(true);
    }

     /**
     * FunciÃ³n para sacar todas las formas de pago de la bd
     * @return
     * @throws SQLException
     */
    private void getFPagoProveedores() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT fp_id, fp_tipo FROM fp_forma_pago");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("fp_tipo");
           
             jComboBoxFPago.addItem(valor);               
             jComboBoxFPago.setSelectedIndex(0);

            j++;
        }
     }

    /**
     * Función que selecciona los datos de departamentos de la bd
     * @throws SQLException
     */
    private void getDepartamentoContacto() throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select("SELECT dp_id, dp_nombre FROM dp_departamentos");
        int j = 0;
        String valor = "";
        while(rs.next())
        {
            valor = rs.getString("dp_nombre");

            jComboBoxDepartamento.addItem(valor);
            jComboBoxDepartamento.setSelectedIndex(0);

            j++;
        }
     }

    /**
     * Insertar las tarifas del proveedor desde el proveedor de plantilla
     * @param proveedor
     */
    public void crearTarifasProveedor(String idProveedor)
    {
        String query = "SELECT * FROM tp_tarifas_proveedores WHERE pr_id = 1";

        ResultSet rs = CSDesktop.datos.select(query);
        try {

            DbConnection da = new DbConnection();
            while (rs.next())
            {
                   boolean rsTp = true;
                   int tp_id = 1;
                    String servicio = rs.getString("tp_servicio");
                    String servicioOrigen = rs.getString("tp_servicio_origen");
                    String servicioDestino = rs.getString("tp_servicio_destino");
                    String soporte = rs.getString("tp_soporte");
                    Date fechaDesde = rs.getDate("tp_fecha_desde");
                    Date fechaHasta = rs.getDate("tp_fecha_hasta");
                    String incremento = rs.getString("tp_incremento");
                    String tarifa = rs.getString("tp_tarifa");

                   String queryTp = "INSERT INTO tp_tarifas_proveedores (tp_servicio, tp_servicio_origen, tp_servicio_destino, " +
                   "tp_soporte, tp_fecha_desde, tp_fecha_hasta, tp_incremento, tp_tarifa, pr_id) " +
                   "VALUES ('" + servicio + "', '" + servicioOrigen + "', '" + servicioDestino + "', " +
                   "'" + soporte + "', '" + fechaDesde + "','" + fechaHasta + "', " +
                   ""+ incremento + ", "+ tarifa + ", "+ idProveedor+")" ;

                   System.out.println(queryTp);
                   rsTp = da.manipuladorDatos(queryTp);
                   if(rsTp)
                   {
                        jButtonGuardar.setEnabled(false);
                        JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar las tarifas en la base de datos</FONT></HTML>");
                        JOptionPane.showMessageDialog(null,errorFields);
                        jButtonGuardar.setEnabled(true);
                   }
            }
            da.cerrarConexion();
            rs.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CSEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * Insertar los servicios especiales del proveedor desde el proveedor de plantilla
     * @param proveedor
     */
    public void crearServiciosProveedor(String idProveedor)
    {
        String query = "SELECT * FROM sp_servicios_proveedores WHERE pr_id = 1";

        ResultSet rs = CSDesktop.datos.select(query);
        try {

            DbConnection se = new DbConnection();
            while (rs.next())
            {
                boolean rsSe = true;

                String todoterreno = rs.getString("sp_todoterreno");
                String industrial = rs.getString("sp_industrial");
                String furgonetas = rs.getString("sp_furgonetas");
                String furgones = rs.getString("sp_furgones");
                String lavadoEx = rs.getString("sp_lavado_exterior");
                String lavadoExIn = rs.getString("sp_lavado_exin");
                String lavadoInt = rs.getString("sp_lavado_integral");
                String lavadoIE4 = rs.getString("sp_int_ext_cuatro");
                String lavadoIntegral4 = rs.getString("sp_integral_cuatro");
                String lavadoIEIndustrial = rs.getString("sp_int_ext_industrial");
                String lavadoIntInd = rs.getString("sp_integral_industrial");
                String desrotularPegaFacil = rs.getString("sp_desrotular_peg_facil");
                String desrotularPegaNormal = rs.getString("sp_desrotular_peg_normal");
                String desrotularPegaDificil = rs.getString("sp_desrotular_peg_dificil");
                String rotularPegaFacil = rs.getString("sp_rotular_peg_facil");
                String rotularPegaNormal = rs.getString("sp_rotular_peg_normal");
                String rotularPegaDificil = rs.getString("sp_rotular_peg_dificil");
                String lavadoDomEx = rs.getString("sp_ldom_exterior");
                String lavadoDomExIn = rs.getString("sp_ldom_exin");
                String lavadoDomInt = rs.getString("sp_ldom_integral");
                String lavadoDomIE4 = rs.getString("sp_ldom_int_ext_cuatro");
                String lavadoDomIntegral4 = rs.getString("sp_ldom_integral_cuatro");
                String lavadoDomIEIndustrial = rs.getString("sp_ldom_int_ext_industrial");
                String lavadoDomIntInd = rs.getString("sp_ldom_integral_industrial");
                String itv = rs.getString("sp_itv");
                String preItv = rs.getString("sp_pre_itv");
                String itvPreItv = rs.getString("sp_itv_pre_itv");
                String idaVuelta = rs.getString("sp_ida_vuelta");
                String entradaCampa = rs.getString("sp_entrada_campa");
                String campa = rs.getString("sp_campa");
                String peritacion = rs.getString("sp_peritacion");
                String mOMecanicaChapa = rs.getString("sp_mo_mecanica_chapa");
                String chequeo = rs.getString("sp_chequeo");
                String repostaje = rs.getString("sp_repostaje");
                String suplemento = rs.getString("sp_suplemento");
                String urgente = rs.getString("sp_urgente");
                String fecha_desde = rs.getString("sp_fecha_desde");
                String fecha_hasta = rs.getString("sp_fecha_hasta");

                String querySe  = "INSERT INTO sp_servicios_proveedores (sp_todoterreno, sp_industrial, sp_furgonetas, sp_furgones, " +
                "sp_lavado_exterior, sp_lavado_exin, sp_lavado_integral, sp_int_ext_cuatro, sp_integral_cuatro, " +
                "sp_int_ext_industrial, sp_integral_industrial, sp_desrotular_peg_facil, sp_desrotular_peg_normal, " +
                "sp_desrotular_peg_dificil, sp_rotular_peg_facil, sp_rotular_peg_normal, sp_rotular_peg_dificil, " +
                "sp_ldom_exterior, sp_ldom_exin, sp_ldom_integral, sp_ldom_int_ext_cuatro, sp_ldom_integral_cuatro, " +
                "sp_ldom_int_ext_industrial, sp_ldom_integral_industrial, sp_itv, sp_pre_itv, sp_itv_pre_itv, " +
                "sp_ida_vuelta, sp_entrada_campa, sp_campa, sp_peritacion, sp_mo_mecanica_chapa, sp_chequeo, " +
                "sp_repostaje, sp_suplemento, sp_urgente, pr_id, sp_fecha_desde, sp_fecha_hasta) " +
                "VALUES ('"+todoterreno+"', '"+industrial+"', '"+furgonetas+"', '"+furgones+"', '"+lavadoEx+"', " +
                "'"+lavadoExIn+"', '"+lavadoInt+"', '"+lavadoIE4+"', '"+lavadoIntegral4+"', '"+lavadoIEIndustrial+"', " +
                "'"+lavadoIntInd+"', '"+desrotularPegaFacil+"', '"+desrotularPegaNormal+"', '"+desrotularPegaDificil+"', " +
                "'"+rotularPegaFacil+"', '"+rotularPegaNormal+"', '"+rotularPegaDificil+"', '"+lavadoDomEx+"', " +
                "'"+lavadoDomExIn+"', '"+lavadoDomInt+"', '"+lavadoDomIE4+"', '"+lavadoDomIntegral4+"', '"+lavadoDomIEIndustrial+"', " +
                "'"+lavadoDomIntInd+"', '"+itv+"', '"+preItv+"', '"+itvPreItv+"', '"+idaVuelta+"', '"+entradaCampa+"', " +
                "'"+campa+"', '"+peritacion+"', '"+mOMecanicaChapa+"', '"+chequeo+"', '"+repostaje+"', '"+suplemento+"', " +
                "'"+urgente+"', '"+ idProveedor+"', '"+ fecha_desde+"', '"+ fecha_hasta+"') ";

                System.out.println(querySe);
                rsSe = se.manipuladorDatos(querySe);
                if(rsSe)
                {
                    jButtonGuardar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar los servicios especiales en la base de datos</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonGuardar.setEnabled(true);
                }
            }
            se.cerrarConexion();
            rs.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CSEditarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Función para la limitación de los campos
     */
     private void limitacionesCampos()
    {
        LimitadorDeDocumento limitadorDNI= new LimitadorDeDocumento(10);
        jTextDNI.setDocument(limitadorDNI);
        LimitadorDeDocumento limitador5= new LimitadorDeDocumento(5);
        jTextCodPostal.setDocument(limitador5);
        LimitadorDeDocumento limitadorNombre= new LimitadorDeDocumento(50);
        jTextNombre.setDocument(limitadorNombre);
        LimitadorDeDocumento limitadorEmail= new LimitadorDeDocumento(50);
        jTextEmail.setDocument(limitadorEmail);
        LimitadorDeDocumento limitadorNomC= new LimitadorDeDocumento(50);
        jTextNombreCon.setDocument(limitadorNomC);
        LimitadorDeDocumento limitadorEmailC= new LimitadorDeDocumento(50);
        jTextEmailCon.setDocument(limitadorEmailC);
        LimitadorDeDocumento limitadorEntidad= new LimitadorDeDocumento(4);
        jTextEntidad.setDocument(limitadorEntidad);
        LimitadorDeDocumento limitadorSucursal= new LimitadorDeDocumento(4);
        jTextSucursal.setDocument(limitadorSucursal);
        LimitadorDeDocumento limitadorDigito= new LimitadorDeDocumento(2);
        jTextDigito.setDocument(limitadorDigito);
        LimitadorDeDocumento limitadorNumC= new LimitadorDeDocumento(10);
        jTextNumCuenta.setDocument(limitadorNumC);
        LimitadorDeDocumento limitadorCPFiscal= new LimitadorDeDocumento(5);
        jTextCodPostal.setDocument(limitadorCPFiscal);
     }
}