/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABBuscarPedido.java
 *
 * Created on 07-oct-2009, 17:50:47
 */

package neg;

import utils.LimitadorDeDocumento;
import data.Cliente;
import data.DbConnection;
import data.Proveedor;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JInternalFrame;
import utils.Utilidades;

/**
 *
 * @author depr73
 */
public class CSBuscarPedido extends javax.swing.JPanel {
    int clienteID=0;
    int proveedorID=0;
    private String fecha2;
    private DbConnection datos;
    /** Creates new form ABBuscarPedido */
    public CSBuscarPedido() {

        CSDesktop.menuBuscarPedido.setEnabled(false);
        initComponents();
        limitacionesCampos();

         KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonBuscar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };

        for (int k = 0; k < this.getComponents().length; k ++)
        {
            if (this.getComponents()[k] != jComboBoxProvinciaOrigen &&
                this.getComponents()[k] != jComboBoxProvinciaDestino &&
                this.getComponents()[k] != jComboBoxServicio &&
                this.getComponents()[k] != jComboBoxServicioFMad &&
                this.getComponents()[k] != jComboBoxSoporte &&
                this.getComponents()[k] != jComboBoxEstado)
            {
                this.getComponents()[k].addKeyListener(l);
            }
        }
        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuscar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jComboVehiculo = new javax.swing.JComboBox();
        lServicio = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lDestino1 = new javax.swing.JLabel();
        lSoporte = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        lFuMadrid = new javax.swing.JLabel();
        lMatricula = new javax.swing.JLabel();
        lPoblacionDestino = new javax.swing.JLabel();
        lVehiculo = new javax.swing.JLabel();
        jCheckBoxFMadrid = new javax.swing.JCheckBox();
        jToggleButtonCliente = new javax.swing.JToggleButton();
        lCliente = new javax.swing.JLabel();
        jTextDireccionOrigen1 = new javax.swing.JTextField();
        lOrigen1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lDireccionOrigen1 = new javax.swing.JLabel();
        jToggleButtonProveedor = new javax.swing.JToggleButton();
        lProvinciaOrigen = new javax.swing.JLabel();
        jTextProveedor = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        jTextPoblacionOrigen = new javax.swing.JTextField();
        jComboBoxServicio = new javax.swing.JComboBox();
        lDireccionDestino1 = new javax.swing.JLabel();
        lEstado3 = new javax.swing.JLabel();
        lCodPostalDestino = new javax.swing.JLabel();
        jComboBoxProvinciaDestino = new javax.swing.JComboBox();
        jTextDireccionDestino1 = new javax.swing.JTextField();
        lFechaIni = new javax.swing.JLabel();
        jTextPoblacionDestino = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox();
        jTextCodPostalOrigen = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jComboBoxProvinciaOrigen = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        lCodPostalOrigen = new javax.swing.JLabel();
        jTextCodPostalDestino = new javax.swing.JTextField();
        jTextNumero = new javax.swing.JTextField();
        lProveedor = new javax.swing.JLabel();
        jTextCliente = new javax.swing.JTextField();
        lPoblacionOrigen = new javax.swing.JLabel();
        lProvinciaDestino = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        jComboBoxSoporte = new javax.swing.JComboBox();
        lServicioFMad = new javax.swing.JLabel();
        jComboBoxServicioFMad = new javax.swing.JComboBox();
        lFechaFin = new javax.swing.JLabel();
        jDateFechaFin = new com.toedter.calendar.JDateChooser();

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setName("jButtonBuscar"); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboVehiculo.setBackground(new java.awt.Color(228, 229, 255));
        jComboVehiculo.setForeground(new java.awt.Color(0, 0, 100));
        jComboVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "Turismo", "Industrial", "4x4", "Monovolumen" }));
        jComboVehiculo.setName("jComboVehiculo"); // NOI18N

        lServicio.setForeground(new java.awt.Color(0, 0, 100));
        lServicio.setText("Servicio");
        lServicio.setName("lServicio"); // NOI18N

        jSeparator4.setName("jSeparator4"); // NOI18N

        lDestino1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lDestino1.setForeground(new java.awt.Color(170, 16, 4));
        lDestino1.setText("DATOS DEL DESTINO");
        lDestino1.setName("lDestino1"); // NOI18N

        lSoporte.setForeground(new java.awt.Color(0, 0, 100));
        lSoporte.setText("Soporte");
        lSoporte.setName("lSoporte"); // NOI18N

        jTextMatricula.setName("jTextMatricula"); // NOI18N
        jTextMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextMatriculaFocusLost(evt);
            }
        });

        lFuMadrid.setForeground(new java.awt.Color(0, 0, 100));
        lFuMadrid.setText("Fuera de Madrid");
        lFuMadrid.setName("lFuMadrid"); // NOI18N

        lMatricula.setForeground(new java.awt.Color(0, 0, 100));
        lMatricula.setText("Matrícula");
        lMatricula.setName("lMatricula"); // NOI18N

        lPoblacionDestino.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionDestino.setText("Población");
        lPoblacionDestino.setName("lPoblacionDestino"); // NOI18N

        lVehiculo.setForeground(new java.awt.Color(0, 0, 100));
        lVehiculo.setText("Tipo de vehículo");
        lVehiculo.setName("lVehiculo"); // NOI18N

        jCheckBoxFMadrid.setAlignmentX(0.5F);
        jCheckBoxFMadrid.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jCheckBoxFMadrid.setMaximumSize(new java.awt.Dimension(45, 45));
        jCheckBoxFMadrid.setMinimumSize(new java.awt.Dimension(45, 45));
        jCheckBoxFMadrid.setName("jCheckBoxFMadrid"); // NOI18N
        jCheckBoxFMadrid.setPreferredSize(new java.awt.Dimension(60, 60));
        jCheckBoxFMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFMadridActionPerformed(evt);
            }
        });

        jToggleButtonCliente.setText("Buscar Cliente");
        jToggleButtonCliente.setName("jToggleButtonCliente"); // NOI18N
        jToggleButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonClienteActionPerformed(evt);
            }
        });

        lCliente.setForeground(new java.awt.Color(0, 0, 100));
        lCliente.setText("Cliente");
        lCliente.setName("lCliente"); // NOI18N

        jTextDireccionOrigen1.setName("jTextDireccionOrigen1"); // NOI18N
        jTextDireccionOrigen1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionOrigen1FocusLost(evt);
            }
        });

        lOrigen1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lOrigen1.setForeground(new java.awt.Color(170, 16, 4));
        lOrigen1.setText("DATOS DEL ORIGEN");
        lOrigen1.setName("lOrigen1"); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator1.setName("jSeparator1"); // NOI18N

        lDireccionOrigen1.setForeground(new java.awt.Color(0, 0, 100));
        lDireccionOrigen1.setText("Dirección");
        lDireccionOrigen1.setName("lDireccionOrigen1"); // NOI18N

        jToggleButtonProveedor.setText("Buscar Proveedor");
        jToggleButtonProveedor.setName("jToggleButtonProveedor"); // NOI18N
        jToggleButtonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonProveedorActionPerformed(evt);
            }
        });

        lProvinciaOrigen.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaOrigen.setText("Provincia");
        lProvinciaOrigen.setName("lProvinciaOrigen"); // NOI18N

        jTextProveedor.setEditable(false);
        jTextProveedor.setName("jTextProveedor"); // NOI18N

        lNumero.setForeground(new java.awt.Color(0, 0, 100));
        lNumero.setText("Núm. de pedido PE/");
        lNumero.setName("lNumero"); // NOI18N

        jTextPoblacionOrigen.setName("jTextPoblacionOrigen"); // NOI18N
        jTextPoblacionOrigen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionOrigenFocusLost(evt);
            }
        });

        jComboBoxServicio.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxServicio.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxServicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Urbano", "Interurbano", "Provincial", "Urbano ITV", "Especial" }));
        jComboBoxServicio.setName("jComboBoxServicio"); // NOI18N

        lDireccionDestino1.setForeground(new java.awt.Color(0, 0, 100));
        lDireccionDestino1.setText("Dirección");
        lDireccionDestino1.setName("lDireccionDestino1"); // NOI18N

        lEstado3.setForeground(new java.awt.Color(0, 0, 100));
        lEstado3.setText("Estado");
        lEstado3.setName("lEstado3"); // NOI18N

        lCodPostalDestino.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostalDestino.setText("Cód. Postal");
        lCodPostalDestino.setName("lCodPostalDestino"); // NOI18N

        jComboBoxProvinciaDestino.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaDestino.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERíA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CORDOBA", "CORUÑA, A", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPUZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MALAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PALMAS, LAS", "PONTEVEDRA", "RIOJA, LA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaDestino.setName("jComboBoxProvinciaDestino"); // NOI18N

        jTextDireccionDestino1.setName("jTextDireccionDestino1"); // NOI18N
        jTextDireccionDestino1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDireccionDestino1FocusLost(evt);
            }
        });

        lFechaIni.setForeground(new java.awt.Color(0, 0, 100));
        lFechaIni.setText("Fecha ini");
        lFechaIni.setName("lFechaIni"); // NOI18N

        jTextPoblacionDestino.setName("jTextPoblacionDestino"); // NOI18N
        jTextPoblacionDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextPoblacionDestinoFocusLost(evt);
            }
        });

        jComboBoxEstado.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxEstado.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo", "Pendiente" }));
        jComboBoxEstado.setName("jComboBoxEstado"); // NOI18N

        jTextCodPostalOrigen.setName("jTextCodPostalOrigen"); // NOI18N

        jSeparator6.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator6.setName("jSeparator6"); // NOI18N

        jComboBoxProvinciaOrigen.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxProvinciaOrigen.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxProvinciaOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERíA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CORDOBA", "CORUÑA, A", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPUZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MALAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PALMAS, LAS", "PONTEVEDRA", "RIOJA, LA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxProvinciaOrigen.setName("jComboBoxProvinciaOrigen"); // NOI18N

        jSeparator5.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator5.setName("jSeparator5"); // NOI18N

        lCodPostalOrigen.setForeground(new java.awt.Color(0, 0, 100));
        lCodPostalOrigen.setText("Cód. Postal");
        lCodPostalOrigen.setName("lCodPostalOrigen"); // NOI18N

        jTextCodPostalDestino.setName("jTextCodPostalDestino"); // NOI18N

        jTextNumero.setName("jTextNumero"); // NOI18N

        lProveedor.setForeground(new java.awt.Color(0, 0, 100));
        lProveedor.setText("Proveedor");
        lProveedor.setName("lProveedor"); // NOI18N

        jTextCliente.setEditable(false);
        jTextCliente.setName("jTextCliente"); // NOI18N

        lPoblacionOrigen.setForeground(new java.awt.Color(0, 0, 100));
        lPoblacionOrigen.setText("Población");
        lPoblacionOrigen.setName("lPoblacionOrigen"); // NOI18N

        lProvinciaDestino.setForeground(new java.awt.Color(0, 0, 100));
        lProvinciaDestino.setText("Provincia");
        lProvinciaDestino.setName("lProvinciaDestino"); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator3.setName("jSeparator3"); // NOI18N

        jDateFecha.setDateFormatString("dd-MM-yyyy"); // NOI18N
        jDateFecha.setName("jDateFecha"); // NOI18N

        jComboBoxSoporte.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxSoporte.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxSoporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grúa", "Camión completo", "Conductor", "Tren", "Custodia" }));
        jComboBoxSoporte.setSelectedIndex(2);
        jComboBoxSoporte.setName("jComboBoxSoporte"); // NOI18N

        lServicioFMad.setForeground(new java.awt.Color(0, 0, 100));
        lServicioFMad.setText("Servicio Fuera de Madrid");
        lServicioFMad.setName("lServicioFMad"); // NOI18N

        jComboBoxServicioFMad.setBackground(new java.awt.Color(228, 229, 255));
        jComboBoxServicioFMad.setForeground(new java.awt.Color(0, 0, 100));
        jComboBoxServicioFMad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona", "ÁLAVA", "ALBACETE", "ALICANTE", "ALMERíA", "ASTURIAS", "ÁVILA", "BADAJOZ", "BARCELONA", "BURGOS", "CÁCERES", "CÁDIZ", "CANTABRIA", "CASTELLÓN", "CEUTA", "CIUDAD REAL", "CORDOBA", "CORUÑA, A", "CUENCA", "GIRONA", "GRANADA", "GUADALAJARA", "GUIPUZCOA", "HUELVA", "HUESCA", "ILLES BALEARS", "JAÉN", "LEÓN", "LLEIDA", "LUGO", "MADRID", "MALAGA", "MELILLA", "MURCIA", "NAVARRA", "OURENSE", "PALENCIA", "PALMAS, LAS", "PONTEVEDRA", "RIOJA, LA", "SALAMANCA", "SANTA CRUZ DE TENERIFE", "SEGOVIA", "SEVILLA", "SORIA", "TARRAGONA", "TERUEL", "TOLEDO", "VALENCIA", "VALLADOLID", "VIZCAYA", "ZAMORA", "ZARAGOZA" }));
        jComboBoxServicioFMad.setEnabled(false);
        jComboBoxServicioFMad.setName("jComboBoxServicioFMad"); // NOI18N

        lFechaFin.setForeground(new java.awt.Color(0, 0, 100));
        lFechaFin.setText("Fecha fin");
        lFechaFin.setName("lFechaFin"); // NOI18N

        jDateFechaFin.setDateFormatString("dd-MM-yyyy"); // NOI18N
        jDateFechaFin.setName("jDateFechaFin"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDestino1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lDireccionDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDireccionDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(lPoblacionDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextPoblacionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lCodPostalDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextCodPostalDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lEstado3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lFuMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckBoxFMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(lServicio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBoxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lServicioFMad)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBoxServicioFMad, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23)
                                    .addComponent(lSoporte)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBoxSoporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lVehiculo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(lMatricula)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14)
                                    .addComponent(lProveedor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jToggleButtonProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lFechaIni)
                                        .addGap(3, 3, 3)
                                        .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lFechaFin)
                                        .addGap(5, 5, 5)
                                        .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lOrigen1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lDireccionOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextDireccionOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(22, 22, 22)
                                            .addComponent(lPoblacionOrigen)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextPoblacionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lCodPostalOrigen)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextCodPostalOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lFechaIni)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButtonCliente)
                        .addComponent(lCliente))
                    .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lOrigen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccionOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCodPostalOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPoblacionOrigen)
                    .addComponent(jTextPoblacionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccionOrigen1)
                    .addComponent(jComboBoxProvinciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodPostalOrigen)
                    .addComponent(lProvinciaOrigen))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDestino1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDireccionDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPoblacionDestino)
                    .addComponent(jTextPoblacionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDireccionDestino1)
                    .addComponent(jTextCodPostalDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCodPostalDestino)
                    .addComponent(lProvinciaDestino)
                    .addComponent(jComboBoxProvinciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lSoporte)
                            .addComponent(jComboBoxSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lServicioFMad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxServicioFMad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBoxFMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lFuMadrid)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonProveedor)
                    .addComponent(jTextProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProveedor)
                    .addComponent(lVehiculo)
                    .addComponent(jComboVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMatricula)
                    .addComponent(jTextMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEstado3)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        System.out.println("\njButtonGuardar_actionPerformed(ActionEvent e) called.");

        String fechaI="";
        String fechaF="";

        int numeroN=0;
        String numero = new String(jTextNumero.getText());
        if(!numero.equals(""))
           numeroN=Integer.valueOf(numero);

         Calendar fechaCalendar = jDateFecha.getCalendar();
        //String fecha = ConvertirFechaString(fechaCalendar);
        if (fechaCalendar!=null)
        {
            Date fecha = fechaCalendar.getTime();
            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
            fechaI=formatoDeFecha.format(fecha);
        }

        fechaCalendar = jDateFechaFin.getCalendar();
        //String fecha = ConvertirFechaString(fechaCalendar);
        if (fechaCalendar!=null)
        {
            Date fecha = fechaCalendar.getTime();
            SimpleDateFormat formatoDeFecha = new SimpleDateFormat("yyyy-MM-dd");
            fechaF=formatoDeFecha.format(fecha);
        }
        String cliente=new String(jTextCliente.getText());
        String direccionOrigen=new String(jTextDireccionOrigen1.getText());
        String poblacionOrigen=new String(jTextPoblacionOrigen.getText());
        String provinciaOrigen=new String(jComboBoxProvinciaOrigen.getSelectedItem().toString());
        String codPostalOrigen=new String(jTextCodPostalOrigen.getText());
        String direccionDestino=new String(jTextDireccionDestino1.getText());
        String poblacionDestino=new String(jTextPoblacionDestino.getText());
        String provinciaDestino=new String(jComboBoxProvinciaDestino.getSelectedItem().toString());
        String codPostalDestino=new String(jTextCodPostalDestino.getText());
        boolean fueraMad = new Boolean(jCheckBoxFMadrid.isSelected());
        String servicio=new String(jComboBoxServicio.getSelectedItem().toString());
        String servicioFMad=new String(jComboBoxServicioFMad.getSelectedItem().toString());
        String soporte=new String(jComboBoxSoporte.getSelectedItem().toString());
        String vehiculo=new String(jComboVehiculo.getSelectedItem().toString());
        String matricula=new String(jTextMatricula.getText());
        String proveedor=new String(jTextProveedor.getText());
        String estado=new String(jComboBoxEstado.getSelectedItem().toString());

        boolean and = false;
        String query = "SELECT * FROM pe_pedidos pe ";


        if(!cliente.equals("") && !proveedor.equals(""))
        {
            Cliente cliente2=new Cliente();
            clienteID=cliente2.getClienteID(cliente);
            Proveedor proveedor2=new Proveedor();
            proveedorID=proveedor2.getProveedorID(proveedor);
            
            query = query + ", pc_pedidos_clientes pc, pp_pedidos_proveedores pp WHERE pe.pe_num = pc.pe_num AND"+ 
                    " pe.pe_num = pp.pe_num AND pc.cl_id = "+clienteID+" AND pp.pr_id = "+proveedorID;
            and=true;

        }
        else if(!cliente.equals(""))
        {
            Cliente cliente2=new Cliente();
            clienteID=cliente2.getClienteID(cliente);

            query = query + ", pc_pedidos_clientes pc WHERE pe.pe_num = pc.pe_num AND pc.cl_id = "+clienteID;
            and=true;
        }
        else if(!proveedor.equals(""))
        {
            Proveedor proveedor2=new Proveedor();
            proveedorID=proveedor2.getProveedorID(proveedor);

            query = query + ", pp_pedidos_proveedores pp WHERE pe.pe_num = pp.pe_num AND pp.pr_id = "+proveedorID;
             and=true;
        }      
        else
        {
            query = query + " WHERE ";
        }
        if(numeroN!=0)
        {
             if (and)
             {
                query = query + " AND pe_num = "+numeroN;
                and=true;
             }
              else
             {
                  query = query + " pe_num = "+numeroN;
                  and = true;
             }
        }
        if ((!fechaI.equals(""))&& (!fechaF.equals("")) )
        {
             if (and)
             {
                 query = query + " AND pe_fecha >='"+fechaI+"' and pe_fecha<='"+fechaF+"'";
             }
             else
             {
                  query = query + " pe_fecha >='"+fechaI+"' and pe_fecha<='"+fechaF+"'";
                  and = true;
             }
        }
        if (!direccionOrigen.equals(""))
        {
             if (and)
             {
                 query = query + " AND pe_direccion_origen='"+direccionOrigen+"'";
             }
             else
             {
                  query = query + " pe_direccion_origen='"+direccionOrigen+"'";
                  and = true;
             }
        }
        if (!poblacionOrigen.equals(""))
        {
             if (and)
             {
                 query = query + " AND pe_poblacion_origen='"+poblacionOrigen+"'";
             }
             else
             {
                  query = query + " pe_poblacion_origen='"+poblacionOrigen+"'";
                  and = true;
             }
        }
        if (!provinciaOrigen.equals("Selecciona"))
        {
             if (and)
             {
                 query = query + " AND pe_provincia_origen='"+provinciaOrigen+"'";
             }
             else
             {
                  query = query + " pe_provincia_origen='"+provinciaOrigen+"'";
                  and = true;
             }
        }
        if (!codPostalOrigen.equals(""))
        {
             if (and)
             {
                 query = query + " AND pe_cp_origen='"+codPostalOrigen+"'";
             }
             else
             {
                  query = query + " pe_cp_origen='"+codPostalOrigen+"'";
                  and = true;
             }
        }
         if (!direccionDestino.equals(""))
        {
             if (and)
             {
                 query = query + " AND pe_direccion_destino='"+direccionDestino+"'";
             }
             else
             {
                  query = query + " pe_direccion_destino='"+direccionDestino+"'";
                  and = true;
             }
        }
        if (!poblacionDestino.equals(""))
        {
             if (and)
             {
                 query = query + " AND pe_poblacion_destino='"+poblacionDestino+"'";
             }
             else
             {
                  query = query + " pe_poblacion_destino='"+poblacionDestino+"'";
                  and = true;
             }
        }
        if (!provinciaDestino.equals("Selecciona"))
        {
             if (and)
             {
                 query = query + " AND pe_provincia_destino='"+provinciaDestino+"'";
             }
             else
             {
                  query = query + " pe_provincia_destino='"+provinciaDestino+"'";
                  and = true;
             }
        }
        if (!codPostalDestino.equals(""))
        {
             if (and)
             {
                 query = query + " AND pe_cp_destino='"+codPostalDestino+"'";
             }
             else
             {
                  query = query + " pe_cp_destino='"+codPostalDestino+"'";
                  and = true;
             }
        }
        if(!fueraMad)
        {
            if (and)
            {
                query = query + " AND pe_fuera_mad=0 AND pe_servicio='"+servicio+"'";
            }
             else
             {
                  query = query + " pe_fuera_mad=0 AND pe_servicio='"+servicio+"'";
                  and = true;
             }
        }
        else
        {
            if (and)
            {
                query = query + " AND pe_fuera_mad=1 AND pe_servicio='"+servicioFMad+"'";
            }
             else
             {
                  query = query + " pe_fuera_mad=1 AND pe_servicio='"+servicioFMad+"'";
                  and = true;
             }
        }
        if(soporte.equals(""))
        {
            if (and)
            {
                query = query + " AND pe_soporte='"+soporte+"'";
            }
             else
             {
                  query = query + " pe_soporte='"+soporte+"'";
                  and = true;
             }
        }
         if (!vehiculo.equals("Selecciona"))
        {
             if (and)
             {
                 query = query + " AND pe_vehiculo='"+vehiculo+"'";
             }
             else
             {
                  query = query + " pe_vehiculo='"+vehiculo+"'";
                  and = true;
             }
        }
        if (!matricula.equals(""))
        {
             if (and)
             {
                 query = query + " AND pe_matricula='"+matricula+"'";
             }
             else
             {
                  query = query + " pe_matricula='"+matricula+"'";
                  and = true;
             }
        }
        if (estado.equals(""))
        {
             if (and)
             {
                 query = query + " AND pe_estado='"+estado+"'";
             }
             else
             {
                  query = query + " pe_estado='"+estado+"'";
                  and = true;
             }
        }

                System.out.println(query+" ORDER BY pe.pe_num DESC");
                query = query+" ORDER BY pe.pe_num ASC";

                CSResultBuscarPedido resultBuscarCliente = new CSResultBuscarPedido(query);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jCheckBoxFMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFMadridActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxFMadrid.isSelected()) {
            jComboBoxServicio.setEnabled(false);
            jComboBoxServicioFMad.setEnabled(true);
        } else {
            jComboBoxServicio.setEnabled(true);
            jComboBoxServicioFMad.setEnabled(false);
        }
}//GEN-LAST:event_jCheckBoxFMadridActionPerformed

    private void jToggleButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonClienteActionPerformed

        System.out.println("\nBotón Buscar Cliente en Añadir Pedido.");

        String query="select cl_id,cl_nombre,cl_DNI_CIF from cl_clientes order by cl_id";

        CSDesktop.BuscaCliente = new JInternalFrame("Seleccionar Cliente", true, false, false, true );
        // adjuntar panel al panel de contenido del marco interno
        CSSelectCliente panel = new CSSelectCliente(query,jTextCliente);
        CSDesktop.BuscaCliente.getContentPane().add( panel,BorderLayout.CENTER);
        // establecer tama�o de marco interno en el tama�o de su contenido
        CSDesktop.BuscaCliente.pack();
        // adjuntar marco interno al escritorio y mostrarlo
        CSDesktop.elEscritorio.add( CSDesktop.BuscaCliente );
        CSDesktop.BuscaCliente.setLocation(150, 50);
        CSDesktop.BuscaCliente.setVisible( true );
}//GEN-LAST:event_jToggleButtonClienteActionPerformed

    private void jToggleButtonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonProveedorActionPerformed
        System.out.println("\nBotón Buscar Cliente en Añadir Pedido.");

        String query="select pr_id,pr_nombre_fiscal,pr_DNI_CIF from pr_proveedores order by pr_id";

        CSDesktop.BuscaProveedor = new JInternalFrame("Seleccionar Proveedor", true, false, false, true );
        // adjuntar panel al panel de contenido del marco interno
        CSSelectProveedor panel = new CSSelectProveedor(query,jTextProveedor);
        CSDesktop.BuscaProveedor.getContentPane().add( panel,BorderLayout.CENTER);
        // establecer tama�o de marco interno en el tama�o de su contenido
        CSDesktop.BuscaProveedor.pack();
        // adjuntar marco interno al escritorio y mostrarlo
        CSDesktop.elEscritorio.add( CSDesktop.BuscaProveedor );
        CSDesktop.BuscaProveedor.setLocation(150, 50);
        CSDesktop.BuscaProveedor.setVisible( true );
}//GEN-LAST:event_jToggleButtonProveedorActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       CSDesktop.BuscarPedido.dispose();
       CSDesktop.menuBuscarPedido.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextDireccionOrigen1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionOrigen1FocusLost
       String DireccionOrigenM = jTextDireccionOrigen1.getText().toUpperCase();
       jTextDireccionOrigen1.setText(DireccionOrigenM);
    }//GEN-LAST:event_jTextDireccionOrigen1FocusLost

    private void jTextPoblacionOrigenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionOrigenFocusLost
       String PoblacionOrigenM = jTextPoblacionOrigen.getText().toUpperCase();
       jTextPoblacionOrigen.setText(PoblacionOrigenM);
    }//GEN-LAST:event_jTextPoblacionOrigenFocusLost

    private void jTextDireccionDestino1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDireccionDestino1FocusLost
        String DireccionDestinoM = jTextDireccionDestino1.getText().toUpperCase();
       jTextDireccionDestino1.setText(DireccionDestinoM);
    }//GEN-LAST:event_jTextDireccionDestino1FocusLost

    private void jTextPoblacionDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPoblacionDestinoFocusLost
       String PoblacionDestinoM = jTextPoblacionDestino.getText().toUpperCase();
       jTextPoblacionDestino.setText(PoblacionDestinoM);
    }//GEN-LAST:event_jTextPoblacionDestinoFocusLost

    private void jTextMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextMatriculaFocusLost
        String MatriculaM = jTextMatricula.getText().toUpperCase();
       jTextMatricula.setText(MatriculaM);
    }//GEN-LAST:event_jTextMatriculaFocusLost

 public Dimension getPreferredSize()
   {
      return new Dimension( 1020,500 );
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JCheckBox jCheckBoxFMadrid;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxProvinciaDestino;
    private javax.swing.JComboBox jComboBoxProvinciaOrigen;
    private javax.swing.JComboBox jComboBoxServicio;
    private javax.swing.JComboBox jComboBoxServicioFMad;
    private javax.swing.JComboBox jComboBoxSoporte;
    private javax.swing.JComboBox jComboVehiculo;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private com.toedter.calendar.JDateChooser jDateFechaFin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JTextField jTextCliente;
    private javax.swing.JTextField jTextCodPostalDestino;
    private javax.swing.JTextField jTextCodPostalOrigen;
    private javax.swing.JTextField jTextDireccionDestino1;
    private javax.swing.JTextField jTextDireccionOrigen1;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPoblacionDestino;
    private javax.swing.JTextField jTextPoblacionOrigen;
    private javax.swing.JTextField jTextProveedor;
    private javax.swing.JToggleButton jToggleButtonCliente;
    private javax.swing.JToggleButton jToggleButtonProveedor;
    private javax.swing.JLabel lCliente;
    private javax.swing.JLabel lCodPostalDestino;
    private javax.swing.JLabel lCodPostalOrigen;
    private javax.swing.JLabel lDestino1;
    private javax.swing.JLabel lDireccionDestino1;
    private javax.swing.JLabel lDireccionOrigen1;
    private javax.swing.JLabel lEstado3;
    private javax.swing.JLabel lFechaFin;
    private javax.swing.JLabel lFechaIni;
    private javax.swing.JLabel lFuMadrid;
    private javax.swing.JLabel lMatricula;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lOrigen1;
    private javax.swing.JLabel lPoblacionDestino;
    private javax.swing.JLabel lPoblacionOrigen;
    private javax.swing.JLabel lProveedor;
    private javax.swing.JLabel lProvinciaDestino;
    private javax.swing.JLabel lProvinciaOrigen;
    private javax.swing.JLabel lServicio;
    private javax.swing.JLabel lServicioFMad;
    private javax.swing.JLabel lSoporte;
    private javax.swing.JLabel lVehiculo;
    // End of variables declaration//GEN-END:variables


    private void limitacionesCampos()
    {

       LimitadorDeDocumento limitadorPoblacionOrigen= new LimitadorDeDocumento(50);
       jTextPoblacionOrigen.setDocument(limitadorPoblacionOrigen);
       LimitadorDeDocumento limitadorCPOrigen= new LimitadorDeDocumento(5);
       jTextCodPostalOrigen.setDocument(limitadorCPOrigen);
       LimitadorDeDocumento limitadorPoblacionDestino= new LimitadorDeDocumento(50);
       jTextPoblacionDestino.setDocument(limitadorPoblacionDestino);
       LimitadorDeDocumento limitadorCPDestino= new LimitadorDeDocumento(5);
       jTextCodPostalDestino.setDocument(limitadorCPDestino);
       LimitadorDeDocumento limitadorMatricula= new LimitadorDeDocumento(10);
       jTextMatricula.setDocument(limitadorMatricula);

    }
    
}
