/*
 * CSServiciosCliente.java
 *
 * Created on 03-oct-2009, 0:25:10
 */

package neg;

import utils.LimitadorDeDocumento;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author lito
 */
public class CSServicioClienteNew extends javax.swing.JPanel
{
    int cl_id = 0;

    public CSServicioClienteNew(String query, int cliente) throws SQLException
    {
        ResultSet rs = CSDesktop.datos.select(query);

        CSDesktop.EditarClienteNew.setEnabled(false);
        initComponents();
        limitacionesCampos();
        cl_id = cliente;
        int numeroFila = 0;

        try{
            while (rs.next()){
                jTextTurismo.setText(rs.getString("sv_turismo"));
                jTextFLM.setText(rs.getString("sv_flm"));
                jTex4x4.setText(rs.getString("sv_todoterreno"));
                jTextFurgoneta.setText(rs.getString("sv_furgoneta"));
                jTextFurgon.setText(rs.getString("sv_furgon"));
                jTextSuv.setText(rs.getString("sv_suv"));
                jTextEspecial.setText(rs.getString("sv_especial"));
                jTextCaSo.setText(rs.getString("sv_carro_sobredim"));
                jTextMoto.setText(rs.getString("sv_moto"));                
                jTextDias.setText(rs.getString("sv_dias"));
                jTextObservaciones.setText(rs.getString("sv_text_asistencia"));
                jTextObservacionesGe.setText(rs.getString("sv_text_general"));
                numeroFila++;
            }
            rs.close();
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(CSResultBuscarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        CSDesktop.ServicioCliente = new JInternalFrame("Servicios Especiales de Cliente", true, false, false, true );
        CSDesktop.ServicioCliente.getContentPane().add( this, BorderLayout.CENTER );
        CSDesktop.ServicioCliente.pack();
        CSDesktop.ServicioCliente.dispose();
        CSDesktop.elEscritorio.add( CSDesktop.ServicioCliente );
        Dimension pantalla = CSDesktop.elEscritorio.getSize();
        Dimension ventana = CSDesktop.ServicioCliente.getSize();
        CSDesktop.ServicioCliente.setLocation(
           (pantalla.width - ventana.width) / 2,
           (pantalla.height - ventana.height) / 2);
        CSDesktop.ServicioCliente.setVisible( true );
        CSDesktop.ServicioCliente.setSize(381, 775);
         
        KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonModificar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };
        
        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTurismo = new javax.swing.JLabel();
        jTextTurismo = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        lFCorrecion = new javax.swing.JLabel();
        lFLM = new javax.swing.JLabel();
        jTextFLM = new javax.swing.JTextField();
        lFurgoneta = new javax.swing.JLabel();
        jTextFurgoneta = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFurgon = new javax.swing.JTextField();
        lFurgon = new javax.swing.JLabel();
        lSuv = new javax.swing.JLabel();
        jTextDias = new javax.swing.JTextField();
        jTextSuv = new javax.swing.JTextField();
        lFCorrecion3 = new javax.swing.JLabel();
        lDias = new javax.swing.JLabel();
        l4x4 = new javax.swing.JLabel();
        jTex4x4 = new javax.swing.JTextField();
        lEuro28 = new javax.swing.JLabel();
        lEuro29 = new javax.swing.JLabel();
        lEuro30 = new javax.swing.JLabel();
        lEuro31 = new javax.swing.JLabel();
        lEuro32 = new javax.swing.JLabel();
        lEuro33 = new javax.swing.JLabel();
        lEspecial = new javax.swing.JLabel();
        jTextEspecial = new javax.swing.JTextField();
        lEuro34 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextObservaciones = new javax.swing.JTextPane();
        lFCorrecion4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lCarroSobre = new javax.swing.JLabel();
        jTextCaSo = new javax.swing.JTextField();
        lEuro35 = new javax.swing.JLabel();
        jTextMoto = new javax.swing.JTextField();
        lMoto = new javax.swing.JLabel();
        lEuro36 = new javax.swing.JLabel();
        lFCorrecion5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextObservacionesGe = new javax.swing.JTextPane();

        setMaximumSize(new java.awt.Dimension(361, 725));
        setMinimumSize(new java.awt.Dimension(361, 725));
        setPreferredSize(new java.awt.Dimension(361, 725));

        lTurismo.setForeground(new java.awt.Color(0, 0, 100));
        lTurismo.setLabelFor(jTextTurismo);
        lTurismo.setText("Turismo");
        lTurismo.setName("lTurismo"); // NOI18N

        jTextTurismo.setName("jTextTurismo"); // NOI18N
        jTextTurismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTurismoActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Guardar");
        jButtonModificar.setName("jButtonModificar"); // NOI18N
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        lFCorrecion.setFont(new java.awt.Font("Tahoma", 1, 11));
        lFCorrecion.setForeground(new java.awt.Color(170, 16, 4));
        lFCorrecion.setText("TIPO DE VEHÍCULO");
        lFCorrecion.setName("lFCorrecion"); // NOI18N

        lFLM.setForeground(new java.awt.Color(0, 0, 100));
        lFLM.setLabelFor(jTextTurismo);
        lFLM.setText("Furgoneta ligera o Monovolumen");
        lFLM.setName("lFLM"); // NOI18N

        jTextFLM.setName("jTextFLM"); // NOI18N

        lFurgoneta.setForeground(new java.awt.Color(0, 0, 100));
        lFurgoneta.setLabelFor(jTextTurismo);
        lFurgoneta.setText("Furgoneta");
        lFurgoneta.setName("lFurgoneta"); // NOI18N

        jTextFurgoneta.setName("jTextFurgoneta"); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator3.setName("jSeparator3"); // NOI18N

        jTextFurgon.setName("jTextFurgon"); // NOI18N

        lFurgon.setForeground(new java.awt.Color(0, 0, 100));
        lFurgon.setLabelFor(jTextTurismo);
        lFurgon.setText("Furgón");
        lFurgon.setName("lFurgon"); // NOI18N

        lSuv.setForeground(new java.awt.Color(0, 0, 100));
        lSuv.setLabelFor(jTextTurismo);
        lSuv.setText("SUV");
        lSuv.setName("lSuv"); // NOI18N

        jTextDias.setName("jTextDias"); // NOI18N

        jTextSuv.setName("jTextSuv"); // NOI18N

        lFCorrecion3.setFont(new java.awt.Font("Tahoma", 1, 11));
        lFCorrecion3.setForeground(new java.awt.Color(170, 16, 4));
        lFCorrecion3.setText("DÍAS HÁBILES MÁXIMOS DE ENTREGA");
        lFCorrecion3.setName("lFCorrecion3"); // NOI18N

        lDias.setForeground(new java.awt.Color(0, 0, 100));
        lDias.setText("Días");
        lDias.setName("lDias"); // NOI18N

        l4x4.setForeground(new java.awt.Color(0, 0, 100));
        l4x4.setLabelFor(jTextTurismo);
        l4x4.setText("Todoterreno");
        l4x4.setName("l4x4"); // NOI18N

        jTex4x4.setName("jTex4x4"); // NOI18N

        lEuro28.setForeground(new java.awt.Color(0, 0, 100));
        lEuro28.setText("€ / Km.");
        lEuro28.setName("lEuro28"); // NOI18N

        lEuro29.setForeground(new java.awt.Color(0, 0, 100));
        lEuro29.setText("€ / Km.");
        lEuro29.setName("lEuro29"); // NOI18N

        lEuro30.setForeground(new java.awt.Color(0, 0, 100));
        lEuro30.setText("€ / Km.");
        lEuro30.setName("lEuro30"); // NOI18N

        lEuro31.setForeground(new java.awt.Color(0, 0, 100));
        lEuro31.setText("€ / Km.");
        lEuro31.setName("lEuro31"); // NOI18N

        lEuro32.setForeground(new java.awt.Color(0, 0, 100));
        lEuro32.setText("€ / Km.");
        lEuro32.setName("lEuro32"); // NOI18N

        lEuro33.setForeground(new java.awt.Color(0, 0, 100));
        lEuro33.setText("€ / Km.");
        lEuro33.setName("lEuro33"); // NOI18N

        lEspecial.setForeground(new java.awt.Color(0, 0, 100));
        lEspecial.setLabelFor(jTextTurismo);
        lEspecial.setText("Especial");
        lEspecial.setName("lEspecial"); // NOI18N

        jTextEspecial.setName("jTextEspecial"); // NOI18N

        lEuro34.setForeground(new java.awt.Color(0, 0, 100));
        lEuro34.setText("€ / Km.");
        lEuro34.setName("lEuro34"); // NOI18N

        jSeparator4.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator4.setName("jSeparator4"); // NOI18N

        jSeparator8.setBackground(new java.awt.Color(0, 102, 51));
        jSeparator8.setForeground(new java.awt.Color(0, 102, 51));
        jSeparator8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 53), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jSeparator8.setName("jSeparator8"); // NOI18N
        jSeparator8.setOpaque(true);
        jSeparator8.setPreferredSize(new java.awt.Dimension(5, 5));

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextObservaciones.setAutoscrolls(false);
        jTextObservaciones.setName("jTextObservaciones"); // NOI18N
        jTextObservaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextObservacionesFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTextObservaciones);

        lFCorrecion4.setFont(new java.awt.Font("Tahoma", 1, 11));
        lFCorrecion4.setForeground(new java.awt.Color(170, 16, 4));
        lFCorrecion4.setText("TEXTO OBSERVACIONES PROVEEDOR");
        lFCorrecion4.setName("lFCorrecion4"); // NOI18N

        jSeparator5.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator5.setName("jSeparator5"); // NOI18N

        lCarroSobre.setForeground(new java.awt.Color(0, 0, 100));
        lCarroSobre.setLabelFor(jTextTurismo);
        lCarroSobre.setText("Carrozados y Sobredimensionados");
        lCarroSobre.setName("lCarroSobre"); // NOI18N

        jTextCaSo.setName("jTextCaSo"); // NOI18N

        lEuro35.setForeground(new java.awt.Color(0, 0, 100));
        lEuro35.setText("€ / Km.");
        lEuro35.setName("lEuro35"); // NOI18N

        jTextMoto.setName("jTextMoto"); // NOI18N

        lMoto.setForeground(new java.awt.Color(0, 0, 100));
        lMoto.setLabelFor(jTextTurismo);
        lMoto.setText("Moto");
        lMoto.setName("lMoto"); // NOI18N

        lEuro36.setForeground(new java.awt.Color(0, 0, 100));
        lEuro36.setText("€ / Km.");
        lEuro36.setName("lEuro36"); // NOI18N

        lFCorrecion5.setFont(new java.awt.Font("Tahoma", 1, 11));
        lFCorrecion5.setForeground(new java.awt.Color(170, 16, 4));
        lFCorrecion5.setText("TEXTO OBSERVACIONES GENERALES");
        lFCorrecion5.setName("lFCorrecion5"); // NOI18N

        jSeparator6.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator6.setName("jSeparator6"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTextObservacionesGe.setAutoscrolls(false);
        jTextObservacionesGe.setName("jTextObservacionesGe"); // NOI18N
        jTextObservacionesGe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextObservacionesGeFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(jTextObservacionesGe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMoto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEspecial)
                            .addComponent(lSuv)
                            .addComponent(lFurgon)
                            .addComponent(lFurgoneta)
                            .addComponent(l4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTurismo)
                            .addComponent(lFLM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(lCarroSobre, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFLM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTex4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextMoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTurismo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCaSo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEspecial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSuv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jTextFurgon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFurgoneta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lEuro36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEuro35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEuro34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEuro33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEuro32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEuro31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEuro30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEuro28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEuro29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lFCorrecion5)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextDias, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lDias)
                        .addGap(120, 120, 120))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lFCorrecion3)
                        .addGap(62, 62, 62))
                    .addComponent(lFCorrecion, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lFCorrecion4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTex4x4, jTextCaSo, jTextDias, jTextEspecial, jTextFLM, jTextFurgon, jTextFurgoneta, jTextMoto, jTextSuv, jTextTurismo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jSeparator3, jSeparator4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFCorrecion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTurismo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro28)
                    .addComponent(jTextTurismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFLM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFLM)
                    .addComponent(lEuro29))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l4x4)
                    .addComponent(jTex4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro30))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFurgoneta)
                    .addComponent(jTextFurgoneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro31))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFurgon)
                    .addComponent(jTextFurgon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro32))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSuv)
                    .addComponent(jTextSuv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro33))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEspecial)
                    .addComponent(jTextEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro34))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCarroSobre)
                    .addComponent(jTextCaSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro35))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMoto)
                    .addComponent(jTextMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEuro36))
                .addGap(18, 18, 18)
                .addComponent(lFCorrecion3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDias))
                .addGap(20, 20, 20)
                .addComponent(lFCorrecion4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lFCorrecion5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonModificar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextDias, jTextFLM, jTextFurgon, jTextFurgoneta, jTextSuv, jTextTurismo});

    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
 
        System.out.println("\nBoton Servicios Cliente.");

        String turismo = new String(jTextTurismo.getText());
        String flm = new String(jTextFLM.getText());
        String todoterreno = new String(jTex4x4.getText());
        String especial = new String(jTextEspecial.getText());
        String furgonetas = new String(jTextFurgoneta.getText());
        String furgones = new String(jTextFurgon.getText());
        String suv = new String(jTextSuv.getText());
        String carroSobre = new String(jTextCaSo.getText());
        String moto = new String(jTextMoto.getText());
        String dias = new String(jTextDias.getText());
        String textAsistencia = new String(jTextObservaciones.getText());
        String textGeneral = new String(jTextObservacionesGe.getText());        

        int exist = 0;
        try {
            exist = buscarServiciosCliente(cl_id, null);
        } catch (SQLException ex) {
            Logger.getLogger(CSServicioClienteNew.class.getName()).log(Level.SEVERE, null, ex);
        }
        String query = "";
        if (exist > 0){
            query = "UPDATE sv_servicios SET sv_turismo  = '"+turismo+"', sv_flm  = '"+flm+"', " +
                    "sv_todoterreno  = '"+todoterreno+"', sv_furgoneta  = '"+furgonetas+"', " +
                    "sv_furgon  = '"+furgones+"', sv_suv  = '"+suv+"', sv_especial  = '"+especial+"', " +
                    "sv_carro_sobredim = '"+carroSobre+"', sv_moto = '"+moto+"', sv_dias= '"+dias+"', " +
                    "sv_text_asistencia= '"+textAsistencia+"' , sv_text_general= '"+textGeneral+"' " +
                    "WHERE cl_id = "+ cl_id+"";
        }else{
            query = "INSERT INTO sv_servicios (sv_turismo, sv_flm, sv_todoterreno, sv_furgoneta, sv_furgon, sv_suv, " +
                    "sv_especial, sv_dias, cl_id, sv_text_asistencia, sv_carro_sobredim, sv_moto, sv_text_general) values (" +
                    "'"+turismo+"', '"+flm+"', '"+todoterreno+"', '"+furgonetas+"', '"+furgones+"', '"+suv+"', '"+especial+"', " +
                    "'"+dias+"',  '"+ cl_id+"', '"+textAsistencia+"', '"+carroSobre+"', '"+moto+"', '"+textGeneral+"')";
        }
        System.out.println(query);
        boolean rs = CSDesktop.datos.manipuladorDatos(query);

        if(rs)
        {
            jButtonModificar.setEnabled(false);
            JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
            JOptionPane.showMessageDialog(null,errorFields);
            jButtonModificar.setEnabled(true);
        }
        else
        {
            jButtonModificar.setEnabled(false);
            JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>Los datos se han guardado correctamente.</FONT></HTML>");
            JOptionPane.showMessageDialog(null, mensaje);
            jButtonModificar.setEnabled(true);
            CSDesktop.ServicioCliente.dispose();
            CSDesktop.EditarClienteNew.setVisible(true);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    public Dimension getPreferredSize()
    {
      return new Dimension( 370,630 );
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

           CSDesktop.EditarClienteNew.setEnabled(true);
           CSDesktop.ServicioCliente.dispose();
           CSDesktop.EditarClienteNew.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextTurismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTurismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTurismoActionPerformed

    private void jTextObservacionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextObservacionesFocusLost
        String ObservacionesM = jTextObservaciones.getText().toUpperCase();
        jTextObservaciones.setText(ObservacionesM);
}//GEN-LAST:event_jTextObservacionesFocusLost

    private void jTextObservacionesGeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextObservacionesGeFocusLost
        String ObservacionesG = jTextObservacionesGe.getText().toUpperCase();
        jTextObservacionesGe.setText(ObservacionesG);
    }//GEN-LAST:event_jTextObservacionesGeFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTex4x4;
    private javax.swing.JTextField jTextCaSo;
    private javax.swing.JTextField jTextDias;
    private javax.swing.JTextField jTextEspecial;
    private javax.swing.JTextField jTextFLM;
    private javax.swing.JTextField jTextFurgon;
    private javax.swing.JTextField jTextFurgoneta;
    private javax.swing.JTextField jTextMoto;
    private javax.swing.JTextPane jTextObservaciones;
    private javax.swing.JTextPane jTextObservacionesGe;
    private javax.swing.JTextField jTextSuv;
    private javax.swing.JTextField jTextTurismo;
    private javax.swing.JLabel l4x4;
    private javax.swing.JLabel lCarroSobre;
    private javax.swing.JLabel lDias;
    private javax.swing.JLabel lEspecial;
    private javax.swing.JLabel lEuro28;
    private javax.swing.JLabel lEuro29;
    private javax.swing.JLabel lEuro30;
    private javax.swing.JLabel lEuro31;
    private javax.swing.JLabel lEuro32;
    private javax.swing.JLabel lEuro33;
    private javax.swing.JLabel lEuro34;
    private javax.swing.JLabel lEuro35;
    private javax.swing.JLabel lEuro36;
    private javax.swing.JLabel lFCorrecion;
    private javax.swing.JLabel lFCorrecion3;
    private javax.swing.JLabel lFCorrecion4;
    private javax.swing.JLabel lFCorrecion5;
    private javax.swing.JLabel lFLM;
    private javax.swing.JLabel lFurgon;
    private javax.swing.JLabel lFurgoneta;
    private javax.swing.JLabel lMoto;
    private javax.swing.JLabel lSuv;
    private javax.swing.JLabel lTurismo;
    // End of variables declaration//GEN-END:variables

    public void ValidarFormatos(String accion)
    {
         jButtonModificar.setEnabled(false);
         JLabel errorFields = new JLabel(accion);
         JOptionPane.showMessageDialog(null,errorFields);
         jButtonModificar.setEnabled(true);
    }

    private void limitacionesCampos()
    {
        LimitadorDeDocumento limitador4= new LimitadorDeDocumento(10);
        jTextFLM.setDocument(limitador4);
        LimitadorDeDocumento limitadorFurgones= new LimitadorDeDocumento(10);
        jTextFurgoneta.setDocument(limitadorFurgones);
        LimitadorDeDocumento limitadorIndustrial= new LimitadorDeDocumento(10);
        jTextTurismo.setDocument(limitadorIndustrial);
    }

    /**
     * Insertar los servicios especiales del cliente desde el cliente de plantilla
     * @param cliente
     */
    public int buscarServiciosCliente(int idCliente, String campo) throws SQLException
    {
        int exist = 0;

        String query = "SELECT count(1) as cont ";

        if(campo !=null){
            query = query + campo;
        }

        query = query + " FROM sv_servicios WHERE cl_id = '"+idCliente+"'";
        System.out.println(query);
        ResultSet rsExist = CSDesktop.datos.select(query);
        try {
            rsExist.next();
        } catch (SQLException ex) {
            Logger.getLogger(CSServicioClienteNew.class.getName()).log(Level.SEVERE, null, ex);
        }
        exist = rsExist.getInt("cont");
        rsExist.close();

        return exist;
    }
}