/*
 * ABAnyadirCliente.java
 *
 * Created on 03-oct-2009, 0:25:10
 */

package neg;

import utils.Utilidades;
import utils.LimitadorDeDocumento;
import data.DbConnection;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author lito
 */
public class CSServicioCliente extends javax.swing.JPanel
{

    DbConnection datos = new DbConnection();
    String sc_id = "";
    int cl_id = 0;
    /** Creates new form ABAnyadirCliente */
    public CSServicioCliente(String query, int cliente) throws SQLException
    {

        ResultSet rs = datos.select(query);
        
        CSDesktop.EditarCliente.setEnabled(false);
        initComponents();
        limitacionesCampos();
        cl_id = cliente;
        int numeroFila = 0;
        try {
            while (rs.next()) {
                sc_id = rs.getString("sc_id");
                jTextNumero.setText(sc_id);
                jTextIndustrial.setText(rs.getString("sc_industrial"));
                jText4x4.setText(rs.getString("sc_todoterreno"));
                jTextFurgonetas.setText(rs.getString("sc_furgonetas"));
                jTextFurgones.setText(rs.getString("sc_furgones"));
                jTextItv.setText(rs.getString("sc_itv"));
                jTextPreItv.setText(rs.getString("sc_pre_itv"));
                jTextChequeo.setText(rs.getString("sc_chequeo"));
                jTextReacondicionamiento.setText(rs.getString("sc_reacondicionamiento"));
                jTextCampa.setText(rs.getString("sc_campa"));
                jTextCampaEntrada.setText(rs.getString("sc_entrada_campa"));
                jTextLavadoEx.setText(rs.getString("sc_lavado"));
                jTextLavadoINEX.setText(rs.getString("sc_lavado_exin"));
                jTextLavadoXtr.setText(rs.getString("sc_lavado_extra"));
                jTextLavadoCo.setText(rs.getString("sc_completo"));
                jTextLavadoHi.setText(rs.getString("sc_higienizado"));
                jTextIdaVuelta.setText(rs.getString("sc_ida_vuelta"));
                jTextUrgente.setText(rs.getString("sc_urgente"));
                jTextSuplemento.setText(rs.getString("sc_suplemento"));
                numeroFila++;
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(CSResultBuscarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        CSDesktop.ServicioCliente = new JInternalFrame("Sercicios Especiales de Cliente", true, false, false, true );
        CSDesktop.ServicioCliente.getContentPane().add( this, BorderLayout.CENTER );
        CSDesktop.ServicioCliente.pack();
        CSDesktop.ServicioCliente.dispose();
        CSDesktop.elEscritorio.add( CSDesktop.ServicioCliente );
        Dimension pantalla = CSDesktop.elEscritorio.getSize();
        Dimension ventana = CSDesktop.ServicioCliente.getSize();
        CSDesktop.ServicioCliente.setLocation(
           (pantalla.width - ventana.width) / 2,
           (pantalla.height - ventana.height) / 2);
        CSDesktop.ServicioCliente.setVisible( true );

         
        KeyListener l = new KeyListener()
        {
            public void keyTyped(KeyEvent e) {}
            public void keyPressed(KeyEvent e)
            {
               if (e.getKeyCode() == KeyEvent.VK_ENTER)
               {
                    jButtonModificar.doClick();
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE)
                {
                    jButtonCancelar.doClick();
                }
            }
            public void keyReleased(KeyEvent e) {}
        };
        
        addKeyListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lIndustrial = new javax.swing.JLabel();
        jTextIndustrial = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        lNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lFCorrecion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l4x4 = new javax.swing.JLabel();
        jText4x4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lFurgonetas = new javax.swing.JLabel();
        jTextFurgonetas = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTextItv = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lItv = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lFCorrecion1 = new javax.swing.JLabel();
        jTextLavadoEx = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextIdaVuelta = new javax.swing.JTextField();
        lFCorrecion2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lCampa = new javax.swing.JLabel();
        lIdaVuelta = new javax.swing.JLabel();
        jTextCampa = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ltantoxciento = new javax.swing.JLabel();
        lEuro = new javax.swing.JLabel();
        lEuro1 = new javax.swing.JLabel();
        lEuro2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lCampaEntrada = new javax.swing.JLabel();
        jTextCampaEntrada = new javax.swing.JTextField();
        lEuro3 = new javax.swing.JLabel();
        lEuro4 = new javax.swing.JLabel();
        lEuro5 = new javax.swing.JLabel();
        jTextPreItv = new javax.swing.JTextField();
        lPreItv1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lLavado1 = new javax.swing.JLabel();
        jTextReacondicionamiento = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lChequeo = new javax.swing.JLabel();
        jTextChequeo = new javax.swing.JTextField();
        lEuro6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lLavadoEx = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lLavadoEx1 = new javax.swing.JLabel();
        jTextLavadoINEX = new javax.swing.JTextField();
        lEuro7 = new javax.swing.JLabel();
        lLavadoCo = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextLavadoCo = new javax.swing.JTextField();
        lEuro8 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lLavadoXtr = new javax.swing.JLabel();
        jTextLavadoXtr = new javax.swing.JTextField();
        lEuro9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lLavadoHi = new javax.swing.JLabel();
        jTextLavadoHi = new javax.swing.JTextField();
        lEuro10 = new javax.swing.JLabel();
        jTextFurgones = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lFurgones = new javax.swing.JLabel();
        jTextUrgente = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        lUrgente = new javax.swing.JLabel();
        ltantoxciento1 = new javax.swing.JLabel();
        jTextSuplemento = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        lSuplemento = new javax.swing.JLabel();
        lEuro11 = new javax.swing.JLabel();

        lIndustrial.setForeground(new java.awt.Color(0, 0, 100));
        lIndustrial.setLabelFor(jTextIndustrial);
        lIndustrial.setText("Industrial y Monovolumen");
        lIndustrial.setName("lIndustrial"); // NOI18N

        jTextIndustrial.setName("jTextIndustrial"); // NOI18N

        jButtonModificar.setText("Modificar");
        jButtonModificar.setName("jButtonModificar"); // NOI18N
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonCancelar.setForeground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        lNumero.setForeground(new java.awt.Color(0, 0, 100));
        lNumero.setText("    Nº. Servicio  SC/");
        lNumero.setName("lNumero"); // NOI18N

        jTextNumero.setEditable(false);
        jTextNumero.setEnabled(false);
        jTextNumero.setName("jTextNumero"); // NOI18N

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("* Campos obligatorios");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("*");
        jLabel8.setName("jLabel8"); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator2.setName("jSeparator2"); // NOI18N

        lFCorrecion.setFont(new java.awt.Font("Tahoma", 1, 11));
        lFCorrecion.setForeground(new java.awt.Color(170, 16, 4));
        lFCorrecion.setText("FACTOR DE CORRECIÓN");
        lFCorrecion.setName("lFCorrecion"); // NOI18N

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("*");
        jLabel9.setName("jLabel9"); // NOI18N

        l4x4.setForeground(new java.awt.Color(0, 0, 100));
        l4x4.setLabelFor(jTextIndustrial);
        l4x4.setText("Todoterreno");
        l4x4.setName("l4x4"); // NOI18N

        jText4x4.setName("jText4x4"); // NOI18N

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("*");
        jLabel12.setName("jLabel12"); // NOI18N

        lFurgonetas.setForeground(new java.awt.Color(0, 0, 100));
        lFurgonetas.setLabelFor(jTextIndustrial);
        lFurgonetas.setText("Furgonetas");
        lFurgonetas.setName("lFurgonetas"); // NOI18N

        jTextFurgonetas.setName("jTextFurgonetas"); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator3.setName("jSeparator3"); // NOI18N

        jTextItv.setName("jTextItv"); // NOI18N

        jSeparator4.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator4.setName("jSeparator4"); // NOI18N

        lItv.setForeground(new java.awt.Color(0, 0, 100));
        lItv.setLabelFor(jTextIndustrial);
        lItv.setText("ITV");
        lItv.setName("lItv"); // NOI18N

        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("*");
        jLabel16.setName("jLabel16"); // NOI18N

        lFCorrecion1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lFCorrecion1.setForeground(new java.awt.Color(170, 16, 4));
        lFCorrecion1.setText("SERVICIOS ESPECIALES");
        lFCorrecion1.setName("lFCorrecion1"); // NOI18N

        jTextLavadoEx.setName("jTextLavadoEx"); // NOI18N

        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("*");
        jLabel18.setName("jLabel18"); // NOI18N

        jSeparator5.setForeground(new java.awt.Color(170, 16, 4));
        jSeparator5.setName("jSeparator5"); // NOI18N

        jTextIdaVuelta.setName("jTextIdaVuelta"); // NOI18N

        lFCorrecion2.setFont(new java.awt.Font("Tahoma", 1, 11));
        lFCorrecion2.setForeground(new java.awt.Color(170, 16, 4));
        lFCorrecion2.setText("OTROS");
        lFCorrecion2.setName("lFCorrecion2"); // NOI18N

        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("*");
        jLabel17.setName("jLabel17"); // NOI18N

        lCampa.setForeground(new java.awt.Color(0, 0, 100));
        lCampa.setLabelFor(jTextIndustrial);
        lCampa.setText("Campa");
        lCampa.setName("lCampa"); // NOI18N

        lIdaVuelta.setForeground(new java.awt.Color(0, 0, 100));
        lIdaVuelta.setLabelFor(jTextIndustrial);
        lIdaVuelta.setText("Ida-Vuelta");
        lIdaVuelta.setName("lIdaVuelta"); // NOI18N

        jTextCampa.setName("jTextCampa"); // NOI18N

        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*");
        jLabel19.setName("jLabel19"); // NOI18N

        ltantoxciento.setForeground(new java.awt.Color(0, 0, 100));
        ltantoxciento.setText("%");
        ltantoxciento.setName("ltantoxciento"); // NOI18N

        lEuro.setForeground(new java.awt.Color(0, 0, 100));
        lEuro.setText("€");
        lEuro.setName("lEuro"); // NOI18N

        lEuro1.setForeground(new java.awt.Color(0, 0, 100));
        lEuro1.setText("€");
        lEuro1.setName("lEuro1"); // NOI18N

        lEuro2.setForeground(new java.awt.Color(0, 0, 100));
        lEuro2.setText("€");
        lEuro2.setName("lEuro2"); // NOI18N

        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("*");
        jLabel20.setName("jLabel20"); // NOI18N

        lCampaEntrada.setForeground(new java.awt.Color(0, 0, 100));
        lCampaEntrada.setLabelFor(jTextIndustrial);
        lCampaEntrada.setText("Coste Entrada Campa");
        lCampaEntrada.setName("lCampaEntrada"); // NOI18N

        jTextCampaEntrada.setName("jTextCampaEntrada"); // NOI18N

        lEuro3.setForeground(new java.awt.Color(0, 0, 100));
        lEuro3.setText("€");
        lEuro3.setName("lEuro3"); // NOI18N

        lEuro4.setForeground(new java.awt.Color(0, 0, 100));
        lEuro4.setText("€");
        lEuro4.setName("lEuro4"); // NOI18N

        lEuro5.setForeground(new java.awt.Color(0, 0, 100));
        lEuro5.setText("€");
        lEuro5.setName("lEuro5"); // NOI18N

        jTextPreItv.setName("jTextPreItv"); // NOI18N

        lPreItv1.setForeground(new java.awt.Color(0, 0, 100));
        lPreItv1.setLabelFor(jTextIndustrial);
        lPreItv1.setText("Pre-ITV");
        lPreItv1.setName("lPreItv1"); // NOI18N

        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("*");
        jLabel21.setName("jLabel21"); // NOI18N

        lLavado1.setForeground(new java.awt.Color(0, 0, 100));
        lLavado1.setLabelFor(jTextIndustrial);
        lLavado1.setText("Reacondicionamiento");
        lLavado1.setName("lLavado1"); // NOI18N

        jTextReacondicionamiento.setName("jTextReacondicionamiento"); // NOI18N

        jLabel22.setForeground(new java.awt.Color(204, 0, 0));
        jLabel22.setText("*");
        jLabel22.setName("jLabel22"); // NOI18N

        lChequeo.setForeground(new java.awt.Color(0, 0, 100));
        lChequeo.setLabelFor(jTextIndustrial);
        lChequeo.setText("Chequeo");
        lChequeo.setName("lChequeo"); // NOI18N

        jTextChequeo.setName("jTextChequeo"); // NOI18N

        lEuro6.setForeground(new java.awt.Color(0, 0, 100));
        lEuro6.setText("€");
        lEuro6.setName("lEuro6"); // NOI18N

        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("*");
        jLabel23.setName("jLabel23"); // NOI18N

        lLavadoEx.setForeground(new java.awt.Color(0, 0, 100));
        lLavadoEx.setLabelFor(jTextIndustrial);
        lLavadoEx.setText("Lavado Exterior");
        lLavadoEx.setName("lLavadoEx"); // NOI18N

        jLabel24.setForeground(new java.awt.Color(204, 0, 0));
        jLabel24.setText("*");
        jLabel24.setName("jLabel24"); // NOI18N

        lLavadoEx1.setForeground(new java.awt.Color(0, 0, 100));
        lLavadoEx1.setLabelFor(jTextIndustrial);
        lLavadoEx1.setText("Lavado Interior y Exterior");
        lLavadoEx1.setName("lLavadoEx1"); // NOI18N

        jTextLavadoINEX.setName("jTextLavadoINEX"); // NOI18N

        lEuro7.setForeground(new java.awt.Color(0, 0, 100));
        lEuro7.setText("€");
        lEuro7.setName("lEuro7"); // NOI18N

        lLavadoCo.setForeground(new java.awt.Color(0, 0, 100));
        lLavadoCo.setLabelFor(jTextIndustrial);
        lLavadoCo.setText("Lavado Completo");
        lLavadoCo.setName("lLavadoCo"); // NOI18N

        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("*");
        jLabel25.setName("jLabel25"); // NOI18N

        jTextLavadoCo.setName("jTextLavadoCo"); // NOI18N

        lEuro8.setForeground(new java.awt.Color(0, 0, 100));
        lEuro8.setText("€");
        lEuro8.setName("lEuro8"); // NOI18N

        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("*");
        jLabel26.setName("jLabel26"); // NOI18N

        lLavadoXtr.setForeground(new java.awt.Color(0, 0, 100));
        lLavadoXtr.setLabelFor(jTextIndustrial);
        lLavadoXtr.setText("Lavado Extra");
        lLavadoXtr.setName("lLavadoXtr"); // NOI18N

        jTextLavadoXtr.setName("jTextLavadoXtr"); // NOI18N

        lEuro9.setForeground(new java.awt.Color(0, 0, 100));
        lEuro9.setText("€");
        lEuro9.setName("lEuro9"); // NOI18N

        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        jLabel27.setText("*");
        jLabel27.setName("jLabel27"); // NOI18N

        lLavadoHi.setForeground(new java.awt.Color(0, 0, 100));
        lLavadoHi.setLabelFor(jTextIndustrial);
        lLavadoHi.setText("Lavado Higienizado");
        lLavadoHi.setName("lLavadoHi"); // NOI18N

        jTextLavadoHi.setName("jTextLavadoHi"); // NOI18N

        lEuro10.setForeground(new java.awt.Color(0, 0, 100));
        lEuro10.setText("€");
        lEuro10.setName("lEuro10"); // NOI18N

        jTextFurgones.setName("jTextFurgones"); // NOI18N

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("*");
        jLabel13.setName("jLabel13"); // NOI18N

        lFurgones.setForeground(new java.awt.Color(0, 0, 100));
        lFurgones.setLabelFor(jTextIndustrial);
        lFurgones.setText("Furgones");
        lFurgones.setName("lFurgones"); // NOI18N

        jTextUrgente.setName("jTextUrgente"); // NOI18N

        jLabel28.setForeground(new java.awt.Color(204, 0, 0));
        jLabel28.setText("*");
        jLabel28.setName("jLabel28"); // NOI18N

        lUrgente.setForeground(new java.awt.Color(0, 0, 100));
        lUrgente.setLabelFor(jTextIndustrial);
        lUrgente.setText("Urgente");
        lUrgente.setName("lUrgente"); // NOI18N

        ltantoxciento1.setForeground(new java.awt.Color(0, 0, 100));
        ltantoxciento1.setText("%");
        ltantoxciento1.setName("ltantoxciento1"); // NOI18N

        jTextSuplemento.setName("jTextSuplemento"); // NOI18N

        jLabel29.setForeground(new java.awt.Color(204, 0, 0));
        jLabel29.setText("*");
        jLabel29.setName("jLabel29"); // NOI18N

        lSuplemento.setForeground(new java.awt.Color(0, 0, 100));
        lSuplemento.setLabelFor(jTextIndustrial);
        lSuplemento.setText("Suplemento");
        lSuplemento.setName("lSuplemento"); // NOI18N

        lEuro11.setForeground(new java.awt.Color(0, 0, 100));
        lEuro11.setText("€");
        lEuro11.setName("lEuro11"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lFCorrecion)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lIndustrial))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel12))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lFurgonetas)
                                                .addComponent(l4x4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lFurgones)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jText4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextIndustrial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFurgonetas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFurgones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lFCorrecion1)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lLavadoXtr))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lLavadoHi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel18))
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lItv)
                                            .addComponent(lPreItv1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lLavadoCo)
                                            .addComponent(lLavadoEx1)
                                            .addComponent(lLavadoEx)
                                            .addComponent(lChequeo)
                                            .addComponent(lLavado1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextItv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(lEuro1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                                .addComponent(jTextPreItv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addComponent(lEuro5))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTextChequeo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addComponent(lEuro6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextLavadoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addComponent(lEuro2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextReacondicionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addComponent(lEuro4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextLavadoINEX, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addComponent(lEuro7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextLavadoCo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addComponent(lEuro8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextLavadoXtr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addComponent(lEuro9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextLavadoHi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addComponent(lEuro10)))))))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lFCorrecion2)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lUrgente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lCampaEntrada))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lCampa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lIdaVuelta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lSuplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextIdaVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                        .addComponent(ltantoxciento))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextCampaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addComponent(lEuro3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextCampa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addComponent(lEuro))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextUrgente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextSuplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lEuro11)
                                            .addComponent(ltantoxciento1)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(641, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNumero)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lFCorrecion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextIndustrial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(lIndustrial))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText4x4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(l4x4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFurgonetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lFurgonetas)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFurgones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lFurgones)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lFCorrecion1)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEuro1)
                            .addComponent(jTextItv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(lItv))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEuro5)
                            .addComponent(jTextPreItv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPreItv1)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEuro6)
                            .addComponent(jTextChequeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lChequeo)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextReacondicionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lLavado1)
                            .addComponent(jLabel21)
                            .addComponent(lEuro4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextLavadoEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEuro2)
                            .addComponent(jLabel16)
                            .addComponent(lLavadoEx))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextLavadoINEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEuro7)
                            .addComponent(lLavadoEx1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jTextLavadoCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEuro8)
                            .addComponent(lLavadoCo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lLavadoXtr)
                            .addComponent(jLabel26)
                            .addComponent(jTextLavadoXtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEuro9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lLavadoHi)
                            .addComponent(jLabel27)
                            .addComponent(jTextLavadoHi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEuro10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lIdaVuelta)
                                    .addComponent(jLabel19)
                                    .addComponent(jTextIdaVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ltantoxciento))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(lCampa)
                                    .addComponent(jTextCampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lEuro))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(lCampaEntrada)
                                    .addComponent(jTextCampaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lEuro3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextUrgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)
                                    .addComponent(lUrgente)
                                    .addComponent(ltantoxciento1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lFCorrecion2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextSuplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(lSuplemento)
                            .addComponent(lEuro11))))
                .addGap(63, 63, 63)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModificar)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonCancelar))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
 
            System.out.println("\nBoton Guardar de Añadir Clientes.");
            
            String numero = new String(jTextNumero.getText());
            String campa = new String(jTextCampa.getText());
            String entradaCampa = new String(jTextCampaEntrada.getText());
            String todoterreno = new String(jText4x4.getText());
            String furgonetas = new String(jTextFurgonetas.getText());
            String furgones = new String(jTextFurgones.getText());
            String industrial = new String(jTextIndustrial.getText());
            String idaVuelta = new String(jTextIdaVuelta.getText());
            String chequeo = new String(jTextChequeo.getText());
            String reacondicionamiento = new String(jTextReacondicionamiento.getText());
            String lavado = new String(jTextLavadoEx.getText());
            String lavadoExIn = new String(jTextLavadoINEX.getText());
            String lavadoCo = new String(jTextLavadoCo.getText());
            String lavadoEx = new String(jTextLavadoEx.getText());
            String lavadoHi = new String(jTextLavadoHi.getText());
            String itv = new String(jTextItv.getText());
            String preItv = new String(jTextPreItv.getText());
            String urgente = new String(jTextUrgente.getText());
            String suplemento = new String(jTextSuplemento.getText());
            
            //CAMPOS OBLIGATORIOS
            if (!Utilidades.campoObligatorio(campa,"Campa").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(campa,"Campa"));
            }
            else if (!Utilidades.campoObligatorio(todoterreno,"todoterreno").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(todoterreno,"todoterreno"));
            }
            else if (!Utilidades.campoObligatorio(furgones,"Furgones").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(furgones,"Furgones"));
            }
            else if (!Utilidades.campoObligatorio(furgonetas,"Furgonetas").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(furgonetas,"Furgonetas"));
            }
            else if (!Utilidades.campoObligatorio(industrial,"Industrial").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(industrial,"Industrial"));
            }
            else if (!Utilidades.campoObligatorioCombo(idaVuelta,"Ida y vuelta").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorioCombo(idaVuelta,"Ida y vuelta"));
            }
            else if (!Utilidades.campoObligatorio(lavado,"Lavado").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(lavado,"Lavado"));
            }
            else if (!Utilidades.campoObligatorio(preItv,"Pre-ITV").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(preItv,"Pre-itv"));
            }
            else if (!Utilidades.campoObligatorio(urgente,"Urgente").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(urgente,"Urgente"));
            }
            else if (!Utilidades.campoObligatorio(suplemento,"Suplemento").equals("OK"))
            {
                 ValidarFormatos(Utilidades.campoObligatorio(suplemento,"Suplemento"));
            }

            //VALIDACION DE FORMATOS
           /*else if (!industrial.equals("") && Utilidades.validarNumericoDecimal(industrial).equals("OK")) {
                    double industrialN = Double.valueOf(industrial).doubleValue();             
            }*/
            else
            {
                String query = "UPDATE sc_servicios_clientes SET sc_industrial = '" + industrial + "', sc_todoterreno = '" + todoterreno + "', " +
                               "sc_furgonetas = '" + furgonetas + "', sc_furgones = '" + furgones + "', sc_itv = '" + itv + "', sc_pre_itv = '" + preItv + "', " +
                               "sc_chequeo = '" + chequeo + "',sc_reacondicionamiento = '"+ reacondicionamiento + "', sc_campa= '" + campa + "', " +
                               "sc_entrada_campa ='" + entradaCampa+"',sc_lavado = '"+ lavado + "', sc_lavado_exin = '"+ lavadoExIn + "', " +
                               "sc_lavado_extra ='" + lavadoEx+"', sc_completo = '"+ lavadoCo + "', sc_higienizado = '"+ lavadoHi + "', " +
                               "sc_ida_vuelta = '"+ idaVuelta + "', sc_urgente = '"+ urgente + "', sc_suplemento = '"+ suplemento + "', cl_id = "+ cl_id+"  " +
                               "WHERE sc_id = "+ numero+"";

                System.out.println(query);
                boolean rs = datos.manipuladorDatos(query);
                System.out.println(rs);
                if(rs)
                {
                    jButtonModificar.setEnabled(false);
                    JLabel errorFields = new JLabel("<HTML><FONT COLOR = Blue>Se ha producido un error al guardar en la base de datos</FONT></HTML>");
                    JOptionPane.showMessageDialog(null,errorFields);
                    jButtonModificar.setEnabled(true);
                }
                else
                {
                    jButtonModificar.setEnabled(false);
                    JLabel mensaje = new JLabel("<HTML><FONT COLOR = Blue>Los datos se han guardado correctamente.</FONT></HTML>");
                    JOptionPane.showMessageDialog(null, mensaje);
                    jButtonModificar.setEnabled(true);
                    CSDesktop.ServicioCliente.dispose();
                    CSDesktop.EditarCliente.setVisible(true);
                }
            }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    public Dimension getPreferredSize()
    {
      return new Dimension( 826,605 );
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
            {
               CSDesktop.EditarCliente.setEnabled(true);
               CSDesktop.ServicioCliente.dispose();
               CSDesktop.EditarCliente.setVisible(true);
            }
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jText4x4;
    private javax.swing.JTextField jTextCampa;
    private javax.swing.JTextField jTextCampaEntrada;
    private javax.swing.JTextField jTextChequeo;
    private javax.swing.JTextField jTextFurgones;
    private javax.swing.JTextField jTextFurgonetas;
    private javax.swing.JTextField jTextIdaVuelta;
    private javax.swing.JTextField jTextIndustrial;
    private javax.swing.JTextField jTextItv;
    private javax.swing.JTextField jTextLavadoCo;
    private javax.swing.JTextField jTextLavadoEx;
    private javax.swing.JTextField jTextLavadoHi;
    private javax.swing.JTextField jTextLavadoINEX;
    private javax.swing.JTextField jTextLavadoXtr;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPreItv;
    private javax.swing.JTextField jTextReacondicionamiento;
    private javax.swing.JTextField jTextSuplemento;
    private javax.swing.JTextField jTextUrgente;
    private javax.swing.JLabel l4x4;
    private javax.swing.JLabel lCampa;
    private javax.swing.JLabel lCampaEntrada;
    private javax.swing.JLabel lChequeo;
    private javax.swing.JLabel lEuro;
    private javax.swing.JLabel lEuro1;
    private javax.swing.JLabel lEuro10;
    private javax.swing.JLabel lEuro11;
    private javax.swing.JLabel lEuro2;
    private javax.swing.JLabel lEuro3;
    private javax.swing.JLabel lEuro4;
    private javax.swing.JLabel lEuro5;
    private javax.swing.JLabel lEuro6;
    private javax.swing.JLabel lEuro7;
    private javax.swing.JLabel lEuro8;
    private javax.swing.JLabel lEuro9;
    private javax.swing.JLabel lFCorrecion;
    private javax.swing.JLabel lFCorrecion1;
    private javax.swing.JLabel lFCorrecion2;
    private javax.swing.JLabel lFurgones;
    private javax.swing.JLabel lFurgonetas;
    private javax.swing.JLabel lIdaVuelta;
    private javax.swing.JLabel lIndustrial;
    private javax.swing.JLabel lItv;
    private javax.swing.JLabel lLavado1;
    private javax.swing.JLabel lLavadoCo;
    private javax.swing.JLabel lLavadoEx;
    private javax.swing.JLabel lLavadoEx1;
    private javax.swing.JLabel lLavadoHi;
    private javax.swing.JLabel lLavadoXtr;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lPreItv1;
    private javax.swing.JLabel lSuplemento;
    private javax.swing.JLabel lUrgente;
    private javax.swing.JLabel ltantoxciento;
    private javax.swing.JLabel ltantoxciento1;
    // End of variables declaration//GEN-END:variables

    public void ValidarFormatos(String accion)
    {
         jButtonModificar.setEnabled(false);
         JLabel errorFields = new JLabel(accion);
         JOptionPane.showMessageDialog(null,errorFields);
         jButtonModificar.setEnabled(true);
    }


     private void limitacionesCampos()
    {
        LimitadorDeDocumento limitador4= new LimitadorDeDocumento(10);
        jText4x4.setDocument(limitador4);
        LimitadorDeDocumento limitadorFurgones= new LimitadorDeDocumento(10);
        jTextFurgonetas.setDocument(limitadorFurgones);
        LimitadorDeDocumento limitadorIdaVuelta = new LimitadorDeDocumento(10);
        jTextIdaVuelta.setDocument(limitadorIdaVuelta);
        LimitadorDeDocumento limitadorIndustrial= new LimitadorDeDocumento(10);
        jTextIndustrial.setDocument(limitadorIndustrial);
        LimitadorDeDocumento limitadorPreItv= new LimitadorDeDocumento(10);
        jTextItv.setDocument(limitadorPreItv);
        LimitadorDeDocumento limitadorLavado= new LimitadorDeDocumento(10);
        jTextLavadoEx.setDocument(limitadorLavado);
        LimitadorDeDocumento limitadorCampa= new LimitadorDeDocumento(10);
        jTextCampa.setDocument(limitadorCampa);

    }

}